CREATE View SL.vwAPHist AS

SELECT 
	 [BegBal] as BeginBalance
	,RTRIM([CpnyID]) as CompanyId
	,RTRIM([CuryID]) as CurrencyId
	,RTRIM([FiscYr]) as FiscalYear
	,[NoteId]
	,[PerNbr] as PeriodNumber
	,[PtdCrAdjs00] as CreditAdjustments00
	,[PtdCrAdjs01] as CreditAdjustments01
	,[PtdCrAdjs02] as CreditAdjustments02
	,[PtdCrAdjs03] as CreditAdjustments03
	,[PtdCrAdjs04] as CreditAdjustments04
	,[PtdCrAdjs05] as CreditAdjustments05
	,[PtdCrAdjs06] as CreditAdjustments06
	,[PtdCrAdjs07] as CreditAdjustments07
	,[PtdCrAdjs08] as CreditAdjustments08
	,[PtdCrAdjs09] as CreditAdjustments09
	,[PtdCrAdjs10] as CreditAdjustments10
	,[PtdCrAdjs11] as CreditAdjustments11
	,[PtdCrAdjs12] as CreditAdjustments12
	,[PtdDiscTkn00] as DiscountsTaken00
	,[PtdDiscTkn01] as DiscountsTaken01
	,[PtdDiscTkn02] as DiscountsTaken02
	,[PtdDiscTkn03] as DiscountsTaken03
	,[PtdDiscTkn04] as DiscountsTaken04
	,[PtdDiscTkn05] as DiscountsTaken05
	,[PtdDiscTkn06] as DiscountsTaken06	
	,[PtdDiscTkn07] as DiscountsTaken07
	,[PtdDiscTkn08] as DiscountsTaken08
	,[PtdDiscTkn09] as DiscountsTaken09
	,[PtdDiscTkn10] as DiscountsTaken10
	,[PtdDiscTkn11] as DiscountsTaken11
	,[PtdDiscTkn12] as DiscountsTaken12
	,[PtdDrAdjs00] as DebitAdjustments00
	,[PtdDrAdjs01] as DebitAdjustments01
	,[PtdDrAdjs02] as DebitAdjustments02	
	,[PtdDrAdjs03] as DebitAdjustments03
	,[PtdDrAdjs04] as DebitAdjustments04
	,[PtdDrAdjs05] as DebitAdjustments05
	,[PtdDrAdjs06] as DebitAdjustments06
	,[PtdDrAdjs07] as DebitAdjustments07
	,[PtdDrAdjs08] as DebitAdjustments08
	,[PtdDrAdjs09] as DebitAdjustments09
	,[PtdDrAdjs10] as DebitAdjustments10
	,[PtdDrAdjs11] as DebitAdjustments11
	,[PtdDrAdjs12] as DebitAdjustments12
	,[PtdPaymt00] as Payments00
	,[PtdPaymt01] as Payments01
	,[PtdPaymt02] as Payments02
	,[PtdPaymt03] as Payments03
	,[PtdPaymt04] as Payments04
	,[PtdPaymt05] as Payments05
	,[PtdPaymt06] as Payments06
	,[PtdPaymt07] as Payments07
	,[PtdPaymt08] as Payments08
	,[PtdPaymt09] as Payments09
	,[PtdPaymt10] as Payments10
	,[PtdPaymt11] as Payments11
	,[PtdPaymt12] as Payments12
	,[PtdPurch00] as Purchases00
	,[PtdPurch01] as Purchases01
	,[PtdPurch02] as Purchases02
	,[PtdPurch03] as Purchases03
	,[PtdPurch04] as Purchases04
	,[PtdPurch05] as Purchases05
	,[PtdPurch06] as Purchases06
	,[PtdPurch07] as Purchases07
	,[PtdPurch08] as Purchases08
	,[PtdPurch09] as Purchases09
	,[PtdPurch10] as Purchases10
	,[PtdPurch11] as Purchases11
	,[PtdPurch12] as Purchases12
	,RTRIM([VendId]) as VendorId
	,[YtdCrAdjs] as YearToDateCreditAdjustments
	,[YtdDiscTkn] as YearToDateDiscountsTaken
	,[YtdDrAdjs] as YearToDateDebitAdjustments
	,[YtdPaymt] as YearToDatePayments
	,[YtdPurch] as YearToDatePurchases
	,[LUpd_DateTime] AS LastUpdate
	,GETUTCDATE() AS ImportDate
FROM [SL].[APHist]