CREATE View [SL].[vwARHist] AS

SELECT 
	 [AccruedRevBegBal] as AccruedRevenueBeginBalance
	,[BegBal] as BeginBalance
	,RTRIM([CpnyID] ) as CompanyId
	,RTRIM([CuryID]) as CurrencyId
	,RTRIM([CustId]) as CustomerId
	,RTRIM([FiscYr]) as FiscalYear
	,[NbrInvcPaid00] as NumberOfInvoicesPaid00
	,[NbrInvcPaid01] as NumberOfInvoicesPaid01
	,[NbrInvcPaid02] as NumberOfInvoicesPaid02
	,[NbrInvcPaid03] as NumberOfInvoicesPaid03
	,[NbrInvcPaid04] as NumberOfInvoicesPaid04
	,[NbrInvcPaid05] as NumberOfInvoicesPaid05
	,[NbrInvcPaid06] as NumberOfInvoicesPaid06
	,[NbrInvcPaid07] as NumberOfInvoicesPaid07
	,[NbrInvcPaid08] as NumberOfInvoicesPaid08
	,[NbrInvcPaid09] as NumberOfInvoicesPaid09
	,[NbrInvcPaid10] as NumberOfInvoicesPaid10
	,[NbrInvcPaid11] as NumberOfInvoicesPaid11
	,[NbrInvcPaid12] as NumberOfInvoicesPaid12
	,[NoteId]
	,[PaidInvcDays00] as PaidInvoiceDays00
	,[PaidInvcDays01] as PaidInvoiceDays01
	,[PaidInvcDays02] as PaidInvoiceDays02
	,[PaidInvcDays03] as PaidInvoiceDays03
	,[PaidInvcDays04] as PaidInvoiceDays04
	,[PaidInvcDays05] as PaidInvoiceDays05
	,[PaidInvcDays06] as PaidInvoiceDays06
	,[PaidInvcDays07] as PaidInvoiceDays07
	,[PaidInvcDays08] as PaidInvoiceDays08
	,[PaidInvcDays09] as PaidInvoiceDays09
	,[PaidInvcDays10] as PaidInvoiceDays10
	,[PaidInvcDays11] as PaidInvoiceDays11
	,[PaidInvcDays12] as PaidInvoiceDays12
	,[PerNbr] as PeriodNumber
	,[PTDAccruedRev00] as AccruedRevenueChange00
	,[PTDAccruedRev01] as AccruedRevenueChange01
	,[PTDAccruedRev02] as AccruedRevenueChange02
	,[PTDAccruedRev03] as AccruedRevenueChange03
	,[PTDAccruedRev04] as AccruedRevenueChange04
	,[PTDAccruedRev05] as AccruedRevenueChange05
	,[PTDAccruedRev06] as AccruedRevenueChange06
	,[PTDAccruedRev07] as AccruedRevenueChange07
	,[PTDAccruedRev08] as AccruedRevenueChange08
	,[PTDAccruedRev09] as AccruedRevenueChange09
	,[PTDAccruedRev10] as AccruedRevenueChange10
	,[PTDAccruedRev11] as AccruedRevenueChange11
	,[PTDAccruedRev12] as AccruedRevenueChange12
	,[PTDCOGS00] as CostOfGoodsSoldTotal00
	,[PTDCOGS01] as CostOfGoodsSoldTotal01
	,[PTDCOGS02] as CostOfGoodsSoldTotal02
	,[PTDCOGS03] as CostOfGoodsSoldTotal03
	,[PTDCOGS04] as CostOfGoodsSoldTotal04
	,[PTDCOGS05] as CostOfGoodsSoldTotal05
	,[PTDCOGS06] as CostOfGoodsSoldTotal06
	,[PTDCOGS07] as CostOfGoodsSoldTotal07
	,[PTDCOGS08] as CostOfGoodsSoldTotal08
	,[PTDCOGS09] as CostOfGoodsSoldTotal09
	,[PTDCOGS10] as CostOfGoodsSoldTotal10
	,[PTDCOGS11] as CostOfGoodsSoldTotal11
	,[PTDCOGS12] as CostOfGoodsSoldTotal12
	,[PTDCrMemo00] as CreditMemoTotal00
	,[PTDCrMemo01] as CreditMemoTotal01
	,[PTDCrMemo02] as CreditMemoTotal02
	,[PTDCrMemo03] as CreditMemoTotal03
	,[PTDCrMemo04] as CreditMemoTotal04
	,[PTDCrMemo05] as CreditMemoTotal05
	,[PTDCrMemo06] as CreditMemoTotal06
	,[PTDCrMemo07] as CreditMemoTotal07
	,[PTDCrMemo08] as CreditMemoTotal08
	,[PTDCrMemo09] as CreditMemoTotal09
	,[PTDCrMemo10] as CreditMemoTotal10
	,[PTDCrMemo11] as CreditMemoTotal11
	,[PTDCrMemo12] as CreditMemoTotal12
	,[PTDDisc00] as DiscountTotal00
	,[PTDDisc01] as DiscountTotal01
	,[PTDDisc02] as DiscountTotal02
	,[PTDDisc03] as DiscountTotal03
	,[PTDDisc04] as DiscountTotal04
	,[PTDDisc05] as DiscountTotal05
	,[PTDDisc06] as DiscountTotal06
	,[PTDDisc07] as DiscountTotal07
	,[PTDDisc08] as DiscountTotal08
	,[PTDDisc09] as DiscountTotal09
	,[PTDDisc10] as DiscountTotal10
	,[PTDDisc11] as DiscountTotal11
	,[PTDDisc12] as DiscountTotal12
	,[PTDDrMemo00] as DebitMemoTotal00
	,[PTDDrMemo01] as DebitMemoTotal01
	,[PTDDrMemo02] as DebitMemoTotal02
	,[PTDDrMemo03] as DebitMemoTotal03
	,[PTDDrMemo04] as DebitMemoTotal04
	,[PTDDrMemo05] as DebitMemoTotal05
	,[PTDDrMemo06] as DebitMemoTotal06
	,[PTDDrMemo07] as DebitMemoTotal07
	,[PTDDrMemo08] as DebitMemoTotal08
	,[PTDDrMemo09] as DebitMemoTotal09
	,[PTDDrMemo10] as DebitMemoTotal10
	,[PTDDrMemo11] as DebitMemoTotal11
	,[PTDDrMemo12] as DebitMemoTotal12
	,[PTDFinChrg00] as FinanceChargeTotal00
	,[PTDFinChrg01] as FinanceChargeTotal01
	,[PTDFinChrg02] as FinanceChargeTotal02
	,[PTDFinChrg03] as FinanceChargeTotal03
	,[PTDFinChrg04] as FinanceChargeTotal04
	,[PTDFinChrg05] as FinanceChargeTotal05
	,[PTDFinChrg06] as FinanceChargeTotal06
	,[PTDFinChrg07] as FinanceChargeTotal07
	,[PTDFinChrg08] as FinanceChargeTotal08
	,[PTDFinChrg09] as FinanceChargeTotal09
	,[PTDFinChrg10] as FinanceChargeTotal10
	,[PTDFinChrg11] as FinanceChargeTotal11
	,[PTDFinChrg12] as FinanceChargeTotal12
	,[PTDRcpt00] as PaymentReceivedTotal00
	,[PTDRcpt01] as PaymentReceivedTotal01
	,[PTDRcpt02] as PaymentReceivedTotal02
	,[PTDRcpt03] as PaymentReceivedTotal03
	,[PTDRcpt04] as PaymentReceivedTotal04
	,[PTDRcpt05] as PaymentReceivedTotal05
	,[PTDRcpt06] as PaymentReceivedTotal06
	,[PTDRcpt07] as PaymentReceivedTotal07
	,[PTDRcpt08] as PaymentReceivedTotal08
	,[PTDRcpt09] as PaymentReceivedTotal09
	,[PTDRcpt10] as PaymentReceivedTotal10
	,[PTDRcpt11] as PaymentReceivedTotal11
	,[PTDRcpt12] as PaymentReceivedTotal12
	,[PTDSales00] as SaleTotal00
	,[PTDSales01] as SaleTotal01
	,[PTDSales02] as SaleTotal02
	,[PTDSales03] as SaleTotal03
	,[PTDSales04] as SaleTotal04
	,[PTDSales05] as SaleTotal05
	,[PTDSales06] as SaleTotal06
	,[PTDSales07] as SaleTotal07
	,[PTDSales08] as SaleTotal08
	,[PTDSales09] as SaleTotal09
	,[PTDSales10] as SaleTotal10
	,[PTDSales11] as SaleTotal11
	,[PTDSales12] as SaleTotal12
	,[YTDAccruedRev] as YearToDateAccruedRevenue
	,[YtdCOGS] as YearTODateCostOfGoodsSold
	,[YtdCrMemo] as YearTODateCreditMemo
	,[YtdDisc] as YearTODateDiscounts
	,[YtdDrMemo] as YearToDateDebitMemo
	,[YtdFinChrg] as YearTODateFinanceCharge
	,[YtdRcpt] as YearToDateReceipts
	,[YtdSales] as YearToDateSales
	,[LUpd_DateTime] AS LastUpdate
	,GETUTCDATE() AS ImportDate
FROM [SL].[ARHist]