CREATE TABLE [SF].[MH_Invoice_Details__c] (
    [Id]                                             NVARCHAR (18)   NOT NULL,
    [IsDeleted]                                      TINYINT         NULL,
    [Name]                                           NVARCHAR (80)   NULL,
    [RecordTypeId]                                   NVARCHAR (18)   NULL,
    [CreatedDate]                                    DATETIME        NULL,
    [CreatedById]                                    NVARCHAR (18)   NULL,
    [LastModifiedDate]                               DATETIME        NULL,
    [LastModifiedById]                               NVARCHAR (18)   NULL,
    [SystemModstamp]                                 DATETIME        NULL,
    [LastActivityDate]                               DATETIME        NULL,
    [LastViewedDate]                                 DATETIME        NULL,
    [LastReferencedDate]                             DATETIME        NULL,
    [Work_Order__c]                                  NVARCHAR (18)   NULL,
    [Vendor__c]                                      NVARCHAR (18)   NULL,
    [Line_Type__c]                                   NVARCHAR (255)  NULL,
    [Part__c]                                        NVARCHAR (18)   NULL,
    [Line_Price_per_Unit__c]                         FLOAT (53)      NULL,
    [Line_Qty__c]                                    FLOAT (53)      NULL,
    [Sales_Tax__c]                                   FLOAT (53)      NULL,
    [Invoice__c]                                     NVARCHAR (18)   NULL,
    [Add_to_Invoice__c]                              TINYINT         NULL,
    [Date_Invoiced__c]                               DATETIME        NULL,
    [Activity_Type__c]                               NVARCHAR (255)  NULL,
    [Total_Line_Price__c]                            FLOAT (53)      NULL,
    [Work_Detail__c]                                 NVARCHAR (18)   NULL,
    [T_Line_Price_per_Unit__c]                       NVARCHAR (1300) NULL,
    [Invoice_Status__c]                              NVARCHAR (1300) NULL,
    [Work_Description_idc__c]                        NVARCHAR (MAX)  NULL,
    [Unit_of_Measure_idc__c]                         NVARCHAR (255)  NULL,
    [Hide_Line_c__c]                                 TINYINT         NULL,
    [Total_Line_Price_formula__c]                    FLOAT (53)      NULL,
    [Sort_Order__c]                                  FLOAT (53)      NULL,
    [Detail_Line_Cost__c]                            FLOAT (53)      NULL,
    [Account_Vendor__r_SL_Vendor_ID__c]              NVARCHAR (15)   NULL,
    [Interface_Processed__c]                         TINYINT         NULL,
    [Account_Vendor__r_MH_SL_CustID__c]              NVARCHAR (15)   NULL,
    [Account_Vendor__r_UNITY_Account_External_Id__c] NVARCHAR (80)   NULL,
    [Product2_Part__r_UNITY_Product_External_Id__c]  NVARCHAR (80)   NULL,
    CONSTRAINT [PK_MH_Invoice_Details__c] PRIMARY KEY CLUSTERED ([Id] ASC)
);

