CREATE TABLE [SF].[SVMXC__Service_Group__c] (
    [Id]                                  NVARCHAR (18)  NOT NULL,
    [OwnerId]                             NVARCHAR (18)  NULL,
    [IsDeleted]                           TINYINT        NULL,
    [Name]                                NVARCHAR (80)  NULL,
    [RecordTypeId]                        NVARCHAR (18)  NULL,
    [CreatedDate]                         DATETIME       NULL,
    [CreatedById]                         NVARCHAR (18)  NULL,
    [LastModifiedDate]                    DATETIME       NULL,
    [LastModifiedById]                    NVARCHAR (18)  NULL,
    [SystemModstamp]                      DATETIME       NULL,
    [LastActivityDate]                    DATETIME       NULL,
    [LastViewedDate]                      DATETIME       NULL,
    [LastReferencedDate]                  DATETIME       NULL,
    [SVMXC__Active__c]                    TINYINT        NULL,
    [SVMXC__City__c]                      NVARCHAR (100) NULL,
    [SVMXC__Country__c]                   NVARCHAR (255) NULL,
    [SVMXC__Description__c]               NVARCHAR (255) NULL,
    [SVMXC__Email__c]                     NVARCHAR (80)  NULL,
    [SVMXC__Group_Code__c]                NVARCHAR (100) NULL,
    [SVMXC__Group_Type__c]                NVARCHAR (255) NULL,
    [SVMXC__Latitude__c]                  FLOAT (53)     NULL,
    [SVMXC__Longitude__c]                 FLOAT (53)     NULL,
    [SVMXC__Phone__c]                     NVARCHAR (40)  NULL,
    [SVMXC__Select__c]                    TINYINT        NULL,
    [SVMXC__State__c]                     NVARCHAR (100) NULL,
    [SVMXC__Street__c]                    NVARCHAR (255) NULL,
    [SVMXC__Zip__c]                       NVARCHAR (100) NULL,
    [Super_Center__c]                     NVARCHAR (255) NULL,
    [Segment__c]                          NVARCHAR (255) NULL,
    [Company_Code__c]                     NVARCHAR (25)  NULL,
    [Company__c]                          NVARCHAR (25)  NULL,
    [Company_Legal_Name__c]               NVARCHAR (40)  NULL,
    [SVMXC__Optimizer_Connection_Name__c] NVARCHAR (100) NULL,
    CONSTRAINT [PK_SVMXC__Service_Group__c] PRIMARY KEY CLUSTERED ([Id] ASC)
);

