CREATE TABLE [SF].[SVMXC__Service_Order_Line__c] (
    [Id]                                     NVARCHAR (18)   NOT NULL,
    [IsDeleted]                              TINYINT         NULL,
    [Name]                                   NVARCHAR (80)   NULL,
    [RecordTypeId]                           NVARCHAR (18)   NULL,
    [CreatedDate]                            DATETIME        NULL,
    [CreatedById]                            NVARCHAR (18)   NULL,
    [LastModifiedDate]                       DATETIME        NULL,
    [LastModifiedById]                       NVARCHAR (18)   NULL,
    [SystemModstamp]                         DATETIME        NULL,
    [LastViewedDate]                         DATETIME        NULL,
    [LastReferencedDate]                     DATETIME        NULL,
    [SVMXC__Service_Order__c]                NVARCHAR (18)   NULL,
    [SVMXC__Activity_Type__c]                NVARCHAR (255)  NULL,
    [SVMXC__Actual_Price2__c]                FLOAT (53)      NULL,
    [SVMXC__Actual_Quantity2__c]             FLOAT (53)      NULL,
    [SVMXC__Canceled_By__c]                  NVARCHAR (18)   NULL,
    [SVMXC__Canceled_On__c]                  DATETIME        NULL,
    [SVMXC__Closed_By__c]                    NVARCHAR (18)   NULL,
    [SVMXC__Closed_On__c]                    DATETIME        NULL,
    [SVMXC__Consumed_From_Location__c]       NVARCHAR (18)   NULL,
    [SVMXC__Cost_Category__c]                NVARCHAR (255)  NULL,
    [SVMXC__Date_Received__c]                DATETIME        NULL,
    [SVMXC__Date_Requested__c]               DATETIME        NULL,
    [SVMXC__Discount__c]                     FLOAT (53)      NULL,
    [SVMXC__End_Date_and_Time__c]            DATETIME        NULL,
    [SVMXC__Estimated_Price2__c]             FLOAT (53)      NULL,
    [SVMXC__Estimated_Quantity2__c]          FLOAT (53)      NULL,
    [SVMXC__Expense_Type__c]                 NVARCHAR (255)  NULL,
    [SVMXC__From_Location__c]                NVARCHAR (18)   NULL,
    [SVMXC__Group_Member__c]                 NVARCHAR (18)   NULL,
    [SVMXC__Include_in_Quote__c]             TINYINT         NULL,
    [SVMXC__Is_Billable__c]                  TINYINT         NULL,
    [SVMXC__Line_Status__c]                  NVARCHAR (255)  NULL,
    [SVMXC__Line_Type__c]                    NVARCHAR (255)  NULL,
    [SVMXC__Log_Against__c]                  NVARCHAR (255)  NULL,
    [SVMXC__Posted_To_Inventory__c]          TINYINT         NULL,
    [SVMXC__Product__c]                      NVARCHAR (18)   NULL,
    [SVMXC__Quantity_Shipment_Initiated2__c] FLOAT (53)      NULL,
    [SVMXC__Quantity_Shipped2__c]            FLOAT (53)      NULL,
    [SVMXC__Received_City__c]                NVARCHAR (100)  NULL,
    [SVMXC__Received_Country__c]             NVARCHAR (255)  NULL,
    [SVMXC__Received_Location__c]            NVARCHAR (18)   NULL,
    [SVMXC__Received_Quantity2__c]           FLOAT (53)      NULL,
    [SVMXC__Received_State__c]               NVARCHAR (100)  NULL,
    [SVMXC__Received_Street__c]              NVARCHAR (255)  NULL,
    [SVMXC__Received_Zip__c]                 NVARCHAR (100)  NULL,
    [SVMXC__Reference_Information__c]        NVARCHAR (MAX)  NULL,
    [SVMXC__Requested_City__c]               NVARCHAR (100)  NULL,
    [SVMXC__Requested_Country__c]            NVARCHAR (255)  NULL,
    [SVMXC__Requested_Location__c]           NVARCHAR (18)   NULL,
    [SVMXC__Requested_Quantity2__c]          FLOAT (53)      NULL,
    [SVMXC__Requested_State__c]              NVARCHAR (100)  NULL,
    [SVMXC__Requested_Street__c]             NVARCHAR (255)  NULL,
    [SVMXC__Requested_Zip__c]                NVARCHAR (100)  NULL,
    [SVMXC__Select__c]                       TINYINT         NULL,
    [SVMXC__Serial_Number__c]                NVARCHAR (18)   NULL,
    [SVMXC__Service_Group__c]                NVARCHAR (18)   NULL,
    [SVMXC__Start_Date_and_Time__c]          DATETIME        NULL,
    [SVMXC__Total_Estimated_Price__c]        FLOAT (53)      NULL,
    [SVMXC__Total_Line_Price__c]             FLOAT (53)      NULL,
    [SVMXC__Use_Price_From_Pricebook__c]     TINYINT         NULL,
    [SVMXC__Work_Description__c]             NVARCHAR (MAX)  NULL,
    [Estimate_or_Actual_Price__c]            FLOAT (53)      NULL,
    [SVMXC__Applied_Rate_Type__c]            NVARCHAR (255)  NULL,
    [SVMXC__Covered__c]                      FLOAT (53)      NULL,
    [SVMXC__Billable_Line_Price__c]          FLOAT (53)      NULL,
    [SVMXC__Billable_Quantity__c]            FLOAT (53)      NULL,
    [SVMXC__Billing_Information__c]          NVARCHAR (MAX)  NULL,
    [SVMXC__Product_Warranty__c]             NVARCHAR (18)   NULL,
    [SVMXC__Work_Detail__c]                  NVARCHAR (18)   NULL,
    [Vendor__c]                              NVARCHAR (18)   NULL,
    [Labor_Type__c]                          NVARCHAR (255)  NULL,
    [Labor_Price_Per_Unit__c]                FLOAT (53)      NULL,
    [Add_to_Invoice__c]                      TINYINT         NULL,
    [Total_Line_PriceMH__c]                  FLOAT (53)      NULL,
    [Part_Serial_Number__c]                  NVARCHAR (18)   NULL,
    [Labor_Time__c]                          FLOAT (53)      NULL,
    [Vendor_Status__c]                       NVARCHAR (255)  NULL,
    [Sales_Tax__c]                           FLOAT (53)      NULL,
    [Invoiced__c]                            TINYINT         NULL,
    [Date_Invoiced__c]                       DATETIME        NULL,
    [Work_Complete__c]                       TINYINT         NULL,
    [Deliver_Date__c]                        DATETIME        NULL,
    [Invoice_Detail__c]                      NVARCHAR (18)   NULL,
    [Total_Line_Price_w_Tax__c]              FLOAT (53)      NULL,
    [Parts_Order_Line__c]                    NVARCHAR (18)   NULL,
    [Vendor_Cost_Per_Unit__c]                FLOAT (53)      NULL,
    [Vendor_Order__c]                        NVARCHAR (50)   NULL,
    [Segment__c]                             NVARCHAR (1300) NULL,
    [Supercenter__c]                         NVARCHAR (1300) NULL,
    [Day_Comments__c]                        NVARCHAR (MAX)  NULL,
    [Installed_Product_c__c]                 NVARCHAR (18)   NULL,
    [Unit_of_Measure__c]                     NVARCHAR (25)   NULL,
    [Total_Cost__c]                          FLOAT (53)      NULL,
    [Inv_Line_Qty_c__c]                      FLOAT (53)      NULL,
    [Actual_Time_c__c]                       FLOAT (53)      NULL,
    [TechID__c]                              NVARCHAR (1300) NULL,
    [Hide_Line__c]                           TINYINT         NULL,
    [Voucher__c]                             TINYINT         NULL,
    [Technician_c__c]                        NVARCHAR (18)   NULL,
    [Sort_Order__c]                          FLOAT (53)      NULL,
    [Non_Inventory_Part__c]                  TINYINT         NULL,
    [WD_Created_Date__c]                     DATETIME        NULL,
    [Service_Report_Line__c]                 NVARCHAR (255)  NULL,
    [Integrated_IN06__c]                     TINYINT         NULL,
    [Consumed_Qty__c]                        FLOAT (53)      NULL,
    [Consumption_Qty__c]                     FLOAT (53)      NULL,
    [Consumed_Parts__c]                      TINYINT         NULL,
    [Used_Qty__c]                            FLOAT (53)      NULL,
    [Reconciled_Qty__c]                      TINYINT         NULL,
    [TechnicianWD_2__c]                      NVARCHAR (18)   NULL,
    [Conga_Vendor_Name__c]                   NVARCHAR (1300) NULL,
    [SVMXC__Serial_Number_List__c]           NVARCHAR (MAX)  NULL,
    [SVMXC__Transaction_Results__c]          NVARCHAR (MAX)  NULL,
    [Service_Report__c]                      NVARCHAR (18)   NULL,
    [Interface_Processed__c]                 TINYINT         NULL,
    [Tax_Code__c]                            NVARCHAR (18)   NULL,
    [Line_from_iPad__c]                      TINYINT         NULL,
    [Quoted_Margin_Percent__c]               FLOAT (53)      NULL,
    [Quoted_Margin__c]                       FLOAT (53)      NULL,
    [Quoted_Quantity__c]                     FLOAT (53)      NULL,
    [Quoted_Unit_Cost__c]                    FLOAT (53)      NULL,
    [Quoted_Unit_Price__c]                   FLOAT (53)      NULL,
    [Quoted__c]                              TINYINT         NULL,
    [Total_Quoted_Cost__c]                   FLOAT (53)      NULL,
    [Total_Quoted_Price__c]                  FLOAT (53)      NULL,
    [Update_Quoted_with_Actuals__c]          TINYINT         NULL,
    [Completed_By__c]                        NVARCHAR (18)   NULL,
    [Completed_Date__c]                      DATETIME        NULL,
    [SVMXC__Dead_Time__c]                    FLOAT (53)      NULL,
    [SVMXC__Entitlement_Notes__c]            NVARCHAR (MAX)  NULL,
    [SVMXC__Is_Entitlement_Performed__c]     TINYINT         NULL,
    [SVMXC__Service_Maintenance_Contract__c] NVARCHAR (18)   NULL,
    [SL_Inventory_Issued__c]                 TINYINT         NULL,
    CONSTRAINT [PK_SVMXC__Service_Order_Line__c] PRIMARY KEY CLUSTERED ([Id] ASC)
);

