CREATE TABLE [SF].[SVMXC__Site__c] (
    [Id]                                     NVARCHAR (18)   NOT NULL,
    [OwnerId]                                NVARCHAR (18)   NULL,
    [IsDeleted]                              TINYINT         NULL,
    [Name]                                   NVARCHAR (80)   NULL,
    [RecordTypeId]                           NVARCHAR (18)   NULL,
    [CreatedDate]                            DATETIME        NULL,
    [CreatedById]                            NVARCHAR (18)   NULL,
    [LastModifiedDate]                       DATETIME        NULL,
    [LastModifiedById]                       NVARCHAR (18)   NULL,
    [SystemModstamp]                         DATETIME        NULL,
    [LastActivityDate]                       DATETIME        NULL,
    [LastViewedDate]                         DATETIME        NULL,
    [LastReferencedDate]                     DATETIME        NULL,
    [SVMXC__Account__c]                      NVARCHAR (18)   NULL,
    [SVMXC__City__c]                         NVARCHAR (100)  NULL,
    [SVMXC__Costed_at_value__c]              TINYINT         NULL,
    [SVMXC__Country__c]                      NVARCHAR (255)  NULL,
    [SVMXC__Email__c]                        NVARCHAR (80)   NULL,
    [SVMXC__Inventory_Account__c]            NVARCHAR (30)   NULL,
    [SVMXC__IsPartnerRecord__c]              TINYINT         NULL,
    [SVMXC__IsPartner__c]                    NVARCHAR (1300) NULL,
    [SVMXC__Latitude__c]                     FLOAT (53)      NULL,
    [SVMXC__Longitude__c]                    FLOAT (53)      NULL,
    [SVMXC__Partner_Account__c]              NVARCHAR (18)   NULL,
    [SVMXC__Partner_Contact__c]              NVARCHAR (18)   NULL,
    [SVMXC__Service_Engineer__c]             NVARCHAR (18)   NULL,
    [SVMXC__Site_Fax__c]                     NVARCHAR (40)   NULL,
    [SVMXC__Site_Phone__c]                   NVARCHAR (40)   NULL,
    [SVMXC__State__c]                        NVARCHAR (100)  NULL,
    [SVMXC__Stocking_Location__c]            TINYINT         NULL,
    [SVMXC__Street__c]                       NVARCHAR (255)  NULL,
    [SVMXC__Web_site__c]                     NVARCHAR (255)  NULL,
    [SVMXC__Zip__c]                          NVARCHAR (100)  NULL,
    [SVMXC__IsDefault_Delivery__c]           TINYINT         NULL,
    [SVMXC__IsDelivery_Location__c]          TINYINT         NULL,
    [SVMXC__IsGood_Stock__c]                 TINYINT         NULL,
    [SVMXC__IsReceiving_Location__c]         TINYINT         NULL,
    [SVMXC__IsRepair_Location__c]            TINYINT         NULL,
    [SVMXC__IsStaging_Location__c]           TINYINT         NULL,
    [SVMXC__Location_Type__c]                NVARCHAR (255)  NULL,
    [SVMXC__Parent__c]                       NVARCHAR (18)   NULL,
    [Mass_SL_Location_ID_ID__c]              NVARCHAR (15)   NULL,
    [Contact__c]                             NVARCHAR (18)   NULL,
    [Location_Established__c]                DATETIME        NULL,
    [Labor_PM_Rate_DDM__c]                   FLOAT (53)      NULL,
    [Labor_PM_Rate_MHE__c]                   FLOAT (53)      NULL,
    [Merger_Acquisition__c]                  NVARCHAR (255)  NULL,
    [Business_Unit__c]                       NVARCHAR (255)  NULL,
    [Priority__c]                            NVARCHAR (255)  NULL,
    [Open_Work_Orders__c]                    FLOAT (53)      NULL,
    [Territory_ID__c]                        NVARCHAR (255)  NULL,
    [Travel_Time__c]                         FLOAT (53)      NULL,
    [Organization__c]                        NVARCHAR (255)  NULL,
    [AR__c]                                  NVARCHAR (1300) NULL,
    [NTE_Threshold__c]                       FLOAT (53)      NULL,
    [Super_Center__c]                        NVARCHAR (255)  NULL,
    [Segment__c]                             NVARCHAR (255)  NULL,
    [Labor_Rate_Standard__c]                 FLOAT (53)      NULL,
    [Labor_Rate_Premium__c]                  FLOAT (53)      NULL,
    [Labor_Rate_Two_Man__c]                  FLOAT (53)      NULL,
    [Customer_P_O__c]                        NVARCHAR (18)   NULL,
    [Contact2__c]                            NVARCHAR (18)   NULL,
    [Contact3__c]                            NVARCHAR (18)   NULL,
    [Contact4__c]                            NVARCHAR (18)   NULL,
    [Site_Mobile__c]                         NVARCHAR (40)   NULL,
    [Labor_Standard_DDM__c]                  FLOAT (53)      NULL,
    [Labor_Standard_MHE__c]                  FLOAT (53)      NULL,
    [Labor_2_Man_DDM__c]                     FLOAT (53)      NULL,
    [Labor_2_Man_MHE__c]                     FLOAT (53)      NULL,
    [Labor_OTDDM_DDM__c]                     FLOAT (53)      NULL,
    [Labor_OTMHE_MHE__c]                     FLOAT (53)      NULL,
    [Labor_DTDDM_DDM__c]                     FLOAT (53)      NULL,
    [Labor_DTMHE_MHE__c]                     FLOAT (53)      NULL,
    [Copy_Address__c]                        TINYINT         NULL,
    [Billing_City_c__c]                      NVARCHAR (100)  NULL,
    [Billing_State_Province_c__c]            NVARCHAR (100)  NULL,
    [Billing_Zip_Postal_Code__c]             NVARCHAR (100)  NULL,
    [Billing_Street__c]                      NVARCHAR (255)  NULL,
    [Call_Type__c]                           NVARCHAR (255)  NULL,
    [Account_Credit_Hold__c]                 TINYINT         NULL,
    [TEST_DATA_DO_NOT_USE__c]                TINYINT         NULL,
    [Chain__c]                               NVARCHAR (100)  NULL,
    [Location_Salesperson_c__c]              NVARCHAR (18)   NULL,
    [Billing_State_Province_lc__c]           NVARCHAR (255)  NULL,
    [State_lc__c]                            NVARCHAR (255)  NULL,
    [Company__c]                             NVARCHAR (10)   NULL,
    [Salesperson_lc__c]                      NVARCHAR (18)   NULL,
    [Download_To_Mobile__c]                  TINYINT         NULL,
    [Site_Contact__c]                        NVARCHAR (150)  NULL,
    [Salespersons__c]                        NVARCHAR (18)   NULL,
    [Doc_Number_Loc__c]                      NVARCHAR (1300) NULL,
    [Salesperson_2nd_Loc__c]                 NVARCHAR (18)   NULL,
    [PM_Frequency_Meter__c]                  FLOAT (53)      NULL,
    [PM_Frequency_Time__c]                   NVARCHAR (5)    NULL,
    [Asset_Mgmt_Billing_Date__c]             TINYINT         NULL,
    [Asset_Mgmt_Fees__c]                     FLOAT (53)      NULL,
    [Static_Doc_Number__c]                   NVARCHAR (20)   NULL,
    [Invoice_Doc_Date__c]                    DATETIME        NULL,
    [Retainage__c]                           FLOAT (53)      NULL,
    [Invoice_Due_Date__c]                    DATETIME        NULL,
    [Requires_Dept_Rec__c]                   TINYINT         NULL,
    [Draw_Date__c]                           NVARCHAR (4)    NULL,
    [Conga_Template__c]                      FLOAT (53)      NULL,
    [Conga_Case__c]                          NVARCHAR (1300) NULL,
    [SVMXC__Preferred_Business_Hours__c]     NVARCHAR (18)   NULL,
    [Recurring_Rental_Fees__c]               FLOAT (53)      NULL,
    [Conga_Post_to_Period__c]                NVARCHAR (1300) NULL,
    [Conga_TFS_Invoice_QueryStringField__c]  NVARCHAR (1300) NULL,
    [Conga_TFS_Invoice_QueryStringField1__c] NVARCHAR (1300) NULL,
    [Conga_TFS_Invoice_QueryStringField2__c] NVARCHAR (1300) NULL,
    [Conga1_P2P__c]                          NVARCHAR (7)    NULL,
    [Conga_Month__c]                         NVARCHAR (50)   NULL,
    [Location_Count__c]                      FLOAT (53)      NULL,
    CONSTRAINT [PK_SVMXC__Site__c] PRIMARY KEY CLUSTERED ([Id] ASC)
);

