CREATE TABLE [SF].[AccountHistory] (
    [RowId]                                     INT              NOT NULL,
    [Id]                                        NVARCHAR (18)    NOT NULL,
    [IsDeleted]                                 TINYINT          NULL,
    [MasterRecordId]                            NVARCHAR (18)    NOT NULL,
    [Name]                                      NVARCHAR (255)   NOT NULL,
    [Type]                                      NVARCHAR (40)    NOT NULL,
    [RecordTypeId]                              NVARCHAR (18)    NOT NULL,
    [ParentId]                                  NVARCHAR (18)    NOT NULL,
    [BillingStreet]                             NVARCHAR (255)   NOT NULL,
    [BillingCity]                               NVARCHAR (40)    NOT NULL,
    [BillingState]                              NVARCHAR (80)    NOT NULL,
    [BillingPostalCode]                         NVARCHAR (20)    NOT NULL,
    [BillingCountry]                            NVARCHAR (80)    NOT NULL,
    [BillingStateCode]                          NVARCHAR (10)    NOT NULL,
    [BillingCountryCode]                        NVARCHAR (10)    NOT NULL,
    [BillingLatitude]                           DECIMAL (32, 16) NULL,
    [BillingLongitude]                          DECIMAL (32, 16) NULL,
    [ShippingStreet]                            NVARCHAR (255)   NOT NULL,
    [ShippingCity]                              NVARCHAR (40)    NOT NULL,
    [ShippingState]                             NVARCHAR (80)    NOT NULL,
    [ShippingPostalCode]                        NVARCHAR (20)    NOT NULL,
    [ShippingCountry]                           NVARCHAR (80)    NOT NULL,
    [ShippingStateCode]                         NVARCHAR (10)    NOT NULL,
    [ShippingCountryCode]                       NVARCHAR (10)    NOT NULL,
    [ShippingLatitude]                          DECIMAL (32, 16) NULL,
    [ShippingLongitude]                         DECIMAL (32, 16) NULL,
    [Phone]                                     NVARCHAR (40)    NOT NULL,
    [Fax]                                       NVARCHAR (40)    NOT NULL,
    [Website]                                   NVARCHAR (255)   NOT NULL,
    [Industry]                                  NVARCHAR (40)    NOT NULL,
    [AnnualRevenue]                             DECIMAL (32, 16) NULL,
    [NumberOfEmployees]                         INT              NULL,
    [Description]                               NVARCHAR (MAX)   NOT NULL,
    [Site]                                      NVARCHAR (80)    NOT NULL,
    [OwnerId]                                   NVARCHAR (18)    NOT NULL,
    [CreatedDate]                               DATETIME2 (7)    NULL,
    [CreatedById]                               NVARCHAR (18)    NOT NULL,
    [LastModifiedDate]                          DATETIME2 (7)    NULL,
    [LastModifiedById]                          NVARCHAR (18)    NOT NULL,
    [SystemModstamp]                            DATETIME2 (7)    NULL,
    [LastActivityDate]                          DATETIME2 (7)    NULL,
    [LastViewedDate]                            DATETIME2 (7)    NULL,
    [LastReferencedDate]                        DATETIME2 (7)    NULL,
    [IsCustomerPortal]                          TINYINT          NULL,
    [Jigsaw]                                    NVARCHAR (20)    NOT NULL,
    [JigsawCompanyId]                           NVARCHAR (20)    NOT NULL,
    [AccountSource]                             NVARCHAR (40)    NOT NULL,
    [SicDescription]                            NVARCHAR (80)    NOT NULL,
    [ServiceMaxAccess_Hours]                    NVARCHAR (18)    NOT NULL,
    [ServiceMaxBusiness_Hours]                  NVARCHAR (18)    NOT NULL,
    [ServiceMaxPreferred_Technician]            NVARCHAR (18)    NOT NULL,
    [ServiceMaxLatitude]                        DECIMAL (32, 16) NULL,
    [ServiceMaxLongitude]                       DECIMAL (32, 16) NULL,
    [AccountStatus]                             NVARCHAR (255)   NOT NULL,
    [AccountFax]                                NVARCHAR (40)    NOT NULL,
    [AccountEmail]                              NVARCHAR (80)    NOT NULL,
    [ShippingPhone]                             NVARCHAR (40)    NOT NULL,
    [ShippingFax]                               NVARCHAR (40)    NOT NULL,
    [ShippingEmail]                             NVARCHAR (80)    NOT NULL,
    [PrimaryEquipmentAssetFee]                  DECIMAL (32, 16) NULL,
    [AncillaryEquipmentAssetFee]                DECIMAL (32, 16) NULL,
    [SalesTerritoryId]                          NVARCHAR (15)    NOT NULL,
    [LaborRateStandard]                         DECIMAL (32, 16) NULL,
    [AccountsReceivableCustomerAccount]         NVARCHAR (15)    NOT NULL,
    [Salesperson]                               NVARCHAR (18)    NOT NULL,
    [TemporaryAccount]                          TINYINT          NULL,
    [WorkTypes]                                 NVARCHAR (MAX)   NOT NULL,
    [LaborRatePremium]                          DECIMAL (32, 16) NULL,
    [NumbeOfLocations]                          DECIMAL (32, 16) NULL,
    [BusinessUnit]                              NVARCHAR (255)   NOT NULL,
    [Organization]                              NVARCHAR (255)   NOT NULL,
    [NteThreshold]                              DECIMAL (32, 16) NULL,
    [PrimaryContact]                            NVARCHAR (50)    NOT NULL,
    [PrimaryContactEmail]                       NVARCHAR (80)    NOT NULL,
    [LaborRateTwoMan]                           DECIMAL (32, 16) NULL,
    [AccountCellPhone]                          NVARCHAR (40)    NOT NULL,
    [VendorId]                                  NVARCHAR (10)    NOT NULL,
    [MaterialHandlingGeneralLedgerAccount]      NVARCHAR (10)    NOT NULL,
    [LeadSourceMarketing]                       NVARCHAR (255)   NOT NULL,
    [MaterialHandlingCreditLimit]               DECIMAL (32, 16) NULL,
    [MaterialHandlingSlCustomerId]              NVARCHAR (15)    NOT NULL,
    [MaterialHandlingTerms]                     NVARCHAR (2)     NOT NULL,
    [MaterialHandlingAttention]                 NVARCHAR (30)    NOT NULL,
    [CustomerIdLegacy]                          NVARCHAR (50)    NOT NULL,
    [MaterialHandlingPrimaryContact]            NVARCHAR (18)    NOT NULL,
    [PrimaryContactSalutation]                  NVARCHAR (30)    NOT NULL,
    [AverageDaysToPay]                          DECIMAL (32, 16) NULL,
    [MaterialHandlingTaxSchedule]               NVARCHAR (8)     NOT NULL,
    [MaterialHandlingBillingContact]            NVARCHAR (18)    NOT NULL,
    [MaterialHandlingCreditHold]                TINYINT          NULL,
    [MaterialHandlingCurrentBalance]            DECIMAL (32, 16) NULL,
    [MaterialHandlingCustomerType]              NVARCHAR (4)     NOT NULL,
    [MaterialHandlingEmailStatements]           TINYINT          NULL,
    [MaterialHandlingGeneralLedgerSubAccountId] NVARCHAR (24)    NULL,
    [AccountsPayableAccount]                    NVARCHAR (10)    NOT NULL,
    [AccountsPayableSubaccountId]               NVARCHAR (24)    NULL,
    [LaborPmRateDdm]                            DECIMAL (32, 16) NULL,
    [LaborPmRateMhe]                            DECIMAL (32, 16) NULL,
    [Labor_StandardDdm]                         DECIMAL (32, 16) NULL,
    [Labor_StandardMhe]                         DECIMAL (32, 16) NULL,
    [Labor2ManDdm]                              DECIMAL (32, 16) NULL,
    [Labor2ManMhe]                              DECIMAL (32, 16) NULL,
    [LaborOtdDmDdm]                             DECIMAL (32, 16) NULL,
    [LaborOtmHeMhe]                             DECIMAL (32, 16) NULL,
    [LaborDtmHeMhe]                             DECIMAL (32, 16) NULL,
    [LaborDtdDmDdm]                             DECIMAL (32, 16) NULL,
    [AccountsReceivableDivisionNumber]          NVARCHAR (5)     NOT NULL,
    [Company]                                   NVARCHAR (5)     NOT NULL,
    [RemitAddress]                              NVARCHAR (255)   NOT NULL,
    [RemitCity]                                 NVARCHAR (30)    NOT NULL,
    [RemitStateProvince]                        NVARCHAR (20)    NOT NULL,
    [RemitZipCode]                              NVARCHAR (11)    NOT NULL,
    [RemitCountry]                              NVARCHAR (25)    NOT NULL,
    [CustomerNotes]                             NVARCHAR (MAX)   NOT NULL,
    [SlVendorId]                                NVARCHAR (15)    NOT NULL,
    [BillingAttention]                          NVARCHAR (30)    NOT NULL,
    [BillingName]                               NVARCHAR (255)   NOT NULL,
    [RemitName]                                 NVARCHAR (255)   NOT NULL,
    [RemitPhone]                                NVARCHAR (40)    NOT NULL,
    [AvailableCredit]                           DECIMAL (32, 16) NULL,
    [CreditRule]                                NVARCHAR (2)     NOT NULL,
    [MinerSalesperson]                          NVARCHAR (18)    NOT NULL,
    [CustomerTypeMarketingSegmets]              NVARCHAR (255)   NOT NULL,
    [TirePress]                                 TINYINT          NULL,
    [Salesperson2]                              NVARCHAR (18)    NOT NULL,
    [DeliveryVehicles]                          NVARCHAR (MAX)   NOT NULL,
    [Grade1]                                    NVARCHAR (255)   NOT NULL,
    [Grade2]                                    NVARCHAR (255)   NOT NULL,
    [AffiliateGrade]                            NVARCHAR (MAX)   NOT NULL,
    [Docks]                                     TINYINT          NULL,
    [Doors]                                     TINYINT          NULL,
    [CustomerServiceRepresentativeCsr]          TINYINT          NULL,
    [Oem]                                       NVARCHAR (255)   NOT NULL,
    [ScissorBoomOem]                            NVARCHAR (255)   NOT NULL,
    [DeletedAccountId]                          NVARCHAR (18)    NOT NULL,
    [FaxIteration]                              NVARCHAR (MAX)   NOT NULL,
    [PhoneIteration]                            NVARCHAR (MAX)   NOT NULL,
    [PayTerms]                                  NVARCHAR (MAX)   NOT NULL,
    [DrawDate]                                  NVARCHAR (255)   NOT NULL,
    [Retainage]                                 DECIMAL (32, 16) NULL,
    [OemAffiliation]                            NVARCHAR (255)   NOT NULL,
    [VendorExpenseType]                         NVARCHAR (255)   NOT NULL,
    [AccountParentSlVendorId]                   NVARCHAR (15)    NOT NULL,
    [ReadyToConvert]                            TINYINT          NULL,
    [Affiliate]                                 TINYINT          NULL,
    [ParentAffiliate]                           NVARCHAR (18)    NOT NULL,
    [AccountCount]                              DECIMAL (32, 16) NULL,
    [DunsNumber]                                NVARCHAR (9)     NOT NULL,
    [Tradestyle]                                NVARCHAR (255)   NOT NULL,
    [NaicsCode]                                 NVARCHAR (8)     NOT NULL,
    [NaicsDesc]                                 NVARCHAR (120)   NOT NULL,
    [YearStarted]                               NVARCHAR (4)     NOT NULL,
    [ResIdential]                               TINYINT          NULL,
    [OpportunityTrade]                          NVARCHAR (MAX)   NOT NULL,
    [AccountParentMaterialHandlingSlCustomerId] NVARCHAR (15)    NOT NULL,
    [AccountApprover]                           NVARCHAR (18)    NOT NULL,
    [PhotoUrl]                                  NVARCHAR (255)   NOT NULL,
    [UnityUserOwnerAgentId]                     NVARCHAR (18)    NOT NULL,
    [IsPartner]                                 TINYINT          NULL,
    [AccountNumber]                             NVARCHAR (40)    NOT NULL,
    [Sic]                                       NVARCHAR (20)    NOT NULL,
    [Ownership]                                 NVARCHAR (40)    NOT NULL,
    [TickerSymbol]                              NVARCHAR (20)    NOT NULL,
    [Rating]                                    NVARCHAR (40)    NOT NULL,
    [AllInPmRateElectric]                       DECIMAL (32, 16) NULL,
    [AllInPmRatePropane]                        DECIMAL (32, 16) NULL,
    [ContractPaint]                             TINYINT          NULL,
    [DeliveryCapability]                        TINYINT          NULL,
    [MobileTirePressure]                        TINYINT          NULL,
    [NumberOfServiceVans]                       DECIMAL (32, 16) NULL,
    [NumberOfTechs]                             DECIMAL (32, 16) NULL,
    [OpportunityPending]                        TINYINT          NULL,
    [PmRate]                                    DECIMAL (32, 16) NULL,
    [PaintBooth]                                TINYINT          NULL,
    [PartsDept]                                 TINYINT          NULL,
    [Propane]                                   TINYINT          NULL,
    [Refurbished]                               TINYINT          NULL,
    [ServiceBatteries]                          TINYINT          NULL,
    [ServiceRate]                               DECIMAL (32, 16) NULL,
    [TirePressure3rdParty]                      TINYINT          NULL,
    [TripCharge]                                DECIMAL (32, 16) NULL,
    [TripFee]                                   TINYINT          NULL,
    [X24HourEmergencyRepair]                    TINYINT          NULL,
    [SalespersonSecond]                         NVARCHAR (18)    NOT NULL,
    [Certificate]                               NVARCHAR (25)    NOT NULL,
    [FsoActive]                                 NVARCHAR (255)   NOT NULL,
    [SuperCenter]                               NVARCHAR (18)    NOT NULL,
    [TaxId]                                     NVARCHAR (9)     NOT NULL,
    [FsoCustomerPriority]                       NVARCHAR (255)   NOT NULL,
    [FsoNumberofLocations]                      DECIMAL (32, 16) NULL,
    [FsoSlaExpirationDate]                      DATETIME2 (7)    NULL,
    [FsoSlaSerialNumber]                        NVARCHAR (10)    NOT NULL,
    [FsoSla]                                    NVARCHAR (255)   NOT NULL,
    [FsoUpsellOpportunity]                      NVARCHAR (255)   NOT NULL,
    [AccountLoop]                               NVARCHAR (18)    NOT NULL,
    [BuUniqueField]                             NVARCHAR (255)   NOT NULL,
    [SlCompanyId]                               NVARCHAR (3)     NOT NULL,
    [SsvyLastVisitedDate]                       DATETIME2 (7)    NULL,
    [SsvyTotalAssets]                           DECIMAL (32, 16) NULL,
    [SsvyTotalSiteSurveysCompleted]             DECIMAL (32, 16) NULL,
    [TimeZoneOffset]                            NVARCHAR (255)   NOT NULL,
    [UnityAccountExternalId]                    NVARCHAR (80)    NOT NULL,
    [UnityAccountId]                            NVARCHAR (30)    NOT NULL,
    [UnityAccountRoutingId]                     NVARCHAR (6)     NOT NULL,
    [UnityAgentWorkDay]                         NVARCHAR (MAX)   NOT NULL,
    [UnityAgentWorkHourEndTime]                 NVARCHAR (5)     NOT NULL,
    [UnityAgentWorkHourStartTime]               NVARCHAR (5)     NOT NULL,
    [UnityAutomobileLiabilityExpiry]            DATETIME2 (7)    NULL,
    [UnityAutomobileLiability]                  TINYINT          NULL,
    [UnityBillToAccount]                        NVARCHAR (18)    NOT NULL,
    [UnityBillToHq]                             TINYINT          NULL,
    [UnityBundling_Requirements]                NVARCHAR (255)   NOT NULL,
    [UnityBusinessUnit]                         NVARCHAR (255)   NOT NULL,
    [UnityCompanyCode]                          NVARCHAR (5)     NOT NULL,
    [UnityCustomerSize]                         NVARCHAR (255)   NOT NULL,
    [UnityCustomerTeam]                         NVARCHAR (255)   NOT NULL,
    [UnityDispatcher]                           NVARCHAR (18)    NOT NULL,
    [UnityDoNotUseFlaggedDate]                  DATETIME2 (7)    NULL,
    [UnityDoNotUseReason]                       NVARCHAR (255)   NOT NULL,
    [UnityDoNotUse]                             TINYINT          NULL,
    [UnityFridayEndTime]                        NVARCHAR (5)     NOT NULL,
    [UnityFridayStartTime]                      NVARCHAR (5)     NOT NULL,
    [UnityGeneralLiabilityExpiry]               DATETIME2 (7)    NULL,
    [UnityGeneralLiability]                     TINYINT          NULL,
    [UnityHasPreferredPart]                     TINYINT          NULL,
    [UnityHoursOfOperationSummary]              NVARCHAR (MAX)   NOT NULL,
    [UnityHoursOfOperation]                     NVARCHAR (MAX)   NOT NULL,
    [UnityIRS_ValIdated]                        TINYINT          NULL,
    [UnityIvrPhoneNumber]                       NVARCHAR (40)    NOT NULL,
    [UnityIvrPin]                               NVARCHAR (8)     NOT NULL,
    [UnityInstallationFloaterLiability]         TINYINT          NULL,
    [UnityInstallationFltLiabilityExpiry]       DATETIME2 (7)    NULL,
    [UnityIsAccountsReceivable]                 TINYINT          NULL,
    [UnityLoc]                                  NVARCHAR (20)    NOT NULL,
    [UnityMinerRegionalOffice]                  TINYINT          NULL,
    [UnityMondayEndTime]                        NVARCHAR (5)     NOT NULL,
    [UnityMondayStartTime]                      NVARCHAR (5)     NOT NULL,
    [UnityOffHourQueue]                         NVARCHAR (60)    NOT NULL,
    [UnityPassword]                             NVARCHAR (174)   NOT NULL,
    [UnityPortalURL]                            NVARCHAR (255)   NOT NULL,
    [UnityPreferred_Vendor]                     TINYINT          NULL,
    [UnityRentedEquipmentLiabilityExpiry]       DATETIME2 (7)    NULL,
    [UnityRentedEquipmentLiability]             TINYINT          NULL,
    [UnitySkillId2]                             NVARCHAR (6)     NOT NULL,
    [UnitySsn]                                  NVARCHAR (11)    NOT NULL,
    [UnitySaturdayEndTime]                      NVARCHAR (5)     NOT NULL,
    [UnitySaturdayStartTime]                    NVARCHAR (5)     NOT NULL,
    [UnityServiceChannelIvr]                    TINYINT          NULL,
    [UnityServiceContract]                      NVARCHAR (18)    NOT NULL,
    [UnityShippingLocationLatitude]             DECIMAL (32, 16) NULL,
    [UnityShippingLocationLongitude]            DECIMAL (32, 16) NULL,
    [UnitySignature_Required]                   TINYINT          NULL,
    [UnitySkillId]                              NVARCHAR (6)     NOT NULL,
    [UnitySubscriberId]                         NVARCHAR (20)    NOT NULL,
    [UnitySundayEndTime]                        NVARCHAR (5)     NOT NULL,
    [UnitySundayStartTime]                      NVARCHAR (5)     NOT NULL,
    [UnitySupportEmailAddress]                  NVARCHAR (80)    NOT NULL,
    [UnityTaxExempt]                            TINYINT          NULL,
    [UnityTaxId]                                NVARCHAR (10)    NOT NULL,
    [UnityThursdayEndTime]                      NVARCHAR (5)     NOT NULL,
    [UnityThursdayStartTime]                    NVARCHAR (5)     NOT NULL,
    [UnityTierLevel]                            NVARCHAR (255)   NOT NULL,
    [UnityTimeZoneSidKey]                       NVARCHAR (255)   NOT NULL,
    [UnityTuesdayEndTime]                       NVARCHAR (5)     NOT NULL,
    [UnityTuesdayStartTime]                     NVARCHAR (5)     NOT NULL,
    [UnityUmbrellaLiabilityExpiry]              DATETIME2 (7)    NULL,
    [UnityUmbrellaLiability]                    TINYINT          NULL,
    [UnityUsername]                             NVARCHAR (255)   NOT NULL,
    [UnityVendorScorePm]                        DECIMAL (32, 16) NULL,
    [UnityVendorScoreProject]                   DECIMAL (32, 16) NULL,
    [UnityVendorScoreSr]                        DECIMAL (32, 16) NULL,
    [UnityVendorScoreSs]                        DECIMAL (32, 16) NULL,
    [UnityVendorStatus]                         NVARCHAR (255)   NOT NULL,
    [UnityVendorTypePm]                         TINYINT          NULL,
    [UnityVendorTypeProject]                    TINYINT          NULL,
    [UnityVendorTypeSr]                         TINYINT          NULL,
    [UnityVendorTypeSs]                         TINYINT          NULL,
    [UnityW9]                                   TINYINT          NULL,
    [UnityWednesdayEndTime]                     NVARCHAR (5)     NOT NULL,
    [UnityWednesdayStartTime]                   NVARCHAR (5)     NOT NULL,
    [UnityWorkersCompenstationLiabilityExpiry]  DATETIME2 (7)    NULL,
    [UnityWorkersCompensationLiability]         TINYINT          NULL,
    [UnityMnsCustomerTeam]                      NVARCHAR (255)   NOT NULL,
    [AccountParentUnityAccountExternalId]       NVARCHAR (80)    NOT NULL,
    [UnityDoBusinessAs]                         NVARCHAR (255)   NOT NULL,
    [Unity0To30PastDue]                         DECIMAL (32, 16) NULL,
    [Unity31To60PastDue]                        DECIMAL (32, 16) NULL,
    [Unity61To90PastDue]                        DECIMAL (32, 16) NULL,
    [Unity90DaysPastDue]                        DECIMAL (32, 16) NULL,
    [UnitySlCurrentBalance]                     DECIMAL (32, 16) NULL,
    [UnityUltimateParent]                       NVARCHAR (18)    NOT NULL,
    [UnityTemplateConfiguration]                NVARCHAR (18)    NOT NULL,
    [UnityFiscalYearBasedOn]                    NVARCHAR (255)   NOT NULL,
    [UnityFiscalYearStartMonth]                 NVARCHAR (255)   NOT NULL,
    [UnityServiceReportTemplate]                NVARCHAR (50)    NOT NULL,
    [Unity3rdPartyCustomer]                     TINYINT          NULL,
    [BillingGeocodeAccuracy]                    NVARCHAR (40)    NOT NULL,
    [ShippingGeocodeAccuracy]                   NVARCHAR (40)    NOT NULL,
    [UnityCompany]                              NVARCHAR (MAX)   NOT NULL,
    [SlNotesText]                               NVARCHAR (MAX)   NOT NULL,
    [SlNotes]                                   NVARCHAR (MAX)   NOT NULL,
    [SlPromiseDate]                             DATETIME2 (7)    NULL,
    [MmpfsBuShippingAddress]                    NVARCHAR (MAX)   NOT NULL,
    [MspGoLiveDate]                             DATETIME2 (7)    NULL,
    [UnityCompanyText]                          NVARCHAR (250)   NULL,
    [UnityVendorId]                             NVARCHAR (20)    NOT NULL,
    [MspfsBuBillingAddress]                     NVARCHAR (MAX)   NOT NULL,
    [MspfsBusinessUnitLegalName]                NVARCHAR (255)   NOT NULL,
    [MspfsMSPBillToAccount]                     NVARCHAR (18)    NOT NULL,
    [UnityVendorManager]                        NVARCHAR (18)    NOT NULL,
    [UnityHasCommUnityMember]                   TINYINT          NULL,
    [UnityRecordTypeName]                       NVARCHAR (MAX)   NOT NULL,
    [UnityPmPin]                                NVARCHAR (4)     NOT NULL,
    [LastUpdate]                                DATETIME2 (7)    NOT NULL,
    [ImportDate]                                DATETIME2 (7)    NOT NULL,
    [ValidFrom]                                 DATETIME2 (7)    NOT NULL,
    [ValidTo]                                   DATETIME2 (7)    NOT NULL
);




GO
CREATE CLUSTERED INDEX [ix_AccountHistory]
    ON [SF].[AccountHistory]([ValidTo] ASC, [ValidFrom] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_AccountHistory_RowId]
    ON [SF].[AccountHistory]([RowId] ASC);

