CREATE TABLE [SF].[ServiceMaxRmaShipmentLineHistory] (
    [RowId]                                INT              NOT NULL,
    [Id]                                   NVARCHAR (18)    NOT NULL,
    [IsDeleted]                            TINYINT          NULL,
    [Name]                                 NVARCHAR (80)    NULL,
    [RecordTypeId]                         NVARCHAR (18)    NULL,
    [CreatedDate]                          DATETIME2 (7)    NULL,
    [CreatedById]                          NVARCHAR (18)    NULL,
    [LastModifiedDate]                     DATETIME2 (7)    NULL,
    [LastModifiedById]                     NVARCHAR (18)    NULL,
    [SystemModstamp]                       DATETIME2 (7)    NULL,
    [RmaShipmentOrder]                     NVARCHAR (18)    NULL,
    [ActualQuantity2]                      DECIMAL (32, 16) NULL,
    [ActualReceiptDate]                    DATETIME2 (7)    NULL,
    [ActualShipDate]                       DATETIME2 (7)    NULL,
    [CanceledBy]                           NVARCHAR (18)    NULL,
    [CanceledOn]                           DATETIME2 (7)    NULL,
    [ClosedBy]                             NVARCHAR (18)    NULL,
    [ClosedOn]                             DATETIME2 (7)    NULL,
    [DiscountPercentage]                   DECIMAL (32, 16) NULL,
    [DispositionInstructions]              NVARCHAR (MAX)   NULL,
    [Disposition]                          NVARCHAR (255)   NULL,
    [ExpectedCondition]                    NVARCHAR (255)   NULL,
    [ExpectedQuantity2]                    DECIMAL (32, 16) NULL,
    [ExpectedReceiptDate]                  DATETIME2 (7)    NULL,
    [ExpectedShipDate]                     DATETIME2 (7)    NULL,
    [LinePrice2]                           DECIMAL (32, 16) NULL,
    [LineStatus]                           NVARCHAR (255)   NULL,
    [LineType]                             NVARCHAR (255)   NULL,
    [PackingInstructions]                  NVARCHAR (MAX)   NULL,
    [PartsRequestLine]                     NVARCHAR (18)    NULL,
    [PostedToInventory]                    TINYINT          NULL,
    [Product]                              NVARCHAR (18)    NULL,
    [ReturnedCondition]                    NVARCHAR (255)   NULL,
    [SalesOrderNumber]                     NVARCHAR (100)   NULL,
    [Select]                               TINYINT          NULL,
    [SerialNumber]                         NVARCHAR (18)    NULL,
    [ServiceEngineer]                      NVARCHAR (18)    NULL,
    [ServiceOrderLine]                     NVARCHAR (18)    NULL,
    [ShipLocation]                         NVARCHAR (18)    NULL,
    [TotalLinePrice2]                      DECIMAL (32, 16) NULL,
    [UsePriceFromPricebook]                TINYINT          NULL,
    [Warehouse]                            NVARCHAR (100)   NULL,
    [CaseLine]                             NVARCHAR (18)    NULL,
    [DeliveredBy]                          NVARCHAR (18)    NULL,
    [DeliveredOn]                          DATETIME2 (7)    NULL,
    [Delivered]                            TINYINT          NULL,
    [DeliveryLocation]                     NVARCHAR (18)    NULL,
    [MasterOrderLine]                      NVARCHAR (18)    NULL,
    [PickedBy]                             NVARCHAR (18)    NULL,
    [PickedOn]                             DATETIME2 (7)    NULL,
    [PickedQuantity]                       DECIMAL (32, 16) NULL,
    [Picked]                               TINYINT          NULL,
    [ReceivedBy]                           NVARCHAR (18)    NULL,
    [ReceivedOn]                           DATETIME2 (7)    NULL,
    [Received]                             TINYINT          NULL,
    [ReconciliationAction]                 NVARCHAR (255)   NULL,
    [RouteCard]                            NVARCHAR (18)    NULL,
    [RouteStop]                            NVARCHAR (18)    NULL,
    [SerialNumber_List]                    NVARCHAR (MAX)   NULL,
    [ServiceOrder]                         NVARCHAR (18)    NULL,
    [ShippedBy]                            NVARCHAR (18)    NULL,
    [ShippedOn]                            DATETIME2 (7)    NULL,
    [Shipped]                              TINYINT          NULL,
    [WorkOrderCreated]                     TINYINT          NULL,
    [EntitlementStatus]                    NVARCHAR (255)   NULL,
    [FulfillmentQuantity]                  DECIMAL (32, 16) NULL,
    [ServiceContractEndDate]               DATETIME2 (7)    NULL,
    [ServiceContractStartDate]             DATETIME2 (7)    NULL,
    [WarrantyEndDate]                      DATETIME2 (7)    NULL,
    [WarrantyStartDate]                    DATETIME2 (7)    NULL,
    [EntitledExchangeType]                 NVARCHAR (255)   NULL,
    [StandardCost]                         DECIMAL (32, 16) NULL,
    [MaterialHandlingTotalVendorLinePrice] DECIMAL (32, 16) NULL,
    [ProductName]                          NVARCHAR (MAX)   NULL,
    [VendorPrice]                          DECIMAL (32, 16) NULL,
    [TotalStandardLinePrice]               DECIMAL (32, 16) NULL,
    [PartNumber]                           NVARCHAR (MAX)   NULL,
    [ShipVia]                              NVARCHAR (255)   NULL,
    [CrossReferenceDescription]            NVARCHAR (MAX)   NULL,
    [CrossReferencePart]                   NVARCHAR (MAX)   NULL,
    [ProductCrossReference]                NVARCHAR (18)    NULL,
    [OrderType]                            NVARCHAR (MAX)   NULL,
    [ToLocationSupercenter]                NVARCHAR (MAX)   NULL,
    [ToLocationSegment]                    NVARCHAR (MAX)   NULL,
    [SLVendorId]                           NVARCHAR (MAX)   NULL,
    [CompanyId]                            NVARCHAR (MAX)   NULL,
    [PartOrderName]                        NVARCHAR (MAX)   NULL,
    [ProductCodePd]                        NVARCHAR (100)   NULL,
    [TransactionResults]                   NVARCHAR (MAX)   NULL,
    [Description]                          NVARCHAR (1000)  NULL,
    [LastUpdate]                           DATETIME2 (7)    NOT NULL,
    [ImportDate]                           DATETIME2 (7)    NOT NULL,
    [ValidFrom]                            DATETIME2 (7)    NOT NULL,
    [ValidTo]                              DATETIME2 (7)    NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ServiceMaxRmaShipmentLineHistory_RowId]
    ON [SF].[ServiceMaxRmaShipmentLineHistory]([RowId] ASC);


GO
CREATE CLUSTERED INDEX [ix_ServiceMaxRmaShipmentLineHistory]
    ON [SF].[ServiceMaxRmaShipmentLineHistory]([ValidTo] ASC, [ValidFrom] ASC);

