CREATE TABLE [SF].[ServiceMaxSite] (
    [RowId]                            INT                                         IDENTITY (1, 1) NOT NULL,
    [Id]                               VARCHAR (18)                                NOT NULL,
    [OwnerId]                          VARCHAR (18)                                NULL,
    [IsDeleted]                        TINYINT                                     NULL,
    [Name]                             VARCHAR (80)                                NOT NULL,
    [RecordTypeId]                     VARCHAR (18)                                NOT NULL,
    [CreatedDate]                      DATETIME                                    NULL,
    [CreatedById]                      VARCHAR (18)                                NOT NULL,
    [LastModifiedDate]                 DATETIME                                    NULL,
    [LastModifiedById]                 VARCHAR (18)                                NOT NULL,
    [SystemModstamp]                   DATETIME                                    NULL,
    [LastActivityDate]                 DATETIME                                    NULL,
    [LastViewedDate]                   DATETIME                                    NULL,
    [LastReferencedDate]               DATETIME                                    NULL,
    [Account]                          VARCHAR (18)                                NOT NULL,
    [City]                             VARCHAR (100)                               NOT NULL,
    [Costedatvalue]                    TINYINT                                     NULL,
    [Country]                          VARCHAR (255)                               NOT NULL,
    [Email]                            VARCHAR (80)                                NOT NULL,
    [InventoryAccount]                 VARCHAR (30)                                NOT NULL,
    [IsPartnerRecord]                  TINYINT                                     NULL,
    [IsPartner]                        VARCHAR (MAX)                               NOT NULL,
    [Latitude]                         DECIMAL (32, 16)                            NULL,
    [Longitude]                        DECIMAL (32, 16)                            NULL,
    [PartnerAccount]                   VARCHAR (18)                                NOT NULL,
    [PartnerContact]                   VARCHAR (18)                                NOT NULL,
    [ServiceEngineer]                  VARCHAR (18)                                NOT NULL,
    [SiteFax]                          VARCHAR (40)                                NOT NULL,
    [SitePhone]                        VARCHAR (40)                                NOT NULL,
    [State]                            VARCHAR (100)                               NOT NULL,
    [StockingLocation]                 TINYINT                                     NULL,
    [Street]                           VARCHAR (255)                               NOT NULL,
    [Website]                          VARCHAR (255)                               NOT NULL,
    [Zip]                              VARCHAR (100)                               NOT NULL,
    [IsDefaultDelivery]                TINYINT                                     NULL,
    [IsDeliveryLocation]               TINYINT                                     NULL,
    [IsGoodStock]                      TINYINT                                     NULL,
    [IsReceivingLocation]              TINYINT                                     NULL,
    [IsRepairLocation]                 TINYINT                                     NULL,
    [IsStagingLocation]                TINYINT                                     NULL,
    [LocationType]                     VARCHAR (255)                               NOT NULL,
    [Parent]                           VARCHAR (18)                                NOT NULL,
    [MassSlLocationId]                 VARCHAR (15)                                NOT NULL,
    [Contact]                          VARCHAR (18)                                NOT NULL,
    [LocationEstablished]              DATETIME                                    NULL,
    [LaborPMRateDDM]                   DECIMAL (32, 16)                            NULL,
    [LaborPMRateMHE]                   DECIMAL (32, 16)                            NULL,
    [MergerAcquisition]                VARCHAR (255)                               NOT NULL,
    [BusinessUnit]                     VARCHAR (255)                               NOT NULL,
    [Priority]                         VARCHAR (255)                               NOT NULL,
    [OpenWorkOrders]                   DECIMAL (32, 16)                            NULL,
    [TerritoryId]                      VARCHAR (255)                               NOT NULL,
    [TravelTime]                       DECIMAL (32, 16)                            NULL,
    [Organization]                     VARCHAR (255)                               NOT NULL,
    [Ar]                               VARCHAR (MAX)                               NOT NULL,
    [NteThreshold]                     DECIMAL (32, 16)                            NULL,
    [SuperCenter]                      VARCHAR (255)                               NOT NULL,
    [Segment]                          NVARCHAR (255)                              NOT NULL,
    [LaborRateStandard]                DECIMAL (32, 16)                            NULL,
    [LaborRatePremium]                 DECIMAL (32, 16)                            NULL,
    [LaborRateTwoMan]                  DECIMAL (32, 16)                            NULL,
    [CustomerPo]                       VARCHAR (18)                                NOT NULL,
    [Contact2]                         VARCHAR (18)                                NOT NULL,
    [Contact3]                         VARCHAR (18)                                NOT NULL,
    [Contact4]                         VARCHAR (18)                                NOT NULL,
    [SiteMobile]                       VARCHAR (40)                                NOT NULL,
    [LaborStandardDDM]                 DECIMAL (32, 16)                            NULL,
    [LaborStandardMHE]                 DECIMAL (32, 16)                            NULL,
    [Labor2ManDDM]                     DECIMAL (32, 16)                            NULL,
    [Labor2ManMHE]                     DECIMAL (32, 16)                            NULL,
    [LaborOTDDMDDM]                    DECIMAL (32, 16)                            NULL,
    [LaborOTMHEMHE]                    DECIMAL (32, 16)                            NULL,
    [LaborDTDDMDDM]                    DECIMAL (32, 16)                            NULL,
    [LaborDTMHEMHE]                    DECIMAL (32, 16)                            NULL,
    [CopyAddress]                      TINYINT                                     NULL,
    [BillingCity]                      VARCHAR (100)                               NOT NULL,
    [BillingStateProvince]             VARCHAR (100)                               NOT NULL,
    [BillingZipPostalCode]             VARCHAR (100)                               NOT NULL,
    [BillingStreet]                    VARCHAR (255)                               NOT NULL,
    [CallType]                         VARCHAR (255)                               NOT NULL,
    [AccountCreditHold]                TINYINT                                     NULL,
    [TESTDATADONOTUSE]                 TINYINT                                     NULL,
    [Chain]                            VARCHAR (100)                               NOT NULL,
    [LocationSalesPerson]              VARCHAR (18)                                NOT NULL,
    [Company]                          VARCHAR (10)                                NOT NULL,
    [Salesperson]                      VARCHAR (18)                                NOT NULL,
    [DownloadToMobile]                 TINYINT                                     NULL,
    [SiteContact]                      VARCHAR (150)                               NOT NULL,
    [SalesPersons]                     VARCHAR (18)                                NOT NULL,
    [DocumentNumberLoc]                VARCHAR (MAX)                               NOT NULL,
    [SalesPerson2ndLoc]                VARCHAR (18)                                NOT NULL,
    [PmFrequencyMeter]                 DECIMAL (32, 16)                            NULL,
    [PmFrequencyTime]                  VARCHAR (5)                                 NOT NULL,
    [AssetManagementBillingDate]       TINYINT                                     NULL,
    [AssetManagementFees]              DECIMAL (32, 16)                            NULL,
    [StaticDocumentNumber]             VARCHAR (20)                                NOT NULL,
    [InvoiceDocumentDate]              DATETIME                                    NULL,
    [Retainage]                        DECIMAL (32, 16)                            NULL,
    [InvoiceDueDate]                   DATETIME                                    NULL,
    [RequiresDepartmentRecord]         TINYINT                                     NULL,
    [DrawDate]                         VARCHAR (4)                                 NOT NULL,
    [CongaTemplate]                    DECIMAL (32, 16)                            NULL,
    [CongaCase]                        VARCHAR (MAX)                               NOT NULL,
    [PreferredBusinessHours]           VARCHAR (18)                                NOT NULL,
    [RecurringRentalFees]              DECIMAL (32, 16)                            NULL,
    [CongaPostToPeriod]                VARCHAR (MAX)                               NOT NULL,
    [CongaTFSInvoiceQueryStringField]  VARCHAR (MAX)                               NOT NULL,
    [CongaTFSInvoiceQueryStringField1] VARCHAR (MAX)                               NOT NULL,
    [CongaTFSInvoiceQueryStringField2] VARCHAR (MAX)                               NOT NULL,
    [Conga1P2P]                        VARCHAR (7)                                 NOT NULL,
    [CongaMonth]                       VARCHAR (50)                                NOT NULL,
    [LocationCount]                    DECIMAL (32, 16)                            NULL,
    [LastUpdate]                       DATETIME2 (7)                               NOT NULL,
    [ImportDate]                       DATETIME2 (7)                               NOT NULL,
    [ValidFrom]                        DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo]                          DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PKServiceMaxSite] PRIMARY KEY CLUSTERED ([RowId] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[SF].[ServiceMaxSiteHistory], DATA_CONSISTENCY_CHECK=ON));




GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ServiceMaxSite_Id]
    ON [SF].[ServiceMaxSite]([Id] ASC);

