CREATE TABLE [SF].[UserHistory] (
    [RowId]                                              INT              NOT NULL,
    [Id]                                                 NVARCHAR (18)    NOT NULL,
    [Username]                                           NVARCHAR (80)    NULL,
    [LastName]                                           NVARCHAR (80)    NULL,
    [FirstName]                                          NVARCHAR (40)    NULL,
    [Name]                                               NVARCHAR (121)   NULL,
    [CompanyName]                                        NVARCHAR (80)    NULL,
    [Division]                                           NVARCHAR (80)    NULL,
    [Department]                                         NVARCHAR (80)    NULL,
    [Title]                                              NVARCHAR (80)    NULL,
    [Street]                                             NVARCHAR (255)   NULL,
    [City]                                               NVARCHAR (40)    NULL,
    [State]                                              NVARCHAR (80)    NULL,
    [PostalCode]                                         NVARCHAR (20)    NULL,
    [Country]                                            NVARCHAR (80)    NULL,
    [StateCode]                                          NVARCHAR (10)    NULL,
    [CountryCode]                                        NVARCHAR (10)    NULL,
    [Latitude]                                           DECIMAL (32, 16) NULL,
    [Longitude]                                          DECIMAL (32, 16) NULL,
    [Email]                                              NVARCHAR (128)   NULL,
    [EmailPreferencesAutoBcc]                            TINYINT          NULL,
    [EmailPreferencesAutoBccStayInTouch]                 TINYINT          NULL,
    [EmailPreferencesStayInTouchReminder]                TINYINT          NULL,
    [SenderEmail]                                        NVARCHAR (80)    NULL,
    [SenderName]                                         NVARCHAR (80)    NULL,
    [Signature]                                          NVARCHAR (1333)  NULL,
    [StayInTouchSubject]                                 NVARCHAR (80)    NULL,
    [StayInTouchSignature]                               NVARCHAR (512)   NULL,
    [StayInTouchNote]                                    NVARCHAR (512)   NULL,
    [Phone]                                              NVARCHAR (40)    NULL,
    [Fax]                                                NVARCHAR (40)    NULL,
    [MobilePhone]                                        NVARCHAR (40)    NULL,
    [Alias]                                              NVARCHAR (8)     NULL,
    [CommunityNickname]                                  NVARCHAR (40)    NULL,
    [IsActive]                                           TINYINT          NULL,
    [TimeZoneSidKey]                                     NVARCHAR (40)    NULL,
    [UserRoleId]                                         NVARCHAR (18)    NULL,
    [LocaleSidKey]                                       NVARCHAR (40)    NULL,
    [ReceivesInfoEmails]                                 TINYINT          NULL,
    [ReceivesAdminInfoEmails]                            TINYINT          NULL,
    [EmailEncodingKey]                                   NVARCHAR (40)    NULL,
    [ProfileId]                                          NVARCHAR (18)    NULL,
    [UserType]                                           NVARCHAR (40)    NULL,
    [LanguageLocaleKey]                                  NVARCHAR (40)    NULL,
    [EmployeeNumber]                                     NVARCHAR (20)    NULL,
    [DelegatedApproverId]                                NVARCHAR (18)    NULL,
    [ManagerId]                                          NVARCHAR (18)    NULL,
    [LastLoginDate]                                      DATETIME2 (7)    NULL,
    [LastPasswordChangeDate]                             DATETIME2 (7)    NULL,
    [CreatedDate]                                        DATETIME2 (7)    NULL,
    [CreatedById]                                        NVARCHAR (18)    NULL,
    [LastModifiedDate]                                   DATETIME2 (7)    NULL,
    [LastModifiedById]                                   NVARCHAR (18)    NULL,
    [SystemModstamp]                                     DATETIME2 (7)    NULL,
    [OfflineTrialExpirationDate]                         DATETIME2 (7)    NULL,
    [OfflinePdaTrialExpirationDate]                      DATETIME2 (7)    NULL,
    [UserPermissionsMarketingUser]                       TINYINT          NULL,
    [UserPermissionsOfflineUser]                         TINYINT          NULL,
    [UserPermissionsAvantgoUser]                         TINYINT          NULL,
    [UserPermissionsCallCenterAutoLogin]                 TINYINT          NULL,
    [UserPermissionsMobileUser]                          TINYINT          NULL,
    [UserPermissionsSFContentUser]                       TINYINT          NULL,
    [UserPermissionsInteractionUser]                     TINYINT          NULL,
    [UserPermissionsSupportUser]                         TINYINT          NULL,
    [UserPermissionsChatterAnswersUser]                  TINYINT          NULL,
    [ForecastEnabled]                                    TINYINT          NULL,
    [UserPreferencesActivityRemindersPopup]              TINYINT          NULL,
    [UserPreferencesEventRemindersCheckboxDefault]       TINYINT          NULL,
    [UserPreferencesTaskRemindersCheckboxDefault]        TINYINT          NULL,
    [UserPreferencesReminderSoundOff]                    TINYINT          NULL,
    [UserPreferencesDisableAllFeedsEmail]                TINYINT          NULL,
    [UserPreferencesDisableFollowersEmail]               TINYINT          NULL,
    [UserPreferencesDisableProfilePostEmail]             TINYINT          NULL,
    [UserPreferencesDisableChangeCommentEmail]           TINYINT          NULL,
    [UserPreferencesDisableLaterCommentEmail]            TINYINT          NULL,
    [UserPreferencesDisProfPostCommentEmail]             TINYINT          NULL,
    [UserPreferencesContentNoEmail]                      TINYINT          NULL,
    [UserPreferencesContentEmailAsAndWhen]               TINYINT          NULL,
    [UserPreferencesApexPagesDeveloperMode]              TINYINT          NULL,
    [UserPreferencesHideCSNGetChatterMobileTask]         TINYINT          NULL,
    [UserPreferencesDisableMentionsPostEmail]            TINYINT          NULL,
    [UserPreferencesDisMentionsCommentEmail]             TINYINT          NULL,
    [UserPreferencesHideCSNDesktopTask]                  TINYINT          NULL,
    [UserPreferencesDisCommentAfterLikeEmail]            TINYINT          NULL,
    [UserPreferencesDisableLikeEmail]                    TINYINT          NULL,
    [UserPreferencesDisableMessageEmail]                 TINYINT          NULL,
    [UserPreferencesOptOutOfTouch]                       TINYINT          NULL,
    [UserPreferencesDisableBookmarkEmail]                TINYINT          NULL,
    [UserPreferencesDisableSharePostEmail]               TINYINT          NULL,
    [UserPreferencesEnableAutoSubForFeeds]               TINYINT          NULL,
    [UserPreferencesDisableFileShareNotificationsForApi] TINYINT          NULL,
    [UserPreferencesShowTitleToExternalUsers]            TINYINT          NULL,
    [UserPreferencesShowManagerToExternalUsers]          TINYINT          NULL,
    [UserPreferencesShowEmailToExternalUsers]            TINYINT          NULL,
    [UserPreferencesShowWorkPhoneToExternalUsers]        TINYINT          NULL,
    [UserPreferencesShowMobilePhoneToExternalUsers]      TINYINT          NULL,
    [UserPreferencesShowFaxToExternalUsers]              TINYINT          NULL,
    [UserPreferencesShowStreetAddressToExternalUsers]    TINYINT          NULL,
    [UserPreferencesShowCityToExternalUsers]             TINYINT          NULL,
    [UserPreferencesShowStateToExternalUsers]            TINYINT          NULL,
    [UserPreferencesShowPostalCodeToExternalUsers]       TINYINT          NULL,
    [UserPreferencesShowCountryToExternalUsers]          TINYINT          NULL,
    [UserPreferencesShowProfilePicToGuestUsers]          TINYINT          NULL,
    [UserPreferencesShowTitleToGuestUsers]               TINYINT          NULL,
    [UserPreferencesShowCityToGuestUsers]                TINYINT          NULL,
    [UserPreferencesShowStateToGuestUsers]               TINYINT          NULL,
    [UserPreferencesShowPostalCodeToGuestUsers]          TINYINT          NULL,
    [UserPreferencesShowCountryToGuestUsers]             TINYINT          NULL,
    [ContactId]                                          NVARCHAR (18)    NULL,
    [AccountId]                                          NVARCHAR (18)    NULL,
    [CallCenterId]                                       NVARCHAR (18)    NULL,
    [Extension]                                          NVARCHAR (40)    NULL,
    [PortalRole]                                         NVARCHAR (40)    NULL,
    [IsPortalEnabled]                                    TINYINT          NULL,
    [IsPortalSelfRegistered]                             TINYINT          NULL,
    [FederationIdentifier]                               NVARCHAR (512)   NULL,
    [AboutMe]                                            NVARCHAR (MAX)   NULL,
    [FullPhotoUrl]                                       NVARCHAR (1024)  NULL,
    [SmallPhotoUrl]                                      NVARCHAR (1024)  NULL,
    [DigestFrequency]                                    NVARCHAR (40)    NULL,
    [DefaultGroupNotificationFrequency]                  NVARCHAR (40)    NULL,
    [LastViewedDate]                                     DATETIME2 (7)    NULL,
    [LastReferencedDate]                                 DATETIME2 (7)    NULL,
    [ServiceMaxDispatchConsoleSettings]                  NVARCHAR (MAX)   NULL,
    [ServiceMaxSelect]                                   TINYINT          NULL,
    [ServiceMaxFaceTimeId]                               NVARCHAR (100)   NULL,
    [ServiceMaxIsSuperDispatcher]                        TINYINT          NULL,
    [BusinessUnit]                                       NVARCHAR (255)   NULL,
    [MaterialHandlingSalesPersonId]                      NVARCHAR (10)    NULL,
    [SalesArea]                                          NVARCHAR (255)   NULL,
    [SuperCenter]                                        NVARCHAR (255)   NULL,
    [CustomerPod]                                        NVARCHAR (18)    NULL,
    [CompanyLegalName]                                   NVARCHAR (100)   NULL,
    [TemporaryEmployee]                                  TINYINT          NULL,
    [UserPermissionsKnowledgeUser]                       TINYINT          NULL,
    [UserPermissionsJigsawProspectingUser]               TINYINT          NULL,
    [UserPermissionsWorkDotComUserFeature]               TINYINT          NULL,
    [UserPreferencesJigsawListUser]                      TINYINT          NULL,
    [UserPreferencesLightningExperiencePreferred]        TINYINT          NULL,
    [JigsawImportLimitOverride]                          INT              NULL,
    [BadgeText]                                          NVARCHAR (80)    NULL,
    [UserPreferencesHideChatterOnboardingSplash]         TINYINT          NULL,
    [UserPreferencesHideSecondChatterOnboardingSplash]   TINYINT          NULL,
    [UserPreferencesDisableFeedbackEmail]                TINYINT          NULL,
    [UserPreferencesDisableWorkEmail]                    TINYINT          NULL,
    [UserPreferencesHideS1BrowserUI]                     TINYINT          NULL,
    [UserPreferencesDisableEndorsementEmail]             TINYINT          NULL,
    [UserPreferencesPathAssistantCollapsed]              TINYINT          NULL,
    [UnityAgentId]                                       NVARCHAR (18)    NULL,
    [UserManagerUnityAgentId]                            NVARCHAR (18)    NULL,
    [UserPreferencesSortFeedByComment]                   TINYINT          NULL,
    [IgnoreValidations]                                  TINYINT          NULL,
    [UnityCustomerTeam]                                  NVARCHAR (MAX)   NULL,
    [UnityCustomerTeamsSelected]                         NVARCHAR (255)   NULL,
    [UnityContactExternalId]                             NVARCHAR (80)    NULL,
    [GeocodeAccuracy]                                    NVARCHAR (40)    NULL,
    [UserPreferencesCacheDiagnostics]                    TINYINT          NULL,
    [UserPreferencesShowEmailToGuestUsers]               TINYINT          NULL,
    [UserPreferencesShowManagerToGuestUsers]             TINYINT          NULL,
    [UserPreferencesShowWorkPhoneToGuestUsers]           TINYINT          NULL,
    [UserPreferencesShowMobilePhoneToGuestUsers]         TINYINT          NULL,
    [UserPreferencesShowFaxToGuestUsers]                 TINYINT          NULL,
    [UserPreferencesShowStreetAddressToGuestUsers]       TINYINT          NULL,
    [UserPreferencesPreviewLightning]                    TINYINT          NULL,
    [UserPreferencesHideEndUserOnboardingAssistantModal] TINYINT          NULL,
    [UserPreferencesHideLightningMigrationModal]         TINYINT          NULL,
    [UserPreferencesHideSfxWelcomeMat]                   TINYINT          NULL,
    [UserPreferencesHideBiggerPhotoCallout]              TINYINT          NULL,
    [MediumPhotoUrl]                                     NVARCHAR (1024)  NULL,
    [BannerPhotoUrl]                                     NVARCHAR (1024)  NULL,
    [IsProfilePhotoActive]                               TINYINT          NULL,
    [ServiceMaxServiceMax_User]                          TINYINT          NULL,
    [UserPreferencesGlobalNavBarWTShown]                 TINYINT          NULL,
    [UserPreferencesGlobalNavGridMenuWTShown]            TINYINT          NULL,
    [UserPreferencesCreateLEXAppsWTShown]                TINYINT          NULL,
    [UserPreferencesFavoritesWTShown]                    TINYINT          NULL,
    [SmallBannerPhotoUrl]                                NVARCHAR (1024)  NULL,
    [MediumBannerPhotoUrl]                               NVARCHAR (1024)  NULL,
    [LastUpdate]                                         DATETIME2 (7)    NOT NULL,
    [ImportDate]                                         DATETIME2 (7)    NOT NULL,
    [ValidFrom]                                          DATETIME2 (7)    NOT NULL,
    [ValidTo]                                            DATETIME2 (7)    NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_UserHistory_RowId]
    ON [SF].[UserHistory]([RowId] ASC);


GO
CREATE CLUSTERED INDEX [ix_UserHistory]
    ON [SF].[UserHistory]([ValidTo] ASC, [ValidFrom] ASC);

