CREATE VIEW SF.vwSVMXC__RMA_Shipment_Line__c
AS
SELECT
	[Id]											 AS [Id]
   ,[IsDeleted]										 AS [IsDeleted]
   ,ISNULL([Name], '')								 AS [Name]
   ,ISNULL([RecordTypeId], '')						 AS [RecordTypeId]
   ,[CreatedDate]									 AS [CreatedDate]
   ,ISNULL([CreatedById], '')						 AS [CreatedById]
   ,[LastModifiedDate]								 AS [LastModifiedDate]
   ,ISNULL([LastModifiedById], '')					 AS [LastModifiedById]
   ,[SystemModstamp]								 AS [SystemModstamp]
   ,ISNULL([SVMXC__RMA_Shipment_Order__c], '')		 AS [RmaShipmentOrder]
   ,[SVMXC__Actual_Quantity2__c]					 AS [ActualQuantity2]
   ,[SVMXC__Actual_Receipt_Date__c]					 AS [ActualReceiptDate]
   ,[SVMXC__Actual_Ship_Date__c]					 AS [ActualShipDate]
   ,ISNULL([SVMXC__Canceled_By__c], '')				 AS [CanceledBy]
   ,[SVMXC__Canceled_On__c]							 AS [CanceledOn]
   ,ISNULL([SVMXC__Closed_By__c], '')				 AS [ClosedBy]
   ,[SVMXC__Closed_On__c]							 AS [ClosedOn]
   ,[SVMXC__Discount_Percentage__c]					 AS [DiscountPercentage]
   ,ISNULL([SVMXC__Disposition_Instructions__c], '') AS [DispositionInstructions]
   ,ISNULL([SVMXC__Disposition__c], '')				 AS [Disposition]
   ,ISNULL([SVMXC__Expected_Condition__c], '')		 AS [ExpectedCondition]
   ,[SVMXC__Expected_Quantity2__c]					 AS [ExpectedQuantity2]
   ,[SVMXC__Expected_Receipt_Date__c]				 AS [ExpectedReceiptDate]
   ,[SVMXC__Expected_Ship_Date__c]					 AS [ExpectedShipDate]
   ,[SVMXC__Line_Price2__c]							 AS [LinePrice2]
   ,ISNULL([SVMXC__Line_Status__c], '')				 AS [LineStatus]
   ,ISNULL([SVMXC__Line_Type__c], '')				 AS [LineType]
   ,ISNULL([SVMXC__Packing_Instructions__c], '')	 AS [PackingInstructions]
   ,ISNULL([SVMXC__Parts_Request_Line__c], '')		 AS [PartsRequestLine]
   ,[SVMXC__Posted_To_Inventory__c]					 AS [PostedToInventory]
   ,ISNULL([SVMXC__Product__c], '')					 AS [Product]
   ,ISNULL([SVMXC__Returned_Condition__c], '')		 AS [ReturnedCondition]
   ,ISNULL([SVMXC__Sales_Order_Number__c], '')		 AS [SalesOrderNumber]
   ,[SVMXC__Select__c]								 AS [Select]
   ,ISNULL([SVMXC__Serial_Number__c], '')			 AS [SerialNumber]
   ,ISNULL([SVMXC__Service_Engineer__c], '')		 AS [ServiceEngineer]
   ,ISNULL([SVMXC__Service_Order_Line__c], '')		 AS [ServiceOrderLine]
   ,ISNULL([SVMXC__Ship_Location__c], '')			 AS [ShipLocation]
   ,[SVMXC__Total_Line_Price2__c]					 AS [TotalLinePrice2]
   ,[SVMXC__Use_Price_From_Pricebook__c]			 AS [UsePriceFromPricebook]
   ,ISNULL([SVMXC__Warehouse__c], '')				 AS [Warehouse]
   ,ISNULL([SVMXC__Case_Line__c], '')				 AS [CaseLine]
   ,ISNULL([SVMXC__Delivered_By__c], '')			 AS [DeliveredBy]
   ,[SVMXC__Delivered_On__c]						 AS [DeliveredOn]
   ,[SVMXC__Delivered__c]							 AS [Delivered]
   ,ISNULL([SVMXC__Delivery_Location__c], '')		 AS [DeliveryLocation]
   ,ISNULL([SVMXC__Master_Order_Line__c], '')		 AS [MasterOrderLine]
   ,ISNULL([SVMXC__Picked_By__c], '')				 AS [PickedBy]
   ,[SVMXC__Picked_On__c]							 AS [PickedOn]
   ,[SVMXC__Picked_Qty__c]							 AS [PickedQuantity]
   ,[SVMXC__Picked__c]								 AS [Picked]
   ,ISNULL([SVMXC__Received_By__c], '')				 AS [ReceivedBy]
   ,[SVMXC__Received_On__c]							 AS [ReceivedOn]
   ,[SVMXC__Received__c]							 AS [Received]
   ,ISNULL([SVMXC__Reconciliation_Action__c], '')	 AS [ReconciliationAction]
   ,ISNULL([SVMXC__Route_Card__c], '')				 AS [RouteCard]
   ,ISNULL([SVMXC__Route_Stop__c], '')				 AS [RouteStop]
   ,ISNULL([SVMXC__Serial_Number_List__c], '')		 AS [SerialNumber_List]
   ,ISNULL([SVMXC__Service_Order__c], '')			 AS [ServiceOrder]
   ,ISNULL([SVMXC__Shipped_By__c], '')				 AS [ShippedBy]
   ,[SVMXC__Shipped_On__c]							 AS [ShippedOn]
   ,[SVMXC__Shipped__c]								 AS [Shipped]
   ,[SVMXC__Work_Order_Created__c]					 AS [WorkOrderCreated]
   ,ISNULL([SVMXC__Entitlement_Status__c], '')		 AS [EntitlementStatus]
   ,[SVMXC__Fulfillment_Qty__c]						 AS [FulfillmentQuantity]
   ,[SVMXC__Service_Contract_End_Date__c]			 AS [ServiceContractEndDate]
   ,[SVMXC__Service_Contract_Start_Date__c]			 AS [ServiceContractStartDate]
   ,[SVMXC__Warranty_End_Date__c]					 AS [WarrantyEndDate]
   ,[SVMXC__Warranty_Start_Date__c]					 AS [WarrantyStartDate]
   ,ISNULL([SVMXC__Entitled_Exchange_Type__c], '')	 AS [EntitledExchangeType]
   ,[Standard_Cost__c]								 AS [StandardCost]
   ,[MH_Total_Vendor_Line_Price__c]					 AS [MaterialHandlingTotalVendorLinePrice]
   ,ISNULL([Product_Name__c], '')					 AS [ProductName]
   ,[Vendor_Price__c]								 AS [VendorPrice]
   ,[Total_Standard_Line_Price__c]					 AS [TotalStandardLinePrice]
   ,ISNULL([Part_Number__c], '')					 AS [PartNumber]
   ,ISNULL([Ship_Via_c__c], '')						 AS [ShipVia]
   ,ISNULL([Cross_Reference_Desc__c], '')			 AS [CrossReferenceDescription]
   ,ISNULL([Cross_Reference_Part__c], '')			 AS [CrossReferencePart]
   ,ISNULL([Product_Cross_Reference__c], '')		 AS [ProductCrossReference]
   ,ISNULL([Order_Type__c], '')						 AS [OrderType]
   ,ISNULL([To_Location_Supercenter__c], '')		 AS [ToLocationSupercenter]
   ,ISNULL([To_Location_Segment__c], '')			 AS [ToLocationSegment]
   ,ISNULL([SL_Vendor_ID__c], '')					 AS [SLVendorId]
   ,ISNULL([CompanyID__c], '')						 AS [CompanyId]
   ,ISNULL([Part_Order_Name__c], '')				 AS [PartOrderName]
   ,ISNULL([Product_Code_PD__c], '')				 AS [ProductCodePd]
   ,ISNULL([SVMXC__Transaction_Results__c], '')		 AS [TransactionResults]
   ,ISNULL([Description__c], '')					 AS [Description]
   ,[LastModifiedDate] AS LastUpdate
   ,GETUTCDATE() AS ImportDate
FROM [SF].[SVMXC__RMA_Shipment_Line__c];