CREATE VIEW [SF].[vwSVMXC__Site__c]
AS
SELECT
	[Id]												 AS [Id]
   ,ISNULL([OwnerId], '')								 AS [OwnerId]
   ,[IsDeleted]											 AS [IsDeleted]
   ,ISNULL([Name], '')									 AS [Name]
   ,ISNULL([RecordTypeId], '')							 AS [RecordTypeId]
   ,[CreatedDate]										 AS [CreatedDate]
   ,ISNULL([CreatedById], '')							 AS [CreatedById]
   ,[LastModifiedDate]									 AS [LastModifiedDate]
   ,ISNULL([LastModifiedById], '')						 AS [LastModifiedById]
   ,[SystemModstamp]									 AS [SystemModstamp]
   ,[LastActivityDate]									 AS [LastActivityDate]
   ,[LastViewedDate]									 AS [LastViewedDate]
   ,[LastReferencedDate]								 AS [LastReferencedDate]
   ,ISNULL([SVMXC__Account__c], '')						 AS [Account]
   ,ISNULL([SVMXC__City__c], '')						 AS [City]
   ,[SVMXC__Costed_at_value__c]							 AS [CostedAtValue]
   ,ISNULL([SVMXC__Country__c], '')						 AS [Country]
   ,ISNULL([SVMXC__Email__c], '')						 AS [Email]
   ,ISNULL([SVMXC__Inventory_Account__c], '')			 AS [InventoryAccount]
   ,[SVMXC__IsPartnerRecord__c]							 AS [IsPartnerRecord]
   ,ISNULL([SVMXC__IsPartner__c], '')					 AS [IsPartner]
   ,[SVMXC__Latitude__c]								 AS [Latitude]
   ,[SVMXC__Longitude__c]								 AS [Longitude]
   ,ISNULL([SVMXC__Partner_Account__c], '')				 AS [PartnerAccount]
   ,ISNULL([SVMXC__Partner_Contact__c], '')				 AS [PartnerContact]
   ,ISNULL([SVMXC__Service_Engineer__c], '')			 AS [ServiceEngineer]
   ,ISNULL([SVMXC__Site_Fax__c], '')					 AS [SiteFax]
   ,ISNULL([SVMXC__Site_Phone__c], '')					 AS [SitePhone]
   ,ISNULL([SVMXC__State__c], '')						 AS [State]
   ,[SVMXC__Stocking_Location__c]						 AS [StockingLocation]
   ,ISNULL([SVMXC__Street__c], '')						 AS [Street]
   ,ISNULL([SVMXC__Web_site__c], '')					 AS [Website]
   ,ISNULL([SVMXC__Zip__c], '')							 AS [Zip]
   ,[SVMXC__IsDefault_Delivery__c]						 AS [IsDefaultDelivery]
   ,[SVMXC__IsDelivery_Location__c]						 AS [IsDeliveryLocation]
   ,[SVMXC__IsGood_Stock__c]							 AS [IsGoodStock]
   ,[SVMXC__IsReceiving_Location__c]					 AS [IsReceivingLocation]
   ,[SVMXC__IsRepair_Location__c]						 AS [IsRepairLocation]
   ,[SVMXC__IsStaging_Location__c]						 AS [IsStagingLocation]
   ,ISNULL([SVMXC__Location_Type__c], '')				 AS [LocationType]
   ,ISNULL([SVMXC__Parent__c], '')						 AS [Parent]
   ,ISNULL([Mass_SL_Location_ID_ID__c], '')				 AS [MassSLLocationIdId]
   ,ISNULL([Contact__c], '')							 AS [Contact]
   ,[Location_Established__c]							 AS [LocationEstablished]
   ,[Labor_PM_Rate_DDM__c]								 AS [LaborPMRateDDM]
   ,[Labor_PM_Rate_MHE__c]								 AS [LaborPMRateMHE]
   ,ISNULL([Merger_Acquisition__c], '')					 AS [MergerAcquisition]
   ,ISNULL([Business_Unit__c], '')						 AS [BusinessUnit]
   ,ISNULL([Priority__c], '')							 AS [Priority]
   ,[Open_Work_Orders__c]								 AS [OpenWorkOrders]
   ,ISNULL([Territory_ID__c], '')						 AS [TerritoryId]
   ,[Travel_Time__c]									 AS [TravelTime]
   ,ISNULL([Organization__c], '')						 AS [Organization]
   ,ISNULL([AR__c], '')									 AS [Ar]
   ,[NTE_Threshold__c]									 AS [NteThreshold]
   ,ISNULL([Super_Center__c], '')						 AS [SuperCenter]
   ,ISNULL([Segment__c], '')							 AS [Segment]
   ,[Labor_Rate_Standard__c]							 AS [LaborRateStandard]
   ,[Labor_Rate_Premium__c]								 AS [LaborRatePremium]
   ,[Labor_Rate_Two_Man__c]								 AS [LaborRateTwoMan]
   ,ISNULL([Customer_P_O__c], '')						 AS [CustomerPO]
   ,ISNULL([Contact2__c], '')							 AS [Contact2]
   ,ISNULL([Contact3__c], '')							 AS [Contact3]
   ,ISNULL([Contact4__c], '')							 AS [Contact4]
   ,ISNULL([Site_Mobile__c], '')						 AS [SiteMobile]
   ,[Labor_Standard_DDM__c]								 AS [LaborStandardDDM]
   ,[Labor_Standard_MHE__c]								 AS [LaborStandardMHE]
   ,[Labor_2_Man_DDM__c]								 AS [Labor2ManDDM]
   ,[Labor_2_Man_MHE__c]								 AS [Labor2ManMHE]
   ,[Labor_OTDDM_DDM__c]								 AS [LaborOTDDMDDM]
   ,[Labor_OTMHE_MHE__c]								 AS [LaborOTMHEMHE]
   ,[Labor_DTDDM_DDM__c]								 AS [LaborDTDDMDDM]
   ,[Labor_DTMHE_MHE__c]								 AS [LaborDTMHEMHE]
   ,[Copy_Address__c]									 AS [CopyAddress]
   ,ISNULL([Billing_City_c__c], '')						 AS [BillingCity]
   ,ISNULL([Billing_State_Province_c__c], '')			 AS [BillingStateProvince]
   ,ISNULL([Billing_Zip_Postal_Code__c], '')			 AS [BillingZipPostalCode]
   ,ISNULL([Billing_Street__c], '')						 AS [BillingStreet]
   ,ISNULL([Call_Type__c], '')							 AS [CallType]
   ,[Account_Credit_Hold__c]							 AS [AccountCreditHold]
   ,[TEST_DATA_DO_NOT_USE__c]							 AS [TESTDATADONOTUSE]
   ,ISNULL([Chain__c], '')								 AS [Chain]
   ,ISNULL([Location_Salesperson_c__c], '')				 AS [LocationSalesPerson]
   ,ISNULL([Company__c], '')							 AS [Company]
   ,ISNULL([Salesperson_lc__c], '')						 AS [Salesperson]
   ,[Download_To_Mobile__c]								 AS [DownloadToMobile]
   ,ISNULL([Site_Contact__c], '')						 AS [SiteContact]
   ,ISNULL([Salespersons__c], '')						 AS [SalesPersons]
   ,ISNULL([Doc_Number_Loc__c], '')						 AS [DocumentNumberLoc]
   ,ISNULL([Salesperson_2nd_Loc__c], '')				 AS [Salesperson2ndLoc]
   ,[PM_Frequency_Meter__c]								 AS [PmFrequencyMeter]
   ,ISNULL([PM_Frequency_Time__c], '')					 AS [PmFrequencyTime]
   ,[Asset_Mgmt_Billing_Date__c]						 AS [AssetManagementBillingDate]
   ,[Asset_Mgmt_Fees__c]								 AS [AssetManagementFees]
   ,ISNULL([Static_Doc_Number__c], '')					 AS [StaticDocumentNumber]
   ,[Invoice_Doc_Date__c]								 AS [InvoiceDocumentDate]
   ,[Retainage__c]										 AS [Retainage]
   ,[Invoice_Due_Date__c]								 AS [InvoiceDueDate]
   ,[Requires_Dept_Rec__c]								 AS [RequiresDepartmentRecord]
   ,ISNULL([Draw_Date__c], '')							 AS [DrawDate]
   ,[Conga_Template__c]									 AS [CongaTemplate]
   ,ISNULL([Conga_Case__c], '')							 AS [CongaCase]
   ,ISNULL([SVMXC__Preferred_Business_Hours__c], '')	 AS [PreferredBusinessHours]
   ,[Recurring_Rental_Fees__c]							 AS [RecurringRentalFees]
   ,ISNULL([Conga_Post_to_Period__c], '')				 AS [CongaPostToPeriod]
   ,ISNULL([Conga_TFS_Invoice_QueryStringField__c], '')	 AS [CongaTFSInvoiceQueryStringField]
   ,ISNULL([Conga_TFS_Invoice_QueryStringField1__c], '') AS [CongaTFSInvoiceQueryStringField1]
   ,ISNULL([Conga_TFS_Invoice_QueryStringField2__c], '') AS [CongaTFSInvoiceQueryStringField2]
   ,ISNULL([Conga1_P2P__c], '')							 AS [Conga1P2P]
   ,ISNULL([Conga_Month__c], '')						 AS [CongaMonth]
   ,[Location_Count__c]									 AS [LocationCount]
   ,[LastModifiedDate]									 AS LastUpdate
   ,GETUTCDATE()										 AS ImportDate
FROM [SF].[SVMXC__Site__c];