
CREATE VIEW [SF].[vwSVMXC__RMA_Shipment_Order__c]
AS
SELECT
	[Id]											 AS [Id]
   ,ISNULL([OwnerId], '')							 AS [OwnerId]
   ,[IsDeleted]										 AS [IsDeleted]
   ,ISNULL([Name], '')								 AS [Name]
   ,ISNULL([RecordTypeId], '')						 AS [RecordTypeId]
   ,[CreatedDate]									 AS [CreatedDate]
   ,ISNULL([CreatedById], '')						 AS [CreatedById]
   ,[LastModifiedDate]								 AS [LastModifiedDate]
   ,ISNULL([LastModifiedById], '')					 AS [LastModifiedById]
   ,[SystemModstamp]								 AS [SystemModstamp]
   ,[LastActivityDate]								 AS [LastActivityDate]
   ,[LastViewedDate]								 AS [LastViewedDate]
   ,[LastReferencedDate]							 AS [LastReferencedDate]
   ,ISNULL([SVMXC__Bill_To__c], '')					 AS [BillTo]
   ,ISNULL([SVMXC__Billing_Type__c], '')			 AS [BillingType]
   ,ISNULL([SVMXC__Canceled_By__c], '')				 AS [CanceledBy]
   ,[SVMXC__Canceled_On__c]							 AS [CanceledOn]
   ,ISNULL([SVMXC__Case__c], '')					 AS [Case]
   ,ISNULL([SVMXC__Closed_By__c], '')				 AS [ClosedBy]
   ,[SVMXC__Closed_On__c]							 AS [ClosedOn]
   ,ISNULL([SVMXC__Company__c], '')					 AS [Company]
   ,ISNULL([SVMXC__Contact__c], '')					 AS [Contact]
   ,ISNULL([SVMXC__Delivery_Option__c], '')			 AS [DeliveryOption]
   ,ISNULL([SVMXC__Destination_City__c], '')		 AS [DestinationCity]
   ,ISNULL([SVMXC__Destination_Country__c], '')		 AS [DestinationCountry]
   ,ISNULL([SVMXC__Destination_Location__c], '')	 AS [DestinationLocation]
   ,ISNULL([SVMXC__Destination_State__c], '')		 AS [DestinationState]
   ,ISNULL([SVMXC__Destination_Street__c], '')		 AS [DestinationStreet]
   ,ISNULL([SVMXC__Destination_Zip__c], '')			 AS [DestinationZip]
   ,ISNULL([SVMXC__EndpointURL__c], '')				 AS [EndpointUrl]
   ,[SVMXC__Expected_Delivery_Date__c]				 AS [ExpectedDeliveryDate]
   ,[SVMXC__Expected_Receive_Date__c]				 AS [ExpectedReceiveDate]
   ,[SVMXC__IsPartnerRecord__c]						 AS [IsPartnerRecord]
   ,ISNULL([SVMXC__IsPartner__c], '')				 AS [IsPartner]
   ,ISNULL([SVMXC__Order_Status__c], '')			 AS [OrderStatus]
   ,ISNULL([SVMXC__Partner_Account__c], '')			 AS [PartnerAccount]
   ,ISNULL([SVMXC__Partner_Contact__c], '')			 AS [PartnerContact]
   ,ISNULL([SVMXC__Parts_Request__c], '')			 AS [PartsRequest]
   ,ISNULL([SVMXC__Priority__c], '')				 AS [Priority]
   ,ISNULL([SVMXC__RMA_Age_Bucket__c], '')			 AS [RmaAgeBucket]
   ,ISNULL([SVMXC__Receiving_Courier__c], '')		 AS [ReceivingCourier]
   ,ISNULL([SVMXC__SESSION_ID__c], '')				 AS [SessionId]
   ,ISNULL([SVMXC__Sales_Order_Number__c], '')		 AS [SalesOrderNumber]
   ,ISNULL([SVMXC__Service_Engineer__c], '')		 AS [ServiceEngineer]
   ,ISNULL([SVMXC__Service_Order__c], '')			 AS [ServiceOrder]
   ,ISNULL([SVMXC__Shipment_Age_Bucket__c], '')		 AS [ShipmentAgeBucket]
   ,ISNULL([SVMXC__Shipment_Reference__c], '')		 AS [ShipmentReference]
   ,ISNULL([SVMXC__Shipping_Courier__c], '')		 AS [ShippingCourier]
   ,ISNULL([SVMXC__Shipping_Receiving_Notes__c], '') AS [ShippingReceivingNotes]
   ,ISNULL([SVMXC__Shipping_Terms__c], '')			 AS [ShippingTerms]
   ,ISNULL([SVMXC__Source_City__c], '')				 AS [SourceCity]
   ,ISNULL([SVMXC__Source_Country__c], '')			 AS [SourceCountry]
   ,ISNULL([SVMXC__Source_Location__c], '')			 AS [SourceLocation]
   ,ISNULL([SVMXC__Source_State__c], '')			 AS [SourceState]
   ,ISNULL([SVMXC__Source_Street__c], '')			 AS [SourceStreet]
   ,ISNULL([SVMXC__Source_Zip__c], '')				 AS [SourceZip]
   ,ISNULL([SVMXC__Tracking_Number__c], '')			 AS [TrackingNumber]
   ,ISNULL([SVMXC__Warehouse__c], '')				 AS [Warehouse]
   ,[SVMXC__Total_Price2__c]						 AS [TotalPrice2]
   ,ISNULL([SVMXC__Address_Type__c], '')			 AS [AddressType]
   ,ISNULL([SVMXC__Order_Type__c], '')				 AS [OrderType]
   ,ISNULL([SVMXC__Fulfillment_Type__c], '')		 AS [FulfillmentType]
   ,ISNULL([SVMXC__Master_Order__c], '')			 AS [MasterOrder]
   ,[SVMXC__On_Hold__c]								 AS [OnHold]
   ,ISNULL([SVMXC__RMA_Type__c], '')				 AS [RmaType]
   ,ISNULL([SVMXC__Supplier__c], '')				 AS [Supplier]
   ,[SVMXC__Number_of_units_returned__c]			 AS [NumberOfUnitsReturned]
   ,ISNULL([Shipping_Provider__c], '')				 AS [ShippingProvider]
   ,ISNULL([Ship_Via__c], '')						 AS [ShipVia]
   ,ISNULL([Terms__c], '')							 AS [Terms]
   ,ISNULL([Buyer__c], '')							 AS [Buyer]
   ,ISNULL([Internal_Bill_To__c], '')				 AS [InternalBillTo]
   ,ISNULL([Purchase_Order_No__c], '')				 AS [PurchaseOrderNumber]
   ,ISNULL([Vendor__c], '')							 AS [Vendor]
   ,ISNULL([Vendor_Contact__c], '')					 AS [VendorContact]
   ,[Open_Lines__c]									 AS [OpenLines]
   ,ISNULL([Vendor_ID__c], '')						 AS [VendorId]
   ,[Total_Price__c]								 AS [TotalPrice]
   ,[MH_Total_Price__c]								 AS [MaterialHandlingTotalPrice]
   ,[Total_Vendor_Price__c]							 AS [TotalVendorPrice]
   ,[Total_Standard_Line_Price__c]					 AS [TotalStandardLinePrice]
   ,[Order_Date1__c]								 AS [OrderDate1]
   ,[Total_lines__c]								 AS [TotalLines]
   ,ISNULL([Reference_Notes__c], '')				 AS [ReferenceNotes]
   ,[Location_Stocking__c]							 AS [LocationStocking]
   ,ISNULL([Company_Legal_Name__c], '')				 AS [CompanyLegalName]
   ,ISNULL([Ship_To_Name__c], '')					 AS [ShipToName]
   ,[Change_Ship_To_Info__c]						 AS [ChangeShipToInfo]
   ,ISNULL([PO_Vendor_Phone__c], '')				 AS [PurchaseOrderVendorPhone]
   ,[Paid_with_Credit_Card__c]						 AS [PaidWithCreditCard]
   ,[Payment_Check_Date__c]							 AS [PaymentCheckDate]
   ,ISNULL([Payment_Check_Number__c], '')			 AS [PaymentCheckNumber]
   ,ISNULL([Payment_Credit_Card__c], '')			 AS [PaymentCreditCard]
   ,[Payment_Date__c]								 AS [PaymentDate]
   ,[Vendor_Invoice_Date__c]						 AS [VendorInvoiceDate]
   ,ISNULL([Vendor_Invoice_Number__c], '')			 AS [VendorInvoiceNumber]
   ,[LastModifiedDate]								 AS LastUpdate
   ,GETUTCDATE()									 AS ImportDate
FROM [SF].[SVMXC__RMA_Shipment_Order__c];