CREATE VIEW SF.vwSVMXC__Service_Order__c
AS
SELECT
	[Id]															AS [Id]
   ,ISNULL([OwnerId], '')											AS [OwnerId]
   ,[IsDeleted]														AS [IsDeleted]
   ,ISNULL([Name], '')												AS [Name]
   ,ISNULL([RecordTypeId], '')										AS [RecordTypeId]
   ,[CreatedDate]													AS [CreatedDate]
   ,ISNULL([CreatedById], '')										AS [CreatedById]
   ,[LastModifiedDate]												AS [LastModifiedDate]
   ,ISNULL([LastModifiedById], '')									AS [LastModifiedById]
   ,[SystemModstamp]												AS [SystemModstamp]
   ,[LastActivityDate]												AS [LastActivityDate]
   ,[LastViewedDate]												AS [LastViewedDate]
   ,[LastReferencedDate]											AS [LastReferencedDate]
   ,ISNULL([SVMXC__Age_Bucket__c], '')								AS [ServiceMaxAgeBucket]
   ,[SVMXC__Age__c]													AS [ServiceMaxAge]
   ,ISNULL([SVMXC__Billing_Type__c], '')							AS [ServiceMaxBillingType]
   ,ISNULL([SVMXC__City__c], '')									AS [ServiceMaxCity]
   ,ISNULL([SVMXC__Company__c], '')									AS [ServiceMaxCompany]
   ,ISNULL([SVMXC__Component__c], '')								AS [ServiceMaxComponent]
   ,ISNULL([SVMXC__Configuration_After__c], '')						AS [ServiceMaxConfigurationAfter]
   ,ISNULL([SVMXC__Configuration_Before__c], '')					AS [ServiceMaxConfigurationBefore]
   ,ISNULL([SVMXC__Contact__c], '')									AS [ServiceMaxContact]
   ,ISNULL([SVMXC__Country__c], '')									AS [ServiceMaxCountry]
   ,ISNULL([SVMXC__Customer_Down_Status__c], '')					AS [ServiceMaxCustomerDownStatus]
   ,[SVMXC__Customer_Down__c]										AS [ServiceMaxCustomerDown]
   ,ISNULL([SVMXC__Dispatch_Status__c], '')							AS [ServiceMaxDispatchStatus]
   ,[SVMXC__Driving_Time__c]										AS [ServiceMaxDrivingTime]
   ,ISNULL([SVMXC__EndpointURL__c], '')								AS [ServiceMaxEndpointURL]
   ,[SVMXC__First_Queued_DateTime__c]								AS [ServiceMaxFirstQueuedDateTime]
   ,ISNULL([SVMXC__Group_Email__c], '')								AS [ServiceMaxGroupEmail]
   ,ISNULL([SVMXC__Group_Member__c], '')							AS [ServiceMaxGroupMember]
   ,ISNULL([SVMXC__IsPartner__c], '')								AS [ServiceMaxIsPartner]
   ,ISNULL([SVMXC__Last_Dispatch_Event__c], '')						AS [ServiceMaxLastDispatchEvent]
   ,ISNULL([SVMXC__Member_Email__c], '')							AS [ServiceMaxMemberEmail]
   ,[SVMXC__NoOfTimesQueued__c]										AS [ServiceMaxNoOfTimesQueued]
   ,ISNULL([SVMXC__Number_Of_Times_Queued_Bucket__c], '')			AS [ServiceMaxNumberOfTimesQueuedBucket]
   ,ISNULL([SVMXC__Number_Of_Times_Scheduled_Bucket__c], '')		AS [ServiceMaxNumberOfTimesScheduledBucket]
   ,ISNULL([SVMXC__OptiMax_Status__c], '')							AS [ServiceMaxOptiMaxStatus]
   ,ISNULL([SVMXC__Order_Status__c], '')							AS [ServiceMaxOrderStatus]
   ,ISNULL([SVMXC__Order_Type__c], '')								AS [ServiceMaxOrderType]
   ,ISNULL([SVMXC__Priority__c], '')								AS [ServiceMaxPriority]
   ,ISNULL([SVMXC__Problem_Description__c], '')						AS [ServiceMaxProblemDescription]
   ,ISNULL([SVMXC__Product__c], '')									AS [ServiceMaxProduct]
   ,ISNULL([SVMXC__SESSION_ID__c], '')								AS [ServiceMaxSessionId]
   ,[SVMXC__Scheduled_Date_Time__c]									AS [ServiceMaxScheduledDateTime]
   ,[SVMXC__Scheduled_Date__c]										AS [ServiceMaxScheduledDate]
   ,[SVMXC__TimeBetweenScheduleAndClose__c]							AS [ServiceMaxTimeBetweenScheduleAndClose]
   ,[SVMXC__TimeToAssign__c]										AS [ServiceMaxTimeToAssign]
   ,[SVMXC__TimeToQueue__c]											AS [ServiceMaxTimeToQueue]
   ,[SVMXC__TimeToSchedule__c]										AS [ServiceMaxTimeToSchedule]
   ,ISNULL([SVMXC__Time_Between_Assign_And_Schedule_Bucket__c], '') AS [ServiceMaxTimeBetweenAssignAndScheduleBucket]
   ,ISNULL([SVMXC__Time_Between_Queue_And_Assign_Bucket__c], '')	AS [ServiceMaxTimeBetweenQueueAndAssignBucket]
   ,ISNULL([SVMXC__Time_Between_Schedule_And_Close_Bucket__c], '')	AS [ServiceMaxTimeBetweenScheduleAndCloseBucket]
   ,ISNULL([SVMXC__Time_to_Assign_Bucket__c], '')					AS [ServiceMaxTimetoAssignBucket]
   ,ISNULL([SVMXC__Time_to_Queue_Bucket__c], '')					AS [ServiceMaxTimetoQueueBucket]
   ,ISNULL([SVMXC__Time_to_Schedule_Bucket__c], '')					AS [ServiceMaxTimetoScheduleBucket]
   ,ISNULL([SVMXC__Turnaround_Time__c], '')							AS [ServiceMaxTurnaroundTime]
   ,ISNULL([SVMXC__Work_Performed__c], '')							AS [ServiceMaxWorkPerformed]
   ,ISNULL([SVMXC__Zip__c], '')										AS [ServiceMaxZip]
   ,[SVMXC__Total_Billable_Amount__c]								AS [ServiceMaxTotalBillableAmount]
   ,[SVMXC__Total_Work_Order_Cost__c]								AS [ServiceMaxTotalWorkOrderCost]
   ,ISNULL([Location__c], '')										AS [Location]
   ,[SVMXC__Invoice_Created__c]										AS [ServiceMaxInvoiceCreated]
   ,ISNULL([SVMXC__Invoice_Number__c], '')							AS [ServiceMaxInvoiceNumber]
   ,[SVMXC__Is_Entitlement_Performed__c]							AS [ServiceMaxIsEntitlementPerformed]
   ,[SVMXC__Is_Service_Covered__c]									AS [ServiceMaxIsServiceCovered]
   ,[SVMXC__Perform_Auto_Entitlement__c]							AS [ServiceMaxPerformAutoEntitlement]
   ,ISNULL([SVMXC__Site__c], '')									AS [ServiceMaxSite]
   ,ISNULL([SVMXC__QTL_Status__c], '')								AS [ServiceMaxQtlStatus]
   ,ISNULL([SVMXC__Qualified_Technicians__c], '')					AS [ServiceMaxQualifiedTechnicians]
   ,ISNULL([SVMXC__Skill_Set__c], '')								AS [ServiceMaxSkillSet]
   ,ISNULL([SVMXC__Service_Zone_ID__c], '')							AS [ServiceMaxServiceZoneId]
   ,[Estimated_Work_Detail_Total__c]								AS [EstimatedWorkDetailTotal]
   ,ISNULL([Work_Order_Denied_Reason__c], '')						AS [WorkOrderDeniedReason]
   ,[Additional_Service_Recommended__c]								AS [AdditionalServiceRecommended]
   ,[Emergency_Service__c]											AS [EmergencyService]
   ,ISNULL([Serial_Number__c], '')									AS [SerialNumber]
   ,ISNULL([Asset_Tag__c], '')										AS [AssetTag]
   ,ISNULL([Customer_P_O__c], '')									AS [CustomerPurchaseOrder]
   ,[Invoice_Total__c]												AS [InvoiceTotal]
   ,ISNULL([Recommended_Service__c], '')							AS [RecommendedService]
   ,ISNULL([Make__c], '')											AS [Make]
   ,[TFS_Service_Date__c]											AS [TfsServiceDate]
   ,[NTEThreshold__c]												AS [NteThreshold]
   ,ISNULL([MHE_Fault_Codes_Tier_I__c], '')							AS [MheFaultCodesTierI]
   ,ISNULL([MHE_Fault_Codes_Tier_II__c], '')						AS [MheFaultCodesTierII]
   ,ISNULL([Model1__c], '')											AS [Model1]
   ,ISNULL([Broad__c], '')											AS [Broad]
   ,ISNULL([Group__c], '')											AS [Group]
   ,ISNULL([Type__c], '')											AS [Type]
   ,ISNULL([Broad_Location__c], '')									AS [BroadLocation]
   ,ISNULL([Broad_Reportable__c], '')								AS [BroadReportable]
   ,ISNULL([Group_Location__c], '')									AS [GroupLocation]
   ,ISNULL([Type_Location__c], '')									AS [TypeLocation]
   ,ISNULL([Group_Reportable__c], '')								AS [GroupReportable]
   ,ISNULL([Type_Reportable__c], '')								AS [TypeReportable]
   ,[Technician_Arrived__c]											AS [TechnicianArrived]
   ,ISNULL([Dispatch_Status1__c], '')								AS [DispatchStatus1]
   ,[Work_Order_Rollup__c]											AS [WorkOrderRollup]
   ,[Labor_Rate_Standard__c]										AS [LaborRateStandard]
   ,[Meter_Reading__c]												AS [MeterReading]
   ,ISNULL([Business_Unit__c], '')									AS [BusinessUnit]
   ,[Work_Detail_Count__c]											AS [WorkDetailCount]
   ,[Total_Sales_Tax__c]											AS [TotalSalesTax]
   ,ISNULL([Field_Office__c], '')									AS [FieldOffice]
   ,[Vendor_Work_Details_Open__c]									AS [VendorWorkDetailsOpen]
   ,[Total_Cost__c]													AS [TotalCost]
   ,[Estimated_Work_Total__c]										AS [EstimatedWorkTotal]
   ,[TFS_Invoice_Date__c]											AS [TfsInvoiceDate]
   ,[TFS_Date_Entered__c]											AS [TfsDateEntered]
   ,ISNULL([TFS_Vendor_Invoice__c], '')								AS [TfsVendorInvoice]
   ,ISNULL([TFS_Vendor_Work_Order__c], '')							AS [TfsVendorWorkOrder]
   ,[Work_Order_Total__c]											AS [WorkOrderTotal]
   ,[Sales_Tax_Total__c]											AS [SalesTaxTotal]
   ,ISNULL([Super_Center__c], '')									AS [SuperCenter]
   ,[Labor_PM_Rate_DDM__c]											AS [LaborPMRateDdm]
   ,[Labor_PM_Rate_MHE__c]											AS [LaborPMRateMhe]
   ,[Labor_Standard_DDM__c]											AS [LaborStandardDdm]
   ,[Labor_Standard_MHE__c]											AS [LaborStandardMhe]
   ,[Labor_2_Man_DDM__c]											AS [Labor2ManDdm]
   ,[Labor_2_Man_MHE__c]											AS [Labor2ManMhe]
   ,[Labor_OTDDM_DDM__c]											AS [LaborOtddmDdm]
   ,[Labor_OTMHE_MHE__c]											AS [LaborOtmheMhe]
   ,[Labor_DTDDM_DDM__c]											AS [LaborDdmDdm]
   ,[Labor_DTMHE_MHE__c]											AS [LaborDTMheMhe]
   ,ISNULL([Job_Info_c__c], '')										AS [JobInformation]
   ,ISNULL([Dock_Fault__c], '')										AS [DockFault]
   ,ISNULL([Door_Fault_I__c], '')									AS [DoorFaultI]
   ,ISNULL([Group_Miner__c], '')									AS [GroupMiner]
   ,[Fault_Validation_c__c]											AS [FaultValidation]
   ,ISNULL([Vendor_Name_c__c], '')									AS [VendorName]
   ,[Meter_Reading_Required__c]										AS [MeterReadingRequired]
   ,[Draw_Date_c__c]												AS [DrawDate]
   ,[Contract_Install_c__c]											AS [ContractInstall]
   ,ISNULL([Door_Fault_II__c], '')									AS [DoorFaultII]
   ,ISNULL([Spec_Waste_Fault__c], '')								AS [SpecWasteFault]
   ,ISNULL([Dock_Solution_I__c], '')								AS [DockSolutionI]
   ,[Invoice_Denied_c__c]											AS [InvoiceDenied]
   ,ISNULL([MHE_Resolution_Code__c], '')							AS [MheResolutionCode]
   ,ISNULL([Dock_Solution_II__c], '')								AS [DockSolutionII]
   ,ISNULL([Door_Solution_I__c], '')								AS [DoorSolutionI]
   ,ISNULL([Door_Solution_II__c], '')								AS [DoorSolutionII]
   ,ISNULL([Door_Solution_III__c], '')								AS [DoorSolutionIII]
   ,ISNULL([Spec_Wast_Solution__c], '')								AS [SpecWastSolution]
   ,ISNULL([Email_Service_Report__c], '')							AS [EmailServiceReport]
   ,[Send_Service_Report_to_Customer__c]							AS [SendServiceReporttoCustomer]
   ,[Estimate_Needed_c__c]											AS [EstimateNeeded]
   ,[Contract_Amount__c]											AS [ContractAmount]
   ,[Change_Order_Amt__c]											AS [ChangeOrderAmt]
   ,ISNULL([Notes__c], '')											AS [Notes]
   ,[Retainage_c__c]												AS [Retainage]
   ,[Retainage_Percentage_c__c]										AS [RetainagePercentage]
   ,ISNULL([Parent_Work_Order_c__c], '')							AS [ParentWorkOrder]
   ,[Work_Order_Margin__c]											AS [WorkOrderMargin]
   ,[Change_Order_Amt_2__c]											AS [ChangeOrderAmt2]
   ,[Change_Order_Amt_3__c]											AS [ChangeOrderAmt3]
   ,[Change_Order_Amt_4__c]											AS [ChangeOrderAmt4]
   ,ISNULL([Signature_Name__c], '')									AS [SignatureName]
   ,ISNULL([Company_code__c], '')									AS [Companycode]
   ,[Parts_Needed_c__c]												AS [PartsNeededc]
   ,ISNULL([Estimate_Parts_Notes_c__c], '')							AS [EstimatePartsNotes]
   ,[Work_Order_Margin_c2__c]										AS [WorkOrderMarginc2]
   ,[Contract_Total_c__c]											AS [ContractTotal]
   ,[Work_Finished_c__c]											AS [WorkFinished]
   ,ISNULL([Installed_Product_Name_c__c], '')						AS [InstalledProductName]
   ,ISNULL([Broad_IP_wo__c], '')									AS [BroadIPwo]
   ,ISNULL([Group_IP_wo__c], '')									AS [GroupIPwo]
   ,ISNULL([Service_Date_I__c], '')									AS [ServiceDateI]
   ,ISNULL([Last_Work_Performed__c], '')							AS [LastWorkPerformed]
   ,ISNULL([Job_History__c], '')									AS [JobHistory]
   ,[SVMXC__Finished_Onsite_Date_Time__c]							AS [ServiceMaxFinishedOnsiteDateTime]
   ,ISNULL([SVMXC__Scheduling_Change_Token__c], '')					AS [ServiceMaxSchedulingChangeToken]
   ,ISNULL([Salesperson_c__c], '')									AS [Salesperson]
   ,ISNULL([Invoice_Date_I__c], '')									AS [InvoiceDateI]
   ,[Locked__c]														AS [Locked]
   ,[Last_Meter_Reading__c]											AS [LastMeterReading]
   ,ISNULL([Customer_Queue__c], '')									AS [CustomerQueue]
   ,ISNULL([Salesperson_wo__c], '')									AS [SalespersonWorkOrder]
   ,[Parts_Cost__c]													AS [PartsCost]
   ,[Total_Work_Order_w_Tax__c]										AS [TotalWorkOrderwTax]
   ,[Rejected_Invoice_Amount__c]									AS [RejectedInvoiceAmount]
   ,[Labor_Cost__c]													AS [LaborCost]
   ,ISNULL([Work_Performed_tfs__c], '')								AS [WorkPerformedTfs]
   ,ISNULL([Invoice_Post_to_Period__c], '')							AS [InvoicePostToPeriod]
   ,ISNULL([Doc_Number__c], '')										AS [DocumentNumber]
   ,ISNULL([Invoice_Document__c], '')								AS [InvoiceDocument]
   ,ISNULL([Make_IP__c], '')										AS [MakeIP]
   ,ISNULL([Model_IP__c], '')										AS [ModelIP]
   ,[Total_Invoiced__c]												AS [TotalInvoiced]
   ,[Vendor_Invoice_Total__c]										AS [VendorInvoiceTotal]
   ,[SL_Invoice_Date__c]											AS [SLInvoiceDate]
   ,ISNULL([Salesperson_2nd_WO__c], '')								AS [Salesperson2ndWorkOrder]
   ,ISNULL([Location_Name__c], '')									AS [LocationName]
   ,[Tax_Exempt_Project__c]											AS [TaxExemptProject]
   ,ISNULL([Equip_Sales_Info__c], '')								AS [EquipSalesInfo]
   ,[Last_Meter_Reading_Date__c]									AS [LastMeterReadingDate]
   ,[Last_PM_Date__c]												AS [LastPmDate]
   ,[Last_PM_Meter_Reading__c]										AS [LastPmMeterReading]
   ,[PM_Date_Diff__c]												AS [PmDateDiff]
   ,[PM_Meter_Diff__c]												AS [PmMeterDiff]
   ,ISNULL([Certificate__c], '')									AS [Certificate]
   ,[Rejection_Override__c]											AS [RejectionOverride]
   ,[Permanent_Rejection__c]										AS [PermanentRejection]
   ,[IP_Warranty_End_Date__c]										AS [IPWarrantyEndDate]
   ,[Days_Left_Under_Warranty__c]									AS [DaysLeftUnderWarranty]
   ,[Meter_Left_Under_Warranty__c]									AS [MeterLeftUnderWarranty]
   ,[Approval_Requested__c]											AS [ApprovalRequested]
   ,ISNULL([Approval_Status__c], '')								AS [ApprovalStatus]
   ,ISNULL([Assigned_Approver__c], '')								AS [AssignedApprover]
   ,ISNULL([Static_Doc_Number__c], '')								AS [StaticDocNumber]
   ,ISNULL([Invoice_Received_Date_I__c], '')						AS [InvoiceReceivedDateI]
   ,Invoice_Received_Date__c										AS [InvoiceReceivedDate]
   ,[Asset_Mgmt_Fees__c]											AS [AssetMgmtFees]
   ,[TFS_AMF_WO__c]													AS [TfsAmfWorkOrder]
   ,[Tax_Cost__c]													AS [TaxCost]
   ,ISNULL([IP_Department__c], '')									AS [IPDepartment]
   ,ISNULL([Conga_Vendor_Name__c], '')								AS [CongaVendorName]
   ,ISNULL([Draw_Date_New__c], '')									AS [DrawDateNew]
   ,[Doc_Number_Date__c]											AS [DocNumberDate]
   ,[Service_Report_Finalized__c]									AS [ServiceReportFinalized]
   ,[Service_Report_Received__c]									AS [ServiceReportReceived]
   ,ISNULL([SuperCenterName__c], '')								AS [SuperCenterName]
   ,ISNULL([Super_Center2__c], '')									AS [SuperCenter2]
   ,[First_Time_Dispatched__c]										AS [FirstTimeDispatched]
   ,[Response_Time__c]												AS [ResponseTime]
   ,[Date_Time_Invoice_Completed__c]								AS [DateTimeInvoiceCompleted]
   ,[Date_Time_Job_Work_Complete__c]								AS [DateTimeJobWorkComplete]
   ,[Time_to_Job_Work_Complete__c]									AS [TimeToJobWorkComplete]
   ,[Time_to_Invoice_Completed__c]									AS [TimeToInvoiceCompleted]
   ,ISNULL([Segment__c], '')										AS [Segment]
   ,[Canadian_QST_PST__c]											AS [CanadianQSTPST]
   ,[Canadian_GST_HST_TPS__c]										AS [CanadianGSTHSTTPS]
   ,[Canadian_QST_PST_TVQ__c]										AS [CanadianQSTPSTTVQ]
   ,ISNULL([Invoiced_Lines__c], '')									AS [InvoicedLines]
   ,[Time_to_Book_Revenue__c]										AS [TimetoBookRevenue]
   ,[Edit_Quoted_Values__c]											AS [EditQuotedValues]
   ,ISNULL([Non_Billable_Item_Approval_Status__c], '')				AS [NonBillableItemApprovalStatus]
   ,[Quoted_Total__c]												AS [QuotedTotal]
   ,ISNULL([Work_Order_Type__c], '')								AS [WorkOrderType]
   ,[Non_Billable_Line_Items__c]									AS [NonBillableLineItems]
   ,[Not_Billable_from_iPad__c]										AS [NotBillablefromiPad]
   ,ISNULL([Service_Notes__c], '')									AS [ServiceNotes]
   ,[SVMXC__SM_LJS_Minimum_Schedule_Duration__c]					AS [ServiceMaxSMLJSMinimumScheduleDuration]
   ,LastModifiedDate												AS LastUpdate
   ,GETUTCDATE()													AS ImportDate
FROM [SF].[SVMXC__Service_Order__c];