CREATE VIEW SF.vwUser
AS
SELECT
	[Id]													   AS [Id]
   ,ISNULL([Username], '')									   AS [Username]
   ,ISNULL([LastName], '')									   AS [LastName]
   ,ISNULL([FirstName], '')									   AS [FirstName]
   ,ISNULL([Name], '')										   AS [Name]
   ,ISNULL([CompanyName], '')								   AS [CompanyName]
   ,ISNULL([Division], '')									   AS [Division]
   ,ISNULL([Department], '')								   AS [Department]
   ,ISNULL([Title], '')										   AS [Title]
   ,ISNULL([Street], '')									   AS [Street]
   ,ISNULL([City], '')										   AS [City]
   ,ISNULL([State], '')										   AS [State]
   ,ISNULL([PostalCode], '')								   AS [PostalCode]
   ,ISNULL([Country], '')									   AS [Country]
   ,ISNULL([StateCode], '')									   AS [StateCode]
   ,ISNULL([CountryCode], '')								   AS [CountryCode]
   ,[Latitude]												   AS [Latitude]
   ,[Longitude]												   AS [Longitude]
   ,ISNULL([Email], '')										   AS [Email]
   ,[EmailPreferencesAutoBcc]								   AS [EmailPreferencesAutoBcc]
   ,[EmailPreferencesAutoBccStayInTouch]					   AS [EmailPreferencesAutoBccStayInTouch]
   ,[EmailPreferencesStayInTouchReminder]					   AS [EmailPreferencesStayInTouchReminder]
   ,ISNULL([SenderEmail], '')								   AS [SenderEmail]
   ,ISNULL([SenderName], '')								   AS [SenderName]
   ,ISNULL([Signature], '')									   AS [Signature]
   ,ISNULL([StayInTouchSubject], '')						   AS [StayInTouchSubject]
   ,ISNULL([StayInTouchSignature], '')						   AS [StayInTouchSignature]
   ,ISNULL([StayInTouchNote], '')							   AS [StayInTouchNote]
   ,ISNULL([Phone], '')										   AS [Phone]
   ,ISNULL([Fax], '')										   AS [Fax]
   ,ISNULL([MobilePhone], '')								   AS [MobilePhone]
   ,ISNULL([Alias], '')										   AS [Alias]
   ,ISNULL([CommunityNickname], '')							   AS [CommunityNickname]
   ,[IsActive]												   AS [IsActive]
   ,ISNULL([TimeZoneSidKey], '')							   AS [TimeZoneSidKey]
   ,ISNULL([UserRoleId], '')								   AS [UserRoleId]
   ,ISNULL([LocaleSidKey], '')								   AS [LocaleSidKey]
   ,[ReceivesInfoEmails]									   AS [ReceivesInfoEmails]
   ,[ReceivesAdminInfoEmails]								   AS [ReceivesAdminInfoEmails]
   ,ISNULL([EmailEncodingKey], '')							   AS [EmailEncodingKey]
   ,ISNULL([ProfileId], '')									   AS [ProfileId]
   ,ISNULL([UserType], '')									   AS [UserType]
   ,ISNULL([LanguageLocaleKey], '')							   AS [LanguageLocaleKey]
   ,ISNULL([EmployeeNumber], '')							   AS [EmployeeNumber]
   ,ISNULL([DelegatedApproverId], '')						   AS [DelegatedApproverId]
   ,ISNULL([ManagerId], '')									   AS [ManagerId]
   ,[LastLoginDate]											   AS [LastLoginDate]
   ,[LastPasswordChangeDate]								   AS [LastPasswordChangeDate]
   ,[CreatedDate]											   AS [CreatedDate]
   ,ISNULL([CreatedById], '')								   AS [CreatedById]
   ,[LastModifiedDate]										   AS [LastModifiedDate]
   ,ISNULL([LastModifiedById], '')							   AS [LastModifiedById]
   ,[SystemModstamp]										   AS [SystemModstamp]
   ,[OfflineTrialExpirationDate]							   AS [OfflineTrialExpirationDate]
   ,[OfflinePdaTrialExpirationDate]							   AS [OfflinePdaTrialExpirationDate]
   ,[UserPermissionsMarketingUser]							   AS [UserPermissionsMarketingUser]
   ,[UserPermissionsOfflineUser]							   AS [UserPermissionsOfflineUser]
   ,[UserPermissionsAvantgoUser]							   AS [UserPermissionsAvantgoUser]
   ,[UserPermissionsCallCenterAutoLogin]					   AS [UserPermissionsCallCenterAutoLogin]
   ,[UserPermissionsMobileUser]								   AS [UserPermissionsMobileUser]
   ,[UserPermissionsSFContentUser]							   AS [UserPermissionsSFContentUser]
   ,[UserPermissionsInteractionUser]						   AS [UserPermissionsInteractionUser]
   ,[UserPermissionsSupportUser]							   AS [UserPermissionsSupportUser]
   ,[UserPermissionsChatterAnswersUser]						   AS [UserPermissionsChatterAnswersUser]
   ,[ForecastEnabled]										   AS [ForecastEnabled]
   ,[UserPreferencesActivityRemindersPopup]					   AS [UserPreferencesActivityRemindersPopup]
   ,[UserPreferencesEventRemindersCheckboxDefault]			   AS [UserPreferencesEventRemindersCheckboxDefault]
   ,[UserPreferencesTaskRemindersCheckboxDefault]			   AS [UserPreferencesTaskRemindersCheckboxDefault]
   ,[UserPreferencesReminderSoundOff]						   AS [UserPreferencesReminderSoundOff]
   ,[UserPreferencesDisableAllFeedsEmail]					   AS [UserPreferencesDisableAllFeedsEmail]
   ,[UserPreferencesDisableFollowersEmail]					   AS [UserPreferencesDisableFollowersEmail]
   ,[UserPreferencesDisableProfilePostEmail]				   AS [UserPreferencesDisableProfilePostEmail]
   ,[UserPreferencesDisableChangeCommentEmail]				   AS [UserPreferencesDisableChangeCommentEmail]
   ,[UserPreferencesDisableLaterCommentEmail]				   AS [UserPreferencesDisableLaterCommentEmail]
   ,[UserPreferencesDisProfPostCommentEmail]				   AS [UserPreferencesDisProfPostCommentEmail]
   ,[UserPreferencesContentNoEmail]							   AS [UserPreferencesContentNoEmail]
   ,[UserPreferencesContentEmailAsAndWhen]					   AS [UserPreferencesContentEmailAsAndWhen]
   ,[UserPreferencesApexPagesDeveloperMode]					   AS [UserPreferencesApexPagesDeveloperMode]
   ,[UserPreferencesHideCSNGetChatterMobileTask]			   AS [UserPreferencesHideCSNGetChatterMobileTask]
   ,[UserPreferencesDisableMentionsPostEmail]				   AS [UserPreferencesDisableMentionsPostEmail]
   ,[UserPreferencesDisMentionsCommentEmail]				   AS [UserPreferencesDisMentionsCommentEmail]
   ,[UserPreferencesHideCSNDesktopTask]						   AS [UserPreferencesHideCSNDesktopTask]
   ,[UserPreferencesDisCommentAfterLikeEmail]				   AS [UserPreferencesDisCommentAfterLikeEmail]
   ,[UserPreferencesDisableLikeEmail]						   AS [UserPreferencesDisableLikeEmail]
   ,[UserPreferencesDisableMessageEmail]					   AS [UserPreferencesDisableMessageEmail]
   ,[UserPreferencesOptOutOfTouch]							   AS [UserPreferencesOptOutOfTouch]
   ,[UserPreferencesDisableBookmarkEmail]					   AS [UserPreferencesDisableBookmarkEmail]
   ,[UserPreferencesDisableSharePostEmail]					   AS [UserPreferencesDisableSharePostEmail]
   ,[UserPreferencesEnableAutoSubForFeeds]					   AS [UserPreferencesEnableAutoSubForFeeds]
   ,[UserPreferencesDisableFileShareNotificationsForApi]	   AS [UserPreferencesDisableFileShareNotificationsForApi]
   ,[UserPreferencesShowTitleToExternalUsers]				   AS [UserPreferencesShowTitleToExternalUsers]
   ,[UserPreferencesShowManagerToExternalUsers]				   AS [UserPreferencesShowManagerToExternalUsers]
   ,[UserPreferencesShowEmailToExternalUsers]				   AS [UserPreferencesShowEmailToExternalUsers]
   ,[UserPreferencesShowWorkPhoneToExternalUsers]			   AS [UserPreferencesShowWorkPhoneToExternalUsers]
   ,[UserPreferencesShowMobilePhoneToExternalUsers]			   AS [UserPreferencesShowMobilePhoneToExternalUsers]
   ,[UserPreferencesShowFaxToExternalUsers]					   AS [UserPreferencesShowFaxToExternalUsers]
   ,[UserPreferencesShowStreetAddressToExternalUsers]		   AS [UserPreferencesShowStreetAddressToExternalUsers]
   ,[UserPreferencesShowCityToExternalUsers]				   AS [UserPreferencesShowCityToExternalUsers]
   ,[UserPreferencesShowStateToExternalUsers]				   AS [UserPreferencesShowStateToExternalUsers]
   ,[UserPreferencesShowPostalCodeToExternalUsers]			   AS [UserPreferencesShowPostalCodeToExternalUsers]
   ,[UserPreferencesShowCountryToExternalUsers]				   AS [UserPreferencesShowCountryToExternalUsers]
   ,[UserPreferencesShowProfilePicToGuestUsers]				   AS [UserPreferencesShowProfilePicToGuestUsers]
   ,[UserPreferencesShowTitleToGuestUsers]					   AS [UserPreferencesShowTitleToGuestUsers]
   ,[UserPreferencesShowCityToGuestUsers]					   AS [UserPreferencesShowCityToGuestUsers]
   ,[UserPreferencesShowStateToGuestUsers]					   AS [UserPreferencesShowStateToGuestUsers]
   ,[UserPreferencesShowPostalCodeToGuestUsers]				   AS [UserPreferencesShowPostalCodeToGuestUsers]
   ,[UserPreferencesShowCountryToGuestUsers]				   AS [UserPreferencesShowCountryToGuestUsers]
   ,ISNULL([ContactId], '')									   AS [ContactId]
   ,ISNULL([AccountId], '')									   AS [AccountId]
   ,ISNULL([CallCenterId], '')								   AS [CallCenterId]
   ,ISNULL([Extension], '')									   AS [Extension]
   ,ISNULL([PortalRole], '')								   AS [PortalRole]
   ,[IsPortalEnabled]										   AS [IsPortalEnabled]
   ,[IsPortalSelfRegistered]								   AS [IsPortalSelfRegistered]
   ,ISNULL([FederationIdentifier], '')						   AS [FederationIdentifier]
   ,ISNULL([AboutMe], '')									   AS [AboutMe]
   ,ISNULL([FullPhotoUrl], '')								   AS [FullPhotoUrl]
   ,ISNULL([SmallPhotoUrl], '')								   AS [SmallPhotoUrl]
   ,ISNULL([DigestFrequency], '')							   AS [DigestFrequency]
   ,ISNULL([DefaultGroupNotificationFrequency], '')			   AS [DefaultGroupNotificationFrequency]
   ,[LastViewedDate]										   AS [LastViewedDate]
   ,[LastReferencedDate]									   AS [LastReferencedDate]
   ,ISNULL([SVMXC__Dispatch_Console_Settings__c], '')		   AS [ServiceMaxDispatchConsoleSettings]
   ,[SVMXC__Select__c]										   AS [ServiceMaxSelect]
   ,ISNULL([SVMXC__FaceTime_ID__c], '')						   AS [ServiceMaxFaceTimeId]
   ,[SVMXC__Is_Super_Dispatcher__c]							   AS [ServiceMaxIsSuperDispatcher]
   ,ISNULL([Business_Unit__c], '')							   AS [BusinessUnit]
   ,ISNULL([MH_SlsPerson_ID__c], '')						   AS [MaterialHandlingSalesPersonId]
   ,ISNULL([Sales_Area__c], '')								   AS [SalesArea]
   ,ISNULL([Super_Center__c], '')							   AS [SuperCenter]
   ,ISNULL([customer_pod__c], '')							   AS [customerPod]
   ,ISNULL([Company_Legal_Name__c], '')						   AS [CompanyLegalName]
   ,[Temporary_Employee__c]									   AS [TemporaryEmployee]
   ,[UserPermissionsKnowledgeUser]							   AS [UserPermissionsKnowledgeUser]
   ,[UserPermissionsJigsawProspectingUser]					   AS [UserPermissionsJigsawProspectingUser]
   ,[UserPermissionsWorkDotComUserFeature]					   AS [UserPermissionsWorkDotComUserFeature]
   ,[UserPreferencesJigsawListUser]							   AS [UserPreferencesJigsawListUser]
   ,[UserPreferencesLightningExperiencePreferred]			   AS [UserPreferencesLightningExperiencePreferred]
   ,[JigsawImportLimitOverride]								   AS [JigsawImportLimitOverride]
   ,ISNULL([BadgeText], '')									   AS [BadgeText]
   ,[UserPreferencesHideChatterOnboardingSplash]			   AS [UserPreferencesHideChatterOnboardingSplash]
   ,[UserPreferencesHideSecondChatterOnboardingSplash]		   AS [UserPreferencesHideSecondChatterOnboardingSplash]
   ,[UserPreferencesDisableFeedbackEmail]					   AS [UserPreferencesDisableFeedbackEmail]
   ,[UserPreferencesDisableWorkEmail]						   AS [UserPreferencesDisableWorkEmail]
   ,[UserPreferencesHideS1BrowserUI]						   AS [UserPreferencesHideS1BrowserUI]
   ,[UserPreferencesDisableEndorsementEmail]				   AS [UserPreferencesDisableEndorsementEmail]
   ,[UserPreferencesPathAssistantCollapsed]					   AS [UserPreferencesPathAssistantCollapsed]
   ,ISNULL([UNITY_Agent_ID__c], '')							   AS [UnityAgentId]
   ,ISNULL([User_Manager_UNITY_Agent_ID__c], '')			   AS [UserManagerUnityAgentId]
   ,[UserPreferencesSortFeedByComment]						   AS [UserPreferencesSortFeedByComment]
   ,[Ignore_Validations__c]									   AS [IgnoreValidations]
   ,ISNULL([Unity_Customer_Team__c], '')					   AS [UnityCustomerTeam]
   ,ISNULL([UNITY_Customer_Teams_Selected__c], '')			   AS [UnityCustomerTeamsSelected]
   ,ISNULL([Contact_Contact_UNITY_Contact_External_Id__c], '') AS [UnityContactExternalId]
   ,ISNULL([GeocodeAccuracy], '')							   AS [GeocodeAccuracy]
   ,[UserPreferencesCacheDiagnostics]						   AS [UserPreferencesCacheDiagnostics]
   ,[UserPreferencesShowEmailToGuestUsers]					   AS [UserPreferencesShowEmailToGuestUsers]
   ,[UserPreferencesShowManagerToGuestUsers]				   AS [UserPreferencesShowManagerToGuestUsers]
   ,[UserPreferencesShowWorkPhoneToGuestUsers]				   AS [UserPreferencesShowWorkPhoneToGuestUsers]
   ,[UserPreferencesShowMobilePhoneToGuestUsers]			   AS [UserPreferencesShowMobilePhoneToGuestUsers]
   ,[UserPreferencesShowFaxToGuestUsers]					   AS [UserPreferencesShowFaxToGuestUsers]
   ,[UserPreferencesShowStreetAddressToGuestUsers]			   AS [UserPreferencesShowStreetAddressToGuestUsers]
   ,[UserPreferencesPreviewLightning]						   AS [UserPreferencesPreviewLightning]
   ,[UserPreferencesHideEndUserOnboardingAssistantModal]	   AS [UserPreferencesHideEndUserOnboardingAssistantModal]
   ,[UserPreferencesHideLightningMigrationModal]			   AS [UserPreferencesHideLightningMigrationModal]
   ,[UserPreferencesHideSfxWelcomeMat]						   AS [UserPreferencesHideSfxWelcomeMat]
   ,[UserPreferencesHideBiggerPhotoCallout]					   AS [UserPreferencesHideBiggerPhotoCallout]
   ,ISNULL([MediumPhotoUrl], '')							   AS [MediumPhotoUrl]
   ,ISNULL([BannerPhotoUrl], '')							   AS [BannerPhotoUrl]
   ,[IsProfilePhotoActive]									   AS [IsProfilePhotoActive]
   ,[SVMXC__ServiceMax_User__c]								   AS [ServiceMaxServiceMax_User]
   ,[UserPreferencesGlobalNavBarWTShown]					   AS [UserPreferencesGlobalNavBarWTShown]
   ,[UserPreferencesGlobalNavGridMenuWTShown]				   AS [UserPreferencesGlobalNavGridMenuWTShown]
   ,[UserPreferencesCreateLEXAppsWTShown]					   AS [UserPreferencesCreateLEXAppsWTShown]
   ,[UserPreferencesFavoritesWTShown]						   AS [UserPreferencesFavoritesWTShown]
   ,ISNULL([SmallBannerPhotoUrl], '')						   AS [SmallBannerPhotoUrl]
   ,ISNULL([MediumBannerPhotoUrl], '')						   AS [MediumBannerPhotoUrl]
   ,[LastModifiedDate] AS LastUpdate
   ,GETUTCDATE() AS ImportDate
FROM [SF].[User];