CREATE TABLE [Pay].[DemographicHistory] (
    [RowId]                      INT             NOT NULL,
    [EmployeeId]                 INT             NOT NULL,
    [CompanyId]                  INT             NOT NULL,
    [SocialSecurityNumber]       NVARCHAR (50)   NOT NULL,
    [FirstName]                  NVARCHAR (50)   NOT NULL,
    [MiddleInitial]              CHAR (1)        NOT NULL,
    [LastName]                   NVARCHAR (50)   NOT NULL,
    [Address1]                   NVARCHAR (50)   NOT NULL,
    [Address2]                   NVARCHAR (50)   NOT NULL,
    [City]                       NVARCHAR (50)   NOT NULL,
    [State]                      NVARCHAR (50)   NOT NULL,
    [PostalCode]                 NVARCHAR (50)   NOT NULL,
    [County]                     NVARCHAR (50)   NOT NULL,
    [BirthDate]                  DATE            NULL,
    [HireDate]                   DATE            NULL,
    [AdjustedSeniorityDate]      DATE            NULL,
    [RehireDate]                 DATE            NULL,
    [EmploymentTerminationDate]  DATE            NULL,
    [TerminationReason]          NVARCHAR (50)   NOT NULL,
    [EmployeeStatus]             CHAR (1)        NOT NULL,
    [EmployeeTypeDescription]    NVARCHAR (50)   NOT NULL,
    [Gender]                     CHAR (1)        NOT NULL,
    [MaritalStatus]              CHAR (1)        NOT NULL,
    [HomePhone]                  NVARCHAR (50)   NOT NULL,
    [PersonalEmail]              NVARCHAR (50)   NOT NULL,
    [MobilePhone]                NVARCHAR (50)   NOT NULL,
    [WorkPhone]                  NVARCHAR (50)   NOT NULL,
    [WorkEmail]                  NVARCHAR (50)   NOT NULL,
    [WorkLocationName]           NVARCHAR (50)   NOT NULL,
    [JobTitle]                   NVARCHAR (100)  NOT NULL,
    [PositionCode]               NVARCHAR (50)   NOT NULL,
    [PositionDescription]        NVARCHAR (100)  NOT NULL,
    [CostCenter1]                NVARCHAR (50)   NOT NULL,
    [CostCenter1Description]     NVARCHAR (50)   NOT NULL,
    [CostCenter2]                NVARCHAR (50)   NOT NULL,
    [CostCenter2Description]     NVARCHAR (50)   NOT NULL,
    [CostCenter3]                NVARCHAR (50)   NOT NULL,
    [CostCenter3Description]     NVARCHAR (50)   NOT NULL,
    [Ethnicity]                  NVARCHAR (50)   NOT NULL,
    [EeoClass]                   NVARCHAR (50)   NOT NULL,
    [PayGroupCode]               NVARCHAR (50)   NOT NULL,
    [PayFrequency]               CHAR (1)        NOT NULL,
    [HourlyOrSalary]             NVARCHAR (50)   NOT NULL,
    [AnnualSalary]               DECIMAL (10, 2) NULL,
    [HourlyRate]                 DECIMAL (7, 2)  NULL,
    [DefaultHours]               INT             NOT NULL,
    [HighlyCompensated]          INT             NOT NULL,
    [BenefitClassCode]           NVARCHAR (50)   NOT NULL,
    [BenefitClassDescription]    NVARCHAR (50)   NOT NULL,
    [BenefitClassEffectiveDate]  DATE            NULL,
    [BenefitOverrideSalary]      NVARCHAR (50)   NOT NULL,
    [BenefitSalaryEffectiveDate] DATE            NULL,
    [BenefitHoursPerWeek]        DECIMAL (7, 2)  NULL,
    [BenefitLocation]            NVARCHAR (50)   NOT NULL,
    [BenefitDivision]            NVARCHAR (50)   NOT NULL,
    [BenefitTerminationDate]     DATE            NULL,
    [BadgeNumberClockNumber]     NVARCHAR (50)   NOT NULL,
    [WebTimeBadgeNumber]         INT             NULL,
    [EnableTimeandLabor]         CHAR (1)        NOT NULL,
    [EligibleforRehire]          CHAR (1)        NOT NULL,
    [TargetBonus]                VARCHAR (50)    NOT NULL,
    [Area]                       NVARCHAR (50)   NOT NULL,
    [UserDefinedField3]          NVARCHAR (50)   NOT NULL,
    [UserDefinedField4]          NVARCHAR (50)   NOT NULL,
    [UserDefinedField5]          NVARCHAR (50)   NOT NULL,
    [UserDefinedField6]          NVARCHAR (50)   NOT NULL,
    [UserDefinedField7]          NVARCHAR (50)   NOT NULL,
    [UserDefinedField8]          NVARCHAR (50)   NOT NULL,
    [UserDefinedField9]          NVARCHAR (50)   NOT NULL,
    [UserDefinedField10]         NVARCHAR (50)   NOT NULL,
    [ImportDate]                 DATETIME2 (7)   NOT NULL,
    [ImportFileName]             VARCHAR (80)    NOT NULL,
    [ImportFileDate]             DATE            NOT NULL,
    [LastUpdate]                 DATETIME2 (7)   NOT NULL,
    [ValidFrom]                  DATETIME2 (7)   NOT NULL,
    [ValidTo]                    DATETIME2 (7)   NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_DemographicHistory_RowId]
    ON [Pay].[DemographicHistory]([RowId] ASC);


GO
CREATE CLUSTERED INDEX [ix_DemographicHistory]
    ON [Pay].[DemographicHistory]([ValidTo] ASC, [ValidFrom] ASC);

