CREATE TABLE [Pay].[Vehicle] (
    [RowId]                         INT             IDENTITY (1, 1) NOT NULL,
    [YearMonth]                     INT             NOT NULL,
    [Vehicle]                       VARCHAR (50)    NOT NULL,
    [MasterCustomerNumber]          INT             NOT NULL,
    [MasterCustomerName]            VARCHAR (50)    NOT NULL,
    [CustomerNumber]                INT             NOT NULL,
    [CustomerName]                  VARCHAR (50)    NOT NULL,
    [CustomerVehicleIdCostCode]     VARCHAR (50)    NOT NULL,
    [Driver]                        VARCHAR (50)    NOT NULL,
    [Vin]                           VARCHAR (50)    NOT NULL,
    [Year]                          VARCHAR (50)    NOT NULL,
    [Make]                          VARCHAR (50)    NOT NULL,
    [Model]                         VARCHAR (50)    NOT NULL,
    [Series]                        VARCHAR (100)   NOT NULL,
    [LicenseState]                  VARCHAR (100)   NOT NULL,
    [LicenseNumber]                 VARCHAR (50)    NOT NULL,
    [LicenseExpirationDate]         INT             NULL,
    [DeliveryDate]                  INT             NULL,
    [FleetVehicleStatus]            VARCHAR (50)    NOT NULL,
    [FleetVehicleStatusDescription] VARCHAR (50)    NOT NULL,
    [LeaseType]                     VARCHAR (50)    NOT NULL,
    [LeaseTerm]                     INT             NULL,
    [MonthsInService]               INT             NULL,
    [ContractMileage]               INT             NULL,
    [DeliveredPrice]                DECIMAL (10, 2) NULL,
    [DepreciationPercent]           DECIMAL (5, 2)  NULL,
    [DepreciationAmountMonth]       DECIMAL (6, 2)  NULL,
    [TotalLeaseChargeMonth]         DECIMAL (7, 2)  NULL,
    [UseTaxAmountMonth]             DECIMAL (6, 2)  NULL,
    [FullMaintenanceRateMonth]      DECIMAL (7, 2)  NULL,
    [TotalRentMonth]                DECIMAL (8, 2)  NULL,
    [L&T]                           DECIMAL (8, 2)  NULL,
    [ServiceCharge]                 DECIMAL (8, 2)  NULL,
    [CurrentRbv]                    DECIMAL (8, 2)  NULL,
    [CalculatedMileage]             INT             NULL,
    [CalculatedMileageDate]         INT             NULL,
    [EnteredMileage]                INT             NULL,
    [EnteredMileageDate]            INT             NULL,
    [GarageStreetAddress1]          VARCHAR (50)    NOT NULL,
    [GarageCity]                    VARCHAR (50)    NOT NULL,
    [GarageState]                   VARCHAR (50)    NOT NULL,
    [GarageCountyName]              VARCHAR (50)    NOT NULL,
    [GaragePostalCode]              VARCHAR (50)    NOT NULL,
    [GarageCountry]                 VARCHAR (50)    NOT NULL,
    [RevenueProducing]              VARCHAR (50)    NOT NULL,
    [VehicleType]                   VARCHAR (50)    NOT NULL,
    [InsCategory]                   VARCHAR (50)    NOT NULL,
    [Count]                         VARCHAR (50)    NOT NULL,
    [Location]                      VARCHAR (50)    NOT NULL,
    [Parent]                        VARCHAR (50)    NOT NULL,
    [Reg]                           VARCHAR (50)    NOT NULL,
    CONSTRAINT [PK_Vehicle] PRIMARY KEY CLUSTERED ([RowId] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Vehicle_Vin_Vehicle_YearMonth]
    ON [Pay].[Vehicle]([Vin] ASC, [Vehicle] ASC, [YearMonth] ASC);

