CREATE VIEW SL.vwAccountsPayableDocument AS

SELECT
	[RowId]
   ,[Account]
   ,[RecordId]
   ,[CompanyId]
   ,[VendorId]
   ,[TransactionReferenceNumber]
   ,[DocumentDate]
   ,[DueDate]
   ,[DiscountDate]
   ,[DocumentType]
   ,[DocumentBalance]
   ,[CurrencyDocumentBalance]
   ,[SubaccountId]
   ,[ProfitCenterId]
   ,[LocationId]
   ,[PeriodToPost]
   ,[InvoiceNumber]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SL].[AccountsPayableDocument]