
CREATE VIEW [SF].[vwAccount]
AS
SELECT
	[RowId]
   ,[Id]
   ,IIF([IsDeleted] = 255, 1, [IsDeleted])												   AS [IsDeleted]
   ,[MasterRecordId]
   ,[Name]
   ,[Type]
   ,[RecordTypeId]
   ,[ParentId]
   ,[BillingStreet]
   ,[BillingCity]
   ,[BillingState]
   ,[BillingPostalCode]
   ,[BillingCountry]
   ,[BillingStateCode]
   ,[BillingCountryCode]
   ,[BillingLatitude]
   ,[BillingLongitude]
   ,[ShippingStreet]
   ,[ShippingCity]
   ,[ShippingState]
   ,[ShippingPostalCode]
   ,[ShippingCountry]
   ,[ShippingStateCode]
   ,[ShippingCountryCode]
   ,[ShippingLatitude]
   ,[ShippingLongitude]
   ,[Phone]
   ,[Fax]
   ,[Website]
   ,[Industry]
   ,[AnnualRevenue]
   ,[NumberOfEmployees]
   ,[Description]
   ,[Site]
   ,[OwnerId]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[LastActivityDate]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,IIF([IsCustomerPortal] = 255, 1, [IsCustomerPortal])								   AS [IsCustomerPortal]
   ,[Jigsaw]
   ,[JigsawCompanyId]
   ,[AccountSource]
   ,[SicDescription]
   ,[ServiceMaxAccess_Hours]
   ,[ServiceMaxBusiness_Hours]
   ,[ServiceMaxPreferred_Technician]
   ,[ServiceMaxLatitude]
   ,[ServiceMaxLongitude]
   ,[AccountStatus]
   ,[AccountFax]
   ,[AccountEmail]
   ,[ShippingPhone]
   ,[ShippingFax]
   ,[ShippingEmail]
   ,[PrimaryEquipmentAssetFee]
   ,[AncillaryEquipmentAssetFee]
   ,[SalesTerritoryId]
   ,[LaborRateStandard]
   ,[AccountsReceivableCustomerAccount]
   ,[Salesperson]
   ,IIF([TemporaryAccount] = 255, 1, [TemporaryAccount])								   AS [TemporaryAccount]
   ,[WorkTypes]
   ,[LaborRatePremium]
   ,[NumbeOfLocations]
   ,[BusinessUnit]
   ,[Organization]
   ,[NteThreshold]
   ,[PrimaryContact]
   ,[PrimaryContactEmail]
   ,[LaborRateTwoMan]
   ,[AccountCellPhone]
   ,[VendorId]
   ,[MaterialHandlingGeneralLedgerAccount]
   ,[LeadSourceMarketing]
   ,[MaterialHandlingCreditLimit]
   ,[MaterialHandlingSlCustomerId]
   ,[MaterialHandlingTerms]
   ,[MaterialHandlingAttention]
   ,[CustomerIdLegacy]
   ,[MaterialHandlingPrimaryContact]
   ,[PrimaryContactSalutation]
   ,[AverageDaysToPay]
   ,[MaterialHandlingTaxSchedule]
   ,[MaterialHandlingBillingContact]
   ,IIF([MaterialHandlingCreditHold] = 255, 1, [MaterialHandlingCreditHold])			   AS [MaterialHandlingCreditHold]
   ,[MaterialHandlingCurrentBalance]
   ,[MaterialHandlingCustomerType]
   ,IIF([MaterialHandlingEmailStatements] = 255, 1, [MaterialHandlingEmailStatements])	   AS [MaterialHandlingEmailStatements]
   ,[MaterialHandlingGeneralLedgerSubAccountId]
   ,[AccountsPayableAccount]
   ,[AccountsPayableSubaccountId]
   ,[LaborPmRateDdm]
   ,[LaborPmRateMhe]
   ,[Labor_StandardDdm]
   ,[Labor_StandardMhe]
   ,[Labor2ManDdm]
   ,[Labor2ManMhe]
   ,[LaborOtdDmDdm]
   ,[LaborOtmHeMhe]
   ,[LaborDtmHeMhe]
   ,[LaborDtdDmDdm]
   ,[AccountsReceivableDivisionNumber]
   ,[Company]
   ,[RemitAddress]
   ,[RemitCity]
   ,[RemitStateProvince]
   ,[RemitZipCode]
   ,[RemitCountry]
   ,[CustomerNotes]
   ,[SlVendorId]
   ,[BillingAttention]
   ,[BillingName]
   ,[RemitName]
   ,[RemitPhone]
   ,[AvailableCredit]
   ,[CreditRule]
   ,[MinerSalesperson]
   ,[CustomerTypeMarketingSegmets]
   ,IIF([TirePress] = 255, 1, [TirePress])												   AS [TirePress]
   ,[Salesperson2]
   ,[DeliveryVehicles]
   ,[Grade1]
   ,[Grade2]
   ,[AffiliateGrade]
   ,IIF([Docks] = 255, 1, [Docks])														   AS [Docks]
   ,IIF([Doors] = 255, 1, [Doors])														   AS [Doors]
   ,IIF([CustomerServiceRepresentativeCsr] = 255, 1, [CustomerServiceRepresentativeCsr])   AS [CustomerServiceRepresentativeCsr]
   ,[Oem]
   ,[ScissorBoomOem]
   ,[DeletedAccountId]
   ,[FaxIteration]
   ,[PhoneIteration]
   ,[PayTerms]
   ,[DrawDate]
   ,[Retainage]
   ,[OemAffiliation]
   ,[VendorExpenseType]
   ,[AccountParentSlVendorId]
   ,IIF([ReadyToConvert] = 255, 1, [ReadyToConvert])									   AS [ReadyToConvert]
   ,IIF([Affiliate] = 255, 1, [Affiliate])												   AS [Affiliate]
   ,[ParentAffiliate]
   ,[AccountCount]
   ,[DunsNumber]
   ,[Tradestyle]
   ,[NaicsCode]
   ,[NaicsDesc]
   ,[YearStarted]
   ,IIF([ResIdential] = 255, 1, [ResIdential])											   AS [ResIdential]
   ,[OpportunityTrade]
   ,[AccountParentMaterialHandlingSlCustomerId]
   ,[AccountApprover]
   ,[PhotoUrl]
   ,[UnityUserOwnerAgentId]
   ,IIF([IsPartner] = 255, 1, [IsPartner])												   AS [IsPartner]
   ,[AccountNumber]
   ,[Sic]
   ,[Ownership]
   ,[TickerSymbol]
   ,[Rating]
   ,[AllInPmRateElectric]
   ,[AllInPmRatePropane]
   ,IIF([ContractPaint] = 255, 1, [ContractPaint])										   AS [ContractPaint]
   ,IIF([DeliveryCapability] = 255, 1, [DeliveryCapability])							   AS [DeliveryCapability]
   ,IIF([MobileTirePressure] = 255, 1, [MobileTirePressure])							   AS [MobileTirePressure]
   ,[NumberOfServiceVans]
   ,[NumberOfTechs]
   ,IIF([OpportunityPending] = 255, 1, [OpportunityPending])							   AS [OpportunityPending]
   ,[PmRate]
   ,IIF([PaintBooth] = 255, 1, [PaintBooth])											   AS [PaintBooth]
   ,IIF([PartsDept] = 255, 1, [PartsDept])												   AS [PartsDept]
   ,IIF([Propane] = 255, 1, [Propane])													   AS [Propane]
   ,IIF([Refurbished] = 255, 1, [Refurbished])											   AS [Refurbished]
   ,IIF([ServiceBatteries] = 255, 1, [ServiceBatteries])								   AS [ServiceBatteries]
   ,[ServiceRate]
   ,IIF([TirePressure3rdParty] = 255, 1, [TirePressure3rdParty])						   AS [TirePressure3rdParty]
   ,[TripCharge]
   ,IIF([TripFee] = 255, 1, [TripFee])													   AS [TripFee]
   ,IIF([X24HourEmergencyRepair] = 255, 1, [X24HourEmergencyRepair])					   AS [X24HourEmergencyRepair]
   ,[SalespersonSecond]
   ,[Certificate]
   ,[FsoActive]
   ,[SuperCenter]
   ,[TaxId]
   ,[FsoCustomerPriority]
   ,[FsoNumberofLocations]
   ,[FsoSlaExpirationDate]
   ,[FsoSlaSerialNumber]
   ,[FsoSla]
   ,[FsoUpsellOpportunity]
   ,[AccountLoop]
   ,[BuUniqueField]
   ,[SlCompanyId]
   ,[SsvyLastVisitedDate]
   ,[SsvyTotalAssets]
   ,[SsvyTotalSiteSurveysCompleted]
   ,[TimeZoneOffset]
   ,[UnityAccountExternalId]
   ,[UnityAccountId]
   ,[UnityAccountRoutingId]
   ,[UnityAgentWorkDay]
   ,[UnityAgentWorkHourEndTime]
   ,[UnityAgentWorkHourStartTime]
   ,[UnityAutomobileLiabilityExpiry]
   ,IIF([UnityAutomobileLiability] = 255, 1, [UnityAutomobileLiability])				   AS [UnityAutomobileLiability]
   ,[UnityBillToAccount]
   ,IIF([UnityBillToHq] = 255, 1, [UnityBillToHq])										   AS [UnityBillToHq]
   ,[UnityBundling_Requirements]
   ,[UnityBusinessUnit]
   ,[UnityCompanyCode]
   ,[UnityCustomerSize]
   ,[UnityCustomerTeam]
   ,[UnityDispatcher]
   ,[UnityDoNotUseFlaggedDate]
   ,[UnityDoNotUseReason]
   ,IIF([UnityDoNotUse] = 255, 1, [UnityDoNotUse])										   AS [UnityDoNotUse]
   ,[UnityFridayEndTime]
   ,[UnityFridayStartTime]
   ,[UnityGeneralLiabilityExpiry]
   ,IIF([UnityGeneralLiability] = 255, 1, [UnityGeneralLiability])						   AS [UnityGeneralLiability]
   ,IIF([UnityHasPreferredPart] = 255, 1, [UnityHasPreferredPart])						   AS [UnityHasPreferredPart]
   ,[UnityHoursOfOperationSummary]
   ,[UnityHoursOfOperation]
   ,IIF([UnityIRS_ValIdated] = 255, 1, [UnityIRS_ValIdated])							   AS [UnityIRSValidated]
   ,[UnityIvrPhoneNumber]
   ,[UnityIvrPin]
   ,IIF([UnityInstallationFloaterLiability] = 255, 1, [UnityInstallationFloaterLiability]) AS [UnityInstallationFloaterLiability]
   ,[UnityInstallationFltLiabilityExpiry]
   ,IIF([UnityIsAccountsReceivable] = 255, 1, [UnityIsAccountsReceivable])				   AS [UnityIsAccountsReceivable]
   ,[UnityLoc]
   ,IIF([UnityMinerRegionalOffice] = 255, 1, [UnityMinerRegionalOffice])				   AS [UnityMinerRegionalOffice]
   ,[UnityMondayEndTime]
   ,[UnityMondayStartTime]
   ,[UnityOffHourQueue]
   ,[UnityPassword]
   ,[UnityPortalURL]
   ,IIF([UnityPreferred_Vendor] = 255, 1, [UnityPreferred_Vendor])						   AS [UnityPreferredVendor]
   ,[UnityRentedEquipmentLiabilityExpiry]
   ,IIF([UnityRentedEquipmentLiability] = 255, 1, [UnityRentedEquipmentLiability])		   AS [UnityRentedEquipmentLiability]
   ,[UnitySkillId2]
   ,[UnitySsn]
   ,[UnitySaturdayEndTime]
   ,[UnitySaturdayStartTime]
   ,IIF([UnityServiceChannelIvr] = 255, 1, [UnityServiceChannelIvr])					   AS [UnityServiceChannelIvr]
   ,[UnityServiceContract]
   ,[UnityShippingLocationLatitude]
   ,[UnityShippingLocationLongitude]
   ,IIF([UnitySignature_Required] = 255, 1, [UnitySignature_Required])					   AS [UnitySignatureRequired]
   ,[UnitySkillId]
   ,[UnitySubscriberId]
   ,[UnitySundayEndTime]
   ,[UnitySundayStartTime]
   ,[UnitySupportEmailAddress]
   ,IIF([UnityTaxExempt] = 255, 1, [UnityTaxExempt])									   AS [UnityTaxExempt]
   ,[UnityTaxId]
   ,[UnityThursdayEndTime]
   ,[UnityThursdayStartTime]
   ,[UnityTierLevel]
   ,[UnityTimeZoneSidKey]
   ,[UnityTuesdayEndTime]
   ,[UnityTuesdayStartTime]
   ,[UnityUmbrellaLiabilityExpiry]
   ,IIF([UnityUmbrellaLiability] = 255, 1, [UnityUmbrellaLiability])					   AS [UnityUmbrellaLiability]
   ,[UnityUsername]
   ,[UnityVendorScorePm]
   ,[UnityVendorScoreProject]
   ,[UnityVendorScoreSr]
   ,[UnityVendorScoreSs]
   ,[UnityVendorStatus]
   ,IIF([UnityVendorTypePm] = 255, 1, [UnityVendorTypePm])								   AS [UnityVendorTypePm]
   ,IIF([UnityVendorTypeProject] = 255, 1, [UnityVendorTypeProject])					   AS [UnityVendorTypeProject]
   ,IIF([UnityVendorTypeSr] = 255, 1, [UnityVendorTypeSr])								   AS [UnityVendorTypeSr]
   ,IIF([UnityVendorTypeSs] = 255, 1, [UnityVendorTypeSs])								   AS [UnityVendorTypeSs]
   ,IIF([UnityW9] = 255, 1, [UnityW9])													   AS [UnityW9]
   ,[UnityWednesdayEndTime]
   ,[UnityWednesdayStartTime]
   ,[UnityWorkersCompenstationLiabilityExpiry]
   ,IIF([UnityWorkersCompensationLiability] = 255, 1, [UnityWorkersCompensationLiability]) AS [UnityWorkersCompensationLiability]
   ,[UnityMnsCustomerTeam]
   ,[AccountParentUnityAccountExternalId]
   ,[UnityDoBusinessAs]
   ,[Unity0To30PastDue]
   ,[Unity31To60PastDue]
   ,[Unity61To90PastDue]
   ,[Unity90DaysPastDue]
   ,[UnitySlCurrentBalance]
   ,[UnityUltimateParent]
   ,[UnityTemplateConfiguration]
   ,[UnityFiscalYearBasedOn]
   ,[UnityFiscalYearStartMonth]
   ,[UnityServiceReportTemplate]
   ,IIF([Unity3rdPartyCustomer] = 255, 1, [Unity3rdPartyCustomer])						   AS [Unity3rdPartyCustomer]
   ,[BillingGeocodeAccuracy]
   ,[ShippingGeocodeAccuracy]
   ,[UnityCompany]
   ,[SlNotesText]
   ,[SlNotes]
   ,[SlPromiseDate]
   ,[MmpfsBuShippingAddress]
   ,[MspGoLiveDate]
   ,[UnityCompanyText]
   ,[UnityVendorId]
   ,[MspfsBuBillingAddress]
   ,[MspfsBusinessUnitLegalName]
   ,[MspfsMSPBillToAccount]
   ,[UnityVendorManager]
   ,IIF([UnityHasCommUnityMember] = 255, 1, [UnityHasCommUnityMember])					   AS [UnityHasCommunityMember]
   ,[UnityRecordTypeName]
   ,[UnityPmPin]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[Account];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwAccount] TO [OdsUser]
    AS [dbo];

