
CREATE VIEW [SF].[vwMaterialHandlingInvoiceDetail]
AS
SELECT
	[RowId]
   ,[Id]
   ,IIF([IsDeleted] = 255, 1, [IsDeleted]) AS [IsDeleted]
   ,[Name]
   ,[RecordTypeId]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[LastActivityDate]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,[WorkOrder]
   ,[Vendor]
   ,[LineType]
   ,[Part]
   ,[LinePricePerUnit]
   ,[LineQuantity]
   ,[SalesTax]
   ,[Invoice]
   ,IIF([AddToInvoice] = 255, 1, [AddToInvoice]) AS [AddToInvoice]
   ,[DateInvoiced]
   ,[ActivityType]
   ,[TotalLinePrice]
   ,[WorkDetail]
   ,[TLinePricePerUnit]
   ,[InvoiceStatus]
   ,[WorkDescription]
   ,[UnitOfMeasure]
   ,IIF([HideLine] = 255, 1, [HideLine]) AS HideLine
   ,[TotalLinePriceFormula]
   ,[SortOrder]
   ,[DetailLineCost]
   ,[AccountVendorSlVendorId]
   ,IIF([InterfaceProcessed] = 255, 1, [InterfaceProcessed]) AS [InterfaceProcessed]
   ,[AccountVendorSlCustomerId]
   ,[AccountVendorUnityAccountExternalId]
   ,[Product2PartUnityProductExternalId]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[MaterialHandlingInvoiceDetail];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwMaterialHandlingInvoiceDetail] TO [OdsUser]
    AS [dbo];

