CREATE VIEW SF.vwMaterialHandlingInvoiceDetail
AS
SELECT
	[RowId]
   ,[Id]
   ,[IsDeleted]
   ,[Name]
   ,[RecordTypeId]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[LastActivityDate]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,[WorkOrder]
   ,[Vendor]
   ,[LineType]
   ,[Part]
   ,[LinePricePerUnit]
   ,[LineQuantity]
   ,[SalesTax]
   ,[Invoice]
   ,[AddToInvoice]
   ,[DateInvoiced]
   ,[ActivityType]
   ,[TotalLinePrice]
   ,[WorkDetail]
   ,[TLinePricePerUnit]
   ,[InvoiceStatus]
   ,[WorkDescription]
   ,[UnitOfMeasure]
   ,[HideLine]
   ,[TotalLinePriceFormula]
   ,[SortOrder]
   ,[DetailLineCost]
   ,[AccountVendorSlVendorId]
   ,[InterfaceProcessed]
   ,[AccountVendorSlCustomerId]
   ,[AccountVendorUnityAccountExternalId]
   ,[Product2PartUnityProductExternalId]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[MaterialHandlingInvoiceDetail];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwMaterialHandlingInvoiceDetail] TO [OdsUser]
    AS [dbo];

