CREATE VIEW SF.vwProduct2
AS
SELECT
	[RowId]
   ,[Id]
   ,[Name]
   ,[ProductCode]
   ,[Description]
   ,[IsActive]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[Family]
   ,[RecordTypeId]
   ,[ExternalDataSourceId]
   ,[ExternalId]
   ,[DisplayUrl]
   ,[QuantityUnitOfMeasure]
   ,[IsDeleted]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,[ServiceMaxEnableSerializedTracking]
   ,[ServiceMaxInheritParentWarranty]
   ,[ServiceMaxProductCost]
   ,[ServiceMaxProductLine]
   ,[ServiceMaxSelect]
   ,[ServiceMaxStockable]
   ,[ServiceMaxTracking]
   ,[ServiceMaxUnitOfMeasure]
   ,[ServiceMaxReplacementAvailable]
   ,[Capacity]
   ,[HighUsageProduct]
   ,[Broad]
   ,[Group]
   ,[Type]
   ,[PartSerialNumber]
   ,[Model]
   ,[Make1]
   ,[UOM]
   ,[ProductId]
   ,[UnityProductExternalId]
   ,[SSVYOptimalCost]
   ,[UnityIsMenuPricing]
   ,[UnityAssetType]
   ,[UnityBumperThickness]
   ,[ServiceMaxProductType]
   ,[UnityIsStockable]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[Product2];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwProduct2] TO [OdsUser]
    AS [dbo];

