CREATE VIEW [SF].[vwProduct2]
AS
SELECT
	[RowId]
   ,[Id]
   ,[Name]
   ,[ProductCode]
   ,[Description]
   ,IIF([IsActive] = 255, 1, [IsActive]) AS IsActive
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[Family]
   ,[RecordTypeId]
   ,[ExternalDataSourceId]
   ,[ExternalId]
   ,[DisplayUrl]
   ,[QuantityUnitOfMeasure]
   ,IIF([IsDeleted] = 255, 1, [IsDeleted]) AS [IsDeleted]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,IIF([ServiceMaxEnableSerializedTracking] = 255, 1, [ServiceMaxEnableSerializedTracking]) AS [ServiceMaxEnableSerializedTracking]
   ,IIF([ServiceMaxInheritParentWarranty] = 255, 1, [ServiceMaxInheritParentWarranty]) AS [ServiceMaxInheritParentWarranty]
   ,[ServiceMaxProductCost]
   ,[ServiceMaxProductLine]
   ,IIF([ServiceMaxSelect] = 255, 1, [ServiceMaxSelect]) AS [ServiceMaxSelect]
   ,IIF([ServiceMaxStockable] = 255, 1, [ServiceMaxStockable]) AS [ServiceMaxStockable]
   ,[ServiceMaxTracking]
   ,[ServiceMaxUnitOfMeasure]
   ,IIF([ServiceMaxReplacementAvailable] =  255, 1, [ServiceMaxReplacementAvailable]) AS [ServiceMaxReplacementAvailable]
   ,[Capacity]
   ,IIF([HighUsageProduct] = 255, 1, [HighUsageProduct]) AS [HighUsageProduct]
   ,[Broad]
   ,[Group]
   ,[Type]
   ,[PartSerialNumber]
   ,[Model]
   ,[Make1]
   ,[UOM]
   ,[ProductId]
   ,[UnityProductExternalId]
   ,[SSVYOptimalCost]
   ,IIF([UnityIsMenuPricing] = 255, 1, [UnityIsMenuPricing]) AS [UnityIsMenuPricing]
   ,[UnityAssetType]
   ,[UnityBumperThickness]
   ,[ServiceMaxProductType]
   ,IIF([UnityIsStockable] = 255, 1, [UnityIsStockable]) AS [UnityIsStockable]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[Product2];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwProduct2] TO [OdsUser]
    AS [dbo];

