CREATE VIEW [SF].[vwServiceMaxSite]
AS
SELECT
	[RowId]
   ,[Id]
   ,[OwnerId]
   ,IIF([IsDeleted] = 255, 1, [IsDeleted]) AS [IsDeleted]
   ,[Name]
   ,[RecordTypeId]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[LastActivityDate]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,[Account]
   ,[City]
   ,IIF([Costedatvalue] = 255, 1, [Costedatvalue]) AS [CostedAtValue]
   ,[Country]
   ,[Email]
   ,[InventoryAccount]
   ,IIF([IsPartnerRecord] = 255, 1, [IsPartnerRecord]) AS [IsPartnerRecord]
   ,[IsPartner]
   ,[Latitude]
   ,[Longitude]
   ,[PartnerAccount]
   ,[PartnerContact]
   ,[ServiceEngineer]
   ,[SiteFax]
   ,[SitePhone]
   ,[State]
   ,IIF([StockingLocation] = 255, 1, [StockingLocation]) AS [StockingLocation]
   ,[Street]
   ,[Website]
   ,[Zip]
   ,IIF([IsDefaultDelivery] = 255, 1, [IsDefaultDelivery]) AS [IsDefaultDelivery]
   ,IIF([IsDeliveryLocation] = 255, 1, [IsDeliveryLocation]) AS [IsDeliveryLocation]
   ,IIF([IsGoodStock] = 255, 1, [IsGoodStock]) AS [IsGoodStock]
   ,IIF([IsReceivingLocation] = 255, 1, [IsReceivingLocation]) AS [IsReceivingLocation]
   ,IIF([IsRepairLocation] = 255, 1, [IsRepairLocation]) AS [IsRepairLocation]
   ,IIF([IsStagingLocation] = 255, 1, [IsStagingLocation]) AS [IsStagingLocation]
   ,[LocationType]
   ,[Parent]
   ,[MassSlLocationId]
   ,[Contact]
   ,[LocationEstablished]
   ,[LaborPMRateDDM]
   ,[LaborPMRateMHE]
   ,[MergerAcquisition]
   ,[BusinessUnit]
   ,[Priority]
   ,[OpenWorkOrders]
   ,[TerritoryId]
   ,[TravelTime]
   ,[Organization]
   ,[Ar]
   ,[NteThreshold]
   ,[SuperCenter]
   ,[Segment]
   ,[LaborRateStandard]
   ,[LaborRatePremium]
   ,[LaborRateTwoMan]
   ,[CustomerPo]
   ,[Contact2]
   ,[Contact3]
   ,[Contact4]
   ,[SiteMobile]
   ,[LaborStandardDDM]
   ,[LaborStandardMHE]
   ,[Labor2ManDDM]
   ,[Labor2ManMHE]
   ,[LaborOTDDMDDM]
   ,[LaborOTMHEMHE]
   ,[LaborDTDDMDDM]
   ,[LaborDTMHEMHE]
   ,IIF([CopyAddress] = 255, 1, [CopyAddress]) AS [CopyAddress]
   ,[BillingCity]
   ,[BillingStateProvince]
   ,[BillingZipPostalCode]
   ,[BillingStreet]
   ,[CallType]
   ,IIF([AccountCreditHold] = 255, 1, [AccountCreditHold]) AS [AccountCreditHold]
   ,IIF([TESTDATADONOTUSE] = 255, 1, [TESTDATADONOTUSE]) AS [TESTDATADONOTUSE]
   ,[Chain]
   ,[LocationSalesPerson]
   ,[Company]
   ,[Salesperson]
   ,IIF([DownloadToMobile] = 255, 1, [DownloadToMobile]) AS [DownloadToMobile]
   ,[SiteContact]
   ,[SalesPersons]
   ,[DocumentNumberLoc]
   ,[SalesPerson2ndLoc]
   ,[PmFrequencyMeter]
   ,[PmFrequencyTime]
   ,IIF([AssetManagementBillingDate] = 255, 1, [AssetManagementBillingDate]) AS [AssetManagementBillingDate]
   ,[AssetManagementFees]
   ,[StaticDocumentNumber]
   ,[InvoiceDocumentDate]
   ,[Retainage]
   ,[InvoiceDueDate]
   ,IIF([RequiresDepartmentRecord] = 255, 1, [RequiresDepartmentRecord]) AS [RequiresDepartmentRecord]
   ,[DrawDate]
   ,[CongaTemplate]
   ,[CongaCase]
   ,[PreferredBusinessHours]
   ,[RecurringRentalFees]
   ,[CongaPostToPeriod]
   ,[CongaTFSInvoiceQueryStringField]
   ,[CongaTFSInvoiceQueryStringField1]
   ,[CongaTFSInvoiceQueryStringField2]
   ,[Conga1P2P]
   ,[CongaMonth]
   ,[LocationCount]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[ServiceMaxSite];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwServiceMaxSite] TO [OdsUser]
    AS [dbo];

