CREATE VIEW [SF].[vwServiceMaxServiceOrder]
AS
SELECT
	[RowId]
   ,[Id]
   ,[OwnerId]
   ,IIF([IsDeleted] = 255, 1, [IsDeleted]) AS [IsDeleted]
   ,[Name]
   ,[RecordTypeId]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[LastActivityDate]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,[ServiceMaxAgeBucket]
   ,[ServiceMaxAge]
   ,[ServiceMaxBillingType]
   ,[ServiceMaxCity]
   ,[ServiceMaxCompany]
   ,[ServiceMaxComponent]
   ,[ServiceMaxConfigurationAfter]
   ,[ServiceMaxConfigurationBefore]
   ,[ServiceMaxContact]
   ,[ServiceMaxCountry]
   ,[ServiceMaxCustomerDownStatus]
   ,IIF([ServiceMaxCustomerDown] = 255, 1, [ServiceMaxCustomerDown]) AS [ServiceMaxCustomerDown]
   ,[ServiceMaxDispatchStatus]
   ,[ServiceMaxDrivingTime]
   ,[ServiceMaxEndpointURL]
   ,[ServiceMaxFirstQueuedDateTime]
   ,[ServiceMaxGroupEmail]
   ,[ServiceMaxGroupMember]
   ,[ServiceMaxIsPartner]
   ,[ServiceMaxLastDispatchEvent]
   ,[ServiceMaxMemberEmail]
   ,[ServiceMaxNoOfTimesQueued]
   ,[ServiceMaxNumberOfTimesQueuedBucket]
   ,[ServiceMaxNumberOfTimesScheduledBucket]
   ,[ServiceMaxOptiMaxStatus]
   ,[ServiceMaxOrderStatus]
   ,[ServiceMaxOrderType]
   ,[ServiceMaxPriority]
   ,[ServiceMaxProblemDescription]
   ,[ServiceMaxProduct]
   ,[ServiceMaxSessionId]
   ,[ServiceMaxScheduledDateTime]
   ,[ServiceMaxScheduledDate]
   ,[ServiceMaxTimeBetweenScheduleAndClose]
   ,[ServiceMaxTimeToAssign]
   ,[ServiceMaxTimeToQueue]
   ,[ServiceMaxTimeToSchedule]
   ,[ServiceMaxTimeBetweenAssignAndScheduleBucket]
   ,[ServiceMaxTimeBetweenQueueAndAssignBucket]
   ,[ServiceMaxTimeBetweenScheduleAndCloseBucket]
   ,[ServiceMaxTimetoAssignBucket]
   ,[ServiceMaxTimetoQueueBucket]
   ,[ServiceMaxTimetoScheduleBucket]
   ,[ServiceMaxTurnaroundTime]
   ,[ServiceMaxWorkPerformed]
   ,[ServiceMaxZip]
   ,[ServiceMaxTotalBillableAmount]
   ,[ServiceMaxTotalWorkOrderCost]
   ,[Location]
   ,IIF([ServiceMaxInvoiceCreated] = 255, 1, [ServiceMaxInvoiceCreated]) AS [ServiceMaxInvoiceCreated]
   ,[ServiceMaxInvoiceNumber]
   ,IIF([ServiceMaxIsEntitlementPerformed] = 255, 1, [ServiceMaxIsEntitlementPerformed]) AS [ServiceMaxIsEntitlementPerformed]
   ,IIF([ServiceMaxIsServiceCovered] = 255, 1, [ServiceMaxIsServiceCovered]) AS [ServiceMaxIsServiceCovered]
   ,IIF([ServiceMaxPerformAutoEntitlement] = 255, 1, [ServiceMaxPerformAutoEntitlement]) AS [ServiceMaxPerformAutoEntitlement] 
   ,[ServiceMaxSite]
   ,[ServiceMaxQtlStatus]
   ,[ServiceMaxQualifiedTechnicians]
   ,[ServiceMaxSkillSet]
   ,[ServiceMaxServiceZoneId]
   ,[EstimatedWorkDetailTotal]
   ,[WorkOrderDeniedReason]
   ,IIF([AdditionalServiceRecommended] = 255, 1, [AdditionalServiceRecommended]) AS [AdditionalServiceRecommended]
   ,IIF([EmergencyService] = 255, 1, [EmergencyService]) AS [EmergencyService]
   ,[SerialNumber]
   ,[AssetTag]
   ,[CustomerPurchaseOrder]
   ,[InvoiceTotal]
   ,[RecommendedService]
   ,[Make]
   ,[TfsServiceDate]
   ,[NteThreshold]
   ,[MheFaultCodesTierI]
   ,[MheFaultCodesTierII]
   ,[Model1]
   ,[Broad]
   ,[Group]
   ,[Type]
   ,[BroadLocation]
   ,[BroadReportable]
   ,[GroupLocation]
   ,[TypeLocation]
   ,[GroupReportable]
   ,[TypeReportable]
   ,IIF([TechnicianArrived] = 255, 1, [TechnicianArrived]) AS [TechnicianArrived]
   ,[DispatchStatus1]
   ,IIF([WorkOrderRollup] = 255, 1, [WorkOrderRollup]) AS [WorkOrderRollup]
   ,[LaborRateStandard]
   ,[MeterReading]
   ,[BusinessUnit]
   ,[WorkDetailCount]
   ,[TotalSalesTax]
   ,[FieldOffice]
   ,[VendorWorkDetailsOpen]
   ,[TotalCost]
   ,[EstimatedWorkTotal]
   ,[TfsInvoiceDate]
   ,[TfsDateEntered]
   ,[TfsVendorInvoice]
   ,[TfsVendorWorkOrder]
   ,[WorkOrderTotal]
   ,[SalesTaxTotal]
   ,[SuperCenter]
   ,[LaborPMRateDdm]
   ,[LaborPMRateMhe]
   ,[LaborStandardDdm]
   ,[LaborStandardMhe]
   ,[Labor2ManDdm]
   ,[Labor2ManMhe]
   ,[LaborOtddmDdm]
   ,[LaborOtmheMhe]
   ,[LaborDdmDdm]
   ,[LaborDTMheMhe]
   ,[JobInformation]
   ,[DockFault]
   ,[DoorFaultI]
   ,[GroupMiner]
   ,[FaultValidation]
   ,[VendorName]
   ,IIF([MeterReadingRequired] = 255, 1, [MeterReadingRequired]) AS [MeterReadingRequired]
   ,[DrawDate]
   ,[ContractInstall]
   ,[DoorFaultII]
   ,[SpecWasteFault]
   ,[DockSolutionI]
   ,IIF([InvoiceDenied] = 255, 1, [InvoiceDenied]) AS [InvoiceDenied]
   ,[MheResolutionCode]
   ,[DockSolutionII]
   ,[DoorSolutionI]
   ,[DoorSolutionII]
   ,[DoorSolutionIII]
   ,[SpecWastSolution]
   ,[EmailServiceReport]
   ,IIF([SendServiceReporttoCustomer] = 255, 1, [SendServiceReporttoCustomer]) AS [SendServiceReportToCustomer]
   ,IIF([EstimateNeeded] = 255, 1, [EstimateNeeded]) AS [EstimateNeeded]
   ,[ContractAmount]
   ,[ChangeOrderAmt]
   ,[Notes]
   ,IIF([Retainage] = 255, 1, [Retainage]) AS [Retainage]
   ,[RetainagePercentage]
   ,[ParentWorkOrder]
   ,[WorkOrderMargin]
   ,[ChangeOrderAmt2]
   ,[ChangeOrderAmt3]
   ,[ChangeOrderAmt4]
   ,[SignatureName]
   ,[Companycode]
   ,IIF([PartsNeededc] = 255, 1, [PartsNeededc]) AS [PartsNeeded]
   ,[EstimatePartsNotes]
   ,[WorkOrderMarginc2]
   ,[ContractTotal]
   ,IIF([WorkFinished] = 255, 1, [WorkFinished]) AS [WorkFinished]
   ,[InstalledProductName]
   ,[BroadIPwo]
   ,[GroupIPwo]
   ,[ServiceDateI]
   ,[LastWorkPerformed]
   ,[JobHistory]
   ,[ServiceMaxFinishedOnsiteDateTime]
   ,[ServiceMaxSchedulingChangeToken]
   ,[Salesperson]
   ,[InvoiceDateI]
   ,IIF([Locked] = 255, 1, [Locked]) AS [Locked]
   ,[LastMeterReading]
   ,[CustomerQueue]
   ,[SalespersonWorkOrder]
   ,[PartsCost]
   ,[TotalWorkOrderwTax]
   ,[RejectedInvoiceAmount]
   ,[LaborCost]
   ,[WorkPerformedTfs]
   ,[InvoicePostToPeriod]
   ,[DocumentNumber]
   ,[InvoiceDocument]
   ,[MakeIP]
   ,[ModelIP]
   ,[TotalInvoiced]
   ,[VendorInvoiceTotal]
   ,[SLInvoiceDate]
   ,[Salesperson2ndWorkOrder]
   ,[LocationName]
   ,IIF([TaxExemptProject] = 255, 1, [TaxExemptProject]) AS [TaxExemptProject]
   ,[EquipSalesInfo]
   ,[LastMeterReadingDate]
   ,[LastPmDate]
   ,[LastPmMeterReading]
   ,[PmDateDiff]
   ,[PmMeterDiff]
   ,[Certificate]
   ,IIF([RejectionOverride] = 255, 1, [RejectionOverride]) AS [RejectionOverride]
   ,IIF([PermanentRejection] = 255, 1, [PermanentRejection]) AS [PermanentRejection]
   ,[IPWarrantyEndDate]
   ,[DaysLeftUnderWarranty]
   ,[MeterLeftUnderWarranty]
   ,[ApprovalRequested]
   ,[ApprovalStatus]
   ,[AssignedApprover]
   ,[StaticDocNumber]
   ,[InvoiceReceivedDateI]
   ,[InvoiceReceivedDate]
   ,[AssetMgmtFees]
   ,[TfsAmfWorkOrder]
   ,[TaxCost]
   ,[IPDepartment]
   ,[CongaVendorName]
   ,[DrawDateNew]
   ,[DocNumberDate]
   ,IIF([ServiceReportFinalized] = 255, 1, [ServiceReportFinalized]) AS [ServiceReportFinalized]
   ,IIF([ServiceReportReceived] = 255, 1, [ServiceReportReceived]) AS [ServiceReportReceived]
   ,[SuperCenterName]
   ,[SuperCenter2]
   ,[FirstTimeDispatched]
   ,[ResponseTime]
   ,[DateTimeInvoiceCompleted]
   ,[DateTimeJobWorkComplete]
   ,[TimeToJobWorkComplete]
   ,[TimeToInvoiceCompleted]
   ,[Segment]
   ,[CanadianQSTPST]
   ,[CanadianGSTHSTTPS]
   ,[CanadianQSTPSTTVQ]
   ,[InvoicedLines]
   ,[TimetoBookRevenue]
   ,IIF([EditQuotedValues] = 255, 1, [EditQuotedValues]) AS [EditQuotedValues]
   ,[NonBillableItemApprovalStatus]
   ,[QuotedTotal]
   ,[WorkOrderType]
   ,[NonBillableLineItems]
   ,[NotBillablefromiPad]
   ,[ServiceNotes]
   ,[ServiceMaxSMLJSMinimumScheduleDuration]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[ServiceMaxServiceOrder];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwServiceMaxServiceOrder] TO [OdsUser]
    AS [dbo];

