CREATE VIEW [SF].[vwServiceMaxRmaShipmentLine]
AS
SELECT
	[RowId]
   ,[Id]
   ,IIF([IsDeleted] = 255, 1, [IsDeleted]) AS [IsDeleted]
   ,[Name]
   ,[RecordTypeId]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[RmaShipmentOrder]
   ,[ActualQuantity2]
   ,[ActualReceiptDate]
   ,[ActualShipDate]
   ,[CanceledBy]
   ,[CanceledOn]
   ,[ClosedBy]
   ,[ClosedOn]
   ,[DiscountPercentage]
   ,[DispositionInstructions]
   ,[Disposition]
   ,[ExpectedCondition]
   ,[ExpectedQuantity2]
   ,[ExpectedReceiptDate]
   ,[ExpectedShipDate]
   ,[LinePrice2]
   ,[LineStatus]
   ,[LineType]
   ,[PackingInstructions]
   ,[PartsRequestLine]
   ,IIF([PostedToInventory] = 255, 1, [PostedToInventory]) AS [PostedToInventory]
   ,[Product]
   ,[ReturnedCondition]
   ,[SalesOrderNumber]
   ,IIF([Select] = 255, 1, [Select]) AS [Select]
   ,[SerialNumber]
   ,[ServiceEngineer]
   ,[ServiceOrderLine]
   ,[ShipLocation]
   ,[TotalLinePrice2]
   ,IIF([UsePriceFromPricebook] = 255, 1, [UsePriceFromPricebook]) AS [UsePriceFromPricebook]
   ,[Warehouse]
   ,[CaseLine]
   ,[DeliveredBy]
   ,[DeliveredOn]
   ,IIF([Delivered] = 255, 1, [Delivered]) AS [Delivered]
   ,[DeliveryLocation]
   ,[MasterOrderLine]
   ,[PickedBy]
   ,[PickedOn]
   ,[PickedQuantity]
   ,IIF([Picked] = 255, 1, [Picked]) AS [Picked]
   ,[ReceivedBy]
   ,[ReceivedOn]
   ,IIF([Received] = 255, 1, [Received]) AS [Received]
   ,[ReconciliationAction]
   ,[RouteCard]
   ,[RouteStop]
   ,[SerialNumber_List]
   ,[ServiceOrder]
   ,[ShippedBy]
   ,[ShippedOn]
   ,IIF([Shipped] = 255, 1, [Shipped]) AS [Shipped]
   ,IIF([WorkOrderCreated] = 255, 1, [WorkOrderCreated]) AS [WorkOrderCreated]
   ,[EntitlementStatus]
   ,[FulfillmentQuantity]
   ,[ServiceContractEndDate]
   ,[ServiceContractStartDate]
   ,[WarrantyEndDate]
   ,[WarrantyStartDate]
   ,[EntitledExchangeType]
   ,[StandardCost]
   ,[MaterialHandlingTotalVendorLinePrice]
   ,[ProductName]
   ,[VendorPrice]
   ,[TotalStandardLinePrice]
   ,[PartNumber]
   ,[ShipVia]
   ,[CrossReferenceDescription]
   ,[CrossReferencePart]
   ,[ProductCrossReference]
   ,[OrderType]
   ,[ToLocationSupercenter]
   ,[ToLocationSegment]
   ,[SLVendorId]
   ,[CompanyId]
   ,[PartOrderName]
   ,[ProductCodePd]
   ,[TransactionResults]
   ,[Description]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[ServiceMaxRmaShipmentLine];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwServiceMaxRmaShipmentLine] TO [OdsUser]
    AS [dbo];

