CREATE VIEW [SF].[vwServiceMaxServiceOrderLine]
AS
SELECT
	[RowId]
   ,CAST([Id] AS NVARCHAR(18))	AS Id
   ,IIF([IsDeleted] = 255, 1, [IsDeleted]) AS [IsDeleted]
   ,[Name]
   ,[RecordTypeId]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,[ServiceOrder]
   ,[ActivityType]
   ,[ActualPrice2]
   ,[ActualQuantity2]
   ,[CanceledBy]
   ,[CanceledOn]
   ,[ClosedBy]
   ,[ClosedOn]
   ,[ConsumedFromLocation]
   ,[CostCategory]
   ,[DateReceived]
   ,[DateRequested]
   ,[Discount]
   ,[EndDateAndTime]
   ,[EstimatedPrice2]
   ,[EstimatedQuantity2]
   ,[ExpenseType]
   ,[FromLocation]
   ,[GroupMember]
   ,IIF([IncludeInQuote] = 255, 1, [IncludeInQuote]) AS [IncludeInQuote]
   ,IIF([IsBillable] = 255, 1, [IsBillable]) AS [IsBillable]
   ,[LineStatus]
   ,[LineType]
   ,[LogAgainst]
   ,IIF([PostedToInventory] = 255, 1, [PostedToInventory]) AS [PostedToInventory]
   ,[Product]
   ,[QuantityShipmentInitiated2]
   ,[QuantityShipped2]
   ,[ReceivedCity]
   ,[ReceivedCountry]
   ,[ReceivedLocation]
   ,[ReceivedQuantity2]
   ,[ReceivedState]
   ,[ReceivedStreet]
   ,[ReceivedZip]
   ,[ReferenceInformation]
   ,[RequestedCity]
   ,[RequestedCountry]
   ,[RequestedLocation]
   ,[RequestedQuantity2]
   ,[RequestedState]
   ,[RequestedStreet]
   ,[RequestedZip]
   ,IIF([Select] = 255, 1, [Select]) AS [Select]
   ,[SerialNumber]
   ,[ServiceGroup]
   ,[StartDateAndTime]
   ,[TotalEstimatedPrice]
   ,[TotalLinePrice]
   ,IIF([UsePriceFromPricebook] = 255, 1, [UsePriceFromPricebook]) AS [UsePriceFromPricebook]
   ,[WorkDescription]
   ,[EstimateOrActualPrice]
   ,[AppliedRateType]
   ,[Covered]
   ,[BillableLinePrice]
   ,[BillableQuantity]
   ,[BillingInformation]
   ,[ProductWarranty]
   ,[WorkDetail]
   ,[Vendor]
   ,[LaborType]
   ,[LaborPricePerUnit]
   ,IIF([AddtoInvoice] = 255, 1, [AddtoInvoice]) AS [AddtoInvoice]
   ,[ExtendedPrice]
   ,[PartSerialNumber]
   ,[LaborTime]
   ,[VendorStatus]
   ,[SalesTax]
   ,IIF([Invoiced] = 255, 1, [Invoiced]) AS [Invoiced]
   ,[DateInvoiced]
   ,IIF([WorkComplete] = 255, 1, [WorkComplete]) AS [WorkComplete]
   ,[DeliverDate]
   ,[InvoiceDetail]
   ,[TotalLinePriceWithTax]
   ,[PartsOrderLine]
   ,[VendorCostPerUnit]
   ,[VendorOrder]
   ,[Segment]
   ,[Supercenter]
   ,[DayComments]
   ,[InstalledProduct]
   ,[UnitofMeasure]
   ,[TotalCost]
   ,[InventoryLineQuantity]
   ,[ActualTime]
   ,[TechId]
   ,IIF([HideLine] = 255, 1, [HideLine]) AS [HideLine]
   ,IIF([Voucher] = 255, 1, [Voucher]) AS [Voucher]
   ,[Technician]
   ,[SortOrder]
   ,IIF([NonInventoryPart] = 255, 1, [NonInventoryPart]) AS [NonInventoryPart]
   ,[WdCreatedDate]
   ,[ServiceReportLine]
   ,IIF([IntegratedIn06] = 255, 1, [IntegratedIn06]) AS [IntegratedIn06]
   ,[ConsumedQuantity]
   ,[ConsumptionQuantity]
   ,IIF([ConsumedParts] = 255, 1, [ConsumedParts]) AS [ConsumedParts]
   ,[UsedQuantity]
   ,IIF([ReconciledQuantity] = 255, 1, [ReconciledQuantity]) AS [ReconciledQuantity]
   ,[TechnicianWd2]
   ,[CongaVendorName]
   ,[SerialNumberList]
   ,[TransactionResults]
   ,[ServiceReport]
   ,IIF([InterfaceProcessed] = 255, 1, [InterfaceProcessed]) AS [InterfaceProcessed]
   ,[TaxCode]
   ,IIF([LineFromiPad] = 255, 1, [LineFromiPad]) AS [LineFromiPad]
   ,[QuotedMarginPercent]
   ,[QuotedMargin]
   ,[QuotedQuantity]
   ,[QuotedUnitCost]
   ,[QuotedUnitPrice]
   ,IIF([Quoted] = 255, 1, [Quoted]) AS [Quoted]
   ,[TotalQuotedCost]
   ,[TotalQuotedPrice]
   ,IIF([UpdateQuotedWithActuals] = 255, 1, [UpdateQuotedWithActuals]) AS [UpdateQuotedWithActuals]
   ,[CompletedBy]
   ,[CompletedDate]
   ,[DeadTime]
   ,[EntitlementNotes]
   ,IIF([IsEntitlementPerformed] = 255, 1, [IsEntitlementPerformed]) AS [IsEntitlementPerformed]
   ,[ServiceMaintenanceContract]
   ,IIF([SlInventoryIssued] = 255, 1, [SlInventoryIssued]) AS [SlInventoryIssued]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[ServiceMaxServiceOrderLine];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwServiceMaxServiceOrderLine] TO [OdsUser]
    AS [dbo];

