CREATE VIEW [SF].[vwUser]
AS
SELECT
	[RowId]
   ,[Id]
   ,[Username]
   ,[LastName]
   ,[FirstName]
   ,[Name]
   ,[CompanyName]
   ,[Division]
   ,[Department]
   ,[Title]
   ,[Street]
   ,[City]
   ,[State]
   ,[PostalCode]
   ,[Country]
   ,[StateCode]
   ,[CountryCode]
   ,[Latitude]
   ,[Longitude]
   ,[Email]
   ,IIF([EmailPreferencesAutoBcc] = 255, 1, [EmailPreferencesAutoBcc]) AS [EmailPreferencesAutoBcc]
   ,IIF([EmailPreferencesAutoBccStayInTouch] = 255, 1, [EmailPreferencesAutoBccStayInTouch]) AS [EmailPreferencesAutoBccStayInTouch]
   ,IIF([EmailPreferencesStayInTouchReminder] = 255, 1, [EmailPreferencesStayInTouchReminder]) [EmailPreferencesStayInTouchReminder]
   ,[SenderEmail]
   ,[SenderName]
   ,[Signature]
   ,[StayInTouchSubject]
   ,[StayInTouchSignature]
   ,[StayInTouchNote]
   ,[Phone]
   ,[Fax]
   ,[MobilePhone]
   ,[Alias]
   ,[CommunityNickname]
   ,IIF([IsActive] = 255, 1, [IsActive]) AS [IsActive]
   ,[TimeZoneSidKey]
   ,[UserRoleId]
   ,[LocaleSidKey]
   ,IIF([ReceivesInfoEmails] = 255, 1, [ReceivesInfoEmails]) AS [ReceivesInfoEmails]
   ,IIF([ReceivesAdminInfoEmails] = 255, 1, [ReceivesAdminInfoEmails]) AS [ReceivesAdminInfoEmails]
   ,[EmailEncodingKey]
   ,[ProfileId]
   ,[UserType]
   ,[LanguageLocaleKey]
   ,[EmployeeNumber]
   ,[DelegatedApproverId]
   ,[ManagerId]
   ,[LastLoginDate]
   ,[LastPasswordChangeDate]
   ,[CreatedDate]
   ,[CreatedById]
   ,[LastModifiedDate]
   ,[LastModifiedById]
   ,[SystemModstamp]
   ,[OfflineTrialExpirationDate]
   ,[OfflinePdaTrialExpirationDate]
   ,IIF([UserPermissionsMarketingUser] = 255, 1, [UserPermissionsMarketingUser]) AS [UserPermissionsMarketingUser]
   ,IIF([UserPermissionsOfflineUser] = 255, 1, [UserPermissionsOfflineUser]) AS [UserPermissionsOfflineUser]
   ,IIF([UserPermissionsAvantgoUser] = 255, 1, [UserPermissionsAvantgoUser]) AS [UserPermissionsAvantGoUser]
   ,IIF([UserPermissionsCallCenterAutoLogin] = 255, 1, [UserPermissionsCallCenterAutoLogin]) AS [UserPermissionsCallCenterAutoLogin]
   ,IIF([UserPermissionsMobileUser] = 255, 1, [UserPermissionsMobileUser]) AS [UserPermissionsMobileUser]
   ,IIF([UserPermissionsSFContentUser] = 255, 1, [UserPermissionsSFContentUser]) AS [UserPermissionsSFContentUser]
   ,IIF([UserPermissionsInteractionUser] = 255, 1, [UserPermissionsInteractionUser]) AS [UserPermissionsInteractionUser]
   ,IIF([UserPermissionsSupportUser] = 255, 1, [UserPermissionsSupportUser]) AS [UserPermissionsSupportUser]
   ,IIF([UserPermissionsChatterAnswersUser] = 255, 1, [UserPermissionsChatterAnswersUser]) AS [UserPermissionsChatterAnswersUser]
   ,IIF([ForecastEnabled] = 255, 1, [ForecastEnabled]) AS [ForecastEnabled]
   ,IIF([UserPreferencesActivityRemindersPopup] = 255, 1, [UserPreferencesActivityRemindersPopup]) as [UserPreferencesActivityRemindersPopup]
   ,IIF([UserPreferencesEventRemindersCheckboxDefault] = 255, 1, [UserPreferencesEventRemindersCheckboxDefault]) as [UserPreferencesEventRemindersCheckboxDefault]
   ,IIF([UserPreferencesTaskRemindersCheckboxDefault] = 255, 1, [UserPreferencesTaskRemindersCheckboxDefault]) as [UserPreferencesTaskRemindersCheckboxDefault]
   ,IIF([UserPreferencesReminderSoundOff] = 255, 1, [UserPreferencesReminderSoundOff]) as [UserPreferencesReminderSoundOff]
   ,IIF([UserPreferencesDisableAllFeedsEmail] = 255, 1, [UserPreferencesDisableAllFeedsEmail]) as [UserPreferencesDisableAllFeedsEmail]
   ,IIF([UserPreferencesDisableFollowersEmail] = 255, 1, [UserPreferencesDisableFollowersEmail]) as [UserPreferencesDisableFollowersEmail]
   ,IIF([UserPreferencesDisableProfilePostEmail] = 255, 1, [UserPreferencesDisableProfilePostEmail]) as [UserPreferencesDisableProfilePostEmail]
   ,IIF([UserPreferencesDisableChangeCommentEmail] = 255, 1, [UserPreferencesDisableChangeCommentEmail]) as [UserPreferencesDisableChangeCommentEmail]
   ,IIF([UserPreferencesDisableLaterCommentEmail] = 255, 1, [UserPreferencesDisableLaterCommentEmail]) as [UserPreferencesDisableLaterCommentEmail]
   ,IIF([UserPreferencesDisProfPostCommentEmail] = 255, 1, [UserPreferencesDisProfPostCommentEmail]) as [UserPreferencesDisProfPostCommentEmail]
   ,IIF([UserPreferencesContentNoEmail] = 255, 1, [UserPreferencesContentNoEmail]) as [UserPreferencesContentNoEmail]
   ,IIF([UserPreferencesContentEmailAsAndWhen] = 255, 1, [UserPreferencesContentEmailAsAndWhen]) as [UserPreferencesContentEmailAsAndWhen]
   ,IIF([UserPreferencesApexPagesDeveloperMode] = 255, 1, [UserPreferencesApexPagesDeveloperMode]) as [UserPreferencesApexPagesDeveloperMode]
   ,IIF([UserPreferencesHideCSNGetChatterMobileTask] = 255, 1, [UserPreferencesHideCSNGetChatterMobileTask]) as [UserPreferencesHideCSNGetChatterMobileTask]
   ,IIF([UserPreferencesDisableMentionsPostEmail] = 255, 1, [UserPreferencesDisableMentionsPostEmail]) as [UserPreferencesDisableMentionsPostEmail]
   ,IIF([UserPreferencesDisMentionsCommentEmail] = 255, 1, [UserPreferencesDisMentionsCommentEmail]) as [UserPreferencesDisMentionsCommentEmail]
   ,IIF([UserPreferencesHideCSNDesktopTask] = 255, 1, [UserPreferencesHideCSNDesktopTask]) as [UserPreferencesHideCSNDesktopTask]
   ,IIF([UserPreferencesDisCommentAfterLikeEmail] = 255, 1, [UserPreferencesDisCommentAfterLikeEmail]) as [UserPreferencesDisCommentAfterLikeEmail]
   ,IIF([UserPreferencesDisableLikeEmail] = 255, 1, [UserPreferencesDisableLikeEmail]) as [UserPreferencesDisableLikeEmail]
   ,IIF([UserPreferencesDisableMessageEmail] = 255, 1, [UserPreferencesDisableMessageEmail]) as [UserPreferencesDisableMessageEmail]
   ,IIF([UserPreferencesOptOutOfTouch] = 255, 1, [UserPreferencesOptOutOfTouch]) as [UserPreferencesOptOutOfTouch]
   ,IIF([UserPreferencesDisableBookmarkEmail] = 255, 1, [UserPreferencesDisableBookmarkEmail]) as [UserPreferencesDisableBookmarkEmail]
   ,IIF([UserPreferencesDisableSharePostEmail] = 255, 1, [UserPreferencesDisableSharePostEmail]) as [UserPreferencesDisableSharePostEmail]
   ,IIF([UserPreferencesEnableAutoSubForFeeds] = 255, 1, [UserPreferencesEnableAutoSubForFeeds]) as [UserPreferencesEnableAutoSubForFeeds]
   ,IIF([UserPreferencesDisableFileShareNotificationsForApi] = 255, 1, [UserPreferencesDisableFileShareNotificationsForApi]) as [UserPreferencesDisableFileShareNotificationsForApi]
   ,IIF([UserPreferencesShowTitleToExternalUsers] = 255, 1, [UserPreferencesShowTitleToExternalUsers]) as [UserPreferencesShowTitleToExternalUsers]
   ,IIF([UserPreferencesShowManagerToExternalUsers] = 255, 1, [UserPreferencesShowManagerToExternalUsers]) as [UserPreferencesShowManagerToExternalUsers]
   ,IIF([UserPreferencesShowEmailToExternalUsers] = 255, 1, [UserPreferencesShowEmailToExternalUsers]) as [UserPreferencesShowEmailToExternalUsers]
   ,IIF([UserPreferencesShowWorkPhoneToExternalUsers] = 255, 1, [UserPreferencesShowWorkPhoneToExternalUsers]) as [UserPreferencesShowWorkPhoneToExternalUsers]
   ,IIF([UserPreferencesShowMobilePhoneToExternalUsers] = 255, 1, [UserPreferencesShowMobilePhoneToExternalUsers]) as [UserPreferencesShowMobilePhoneToExternalUsers]
   ,IIF([UserPreferencesShowFaxToExternalUsers] = 255, 1, [UserPreferencesShowFaxToExternalUsers]) as [UserPreferencesShowFaxToExternalUsers]
   ,IIF([UserPreferencesShowStreetAddressToExternalUsers] = 255, 1, [UserPreferencesShowStreetAddressToExternalUsers]) as [UserPreferencesShowStreetAddressToExternalUsers]
   ,IIF([UserPreferencesShowCityToExternalUsers] = 255, 1, [UserPreferencesShowCityToExternalUsers]) as [UserPreferencesShowCityToExternalUsers]
   ,IIF([UserPreferencesShowStateToExternalUsers] = 255, 1, [UserPreferencesShowStateToExternalUsers]) as [UserPreferencesShowStateToExternalUsers]
   ,IIF([UserPreferencesShowPostalCodeToExternalUsers] = 255, 1, [UserPreferencesShowPostalCodeToExternalUsers]) as [UserPreferencesShowPostalCodeToExternalUsers]
   ,IIF([UserPreferencesShowCountryToExternalUsers] = 255, 1, [UserPreferencesShowCountryToExternalUsers]) as [UserPreferencesShowCountryToExternalUsers]
   ,IIF([UserPreferencesShowProfilePicToGuestUsers] = 255, 1, [UserPreferencesShowProfilePicToGuestUsers]) as [UserPreferencesShowProfilePicToGuestUsers]
   ,IIF([UserPreferencesShowTitleToGuestUsers] = 255, 1, [UserPreferencesShowTitleToGuestUsers]) as [UserPreferencesShowTitleToGuestUsers]
   ,IIF([UserPreferencesShowCityToGuestUsers] = 255, 1, [UserPreferencesShowCityToGuestUsers]) as [UserPreferencesShowCityToGuestUsers]
   ,IIF([UserPreferencesShowStateToGuestUsers] = 255, 1, [UserPreferencesShowStateToGuestUsers]) as [UserPreferencesShowStateToGuestUsers]
   ,IIF([UserPreferencesShowPostalCodeToGuestUsers] = 255, 1, [UserPreferencesShowPostalCodeToGuestUsers]) as [UserPreferencesShowPostalCodeToGuestUsers]
   ,IIF([UserPreferencesShowCountryToGuestUsers] = 255, 1, [UserPreferencesShowCountryToGuestUsers]) as [UserPreferencesShowCountryToGuestUsers]
   ,[ContactId]
   ,[AccountId]
   ,[CallCenterId]
   ,[Extension]
   ,[PortalRole]
   ,IIF([IsPortalEnabled] = 255, 1, [IsPortalEnabled]) AS [IsPortalEnabled]
   ,IIF([IsPortalSelfRegistered] = 255, 1, [IsPortalSelfRegistered]) AS [IsPortalSelfRegistered]
   ,[FederationIdentifier]
   ,[AboutMe]
   ,[FullPhotoUrl]
   ,[SmallPhotoUrl]
   ,[DigestFrequency]
   ,[DefaultGroupNotificationFrequency]
   ,[LastViewedDate]
   ,[LastReferencedDate]
   ,[ServiceMaxDispatchConsoleSettings]
   ,IIF([ServiceMaxSelect] = 255, 1, [ServiceMaxSelect]) AS [ServiceMaxSelect]
   ,[ServiceMaxFaceTimeId]
   ,IIF([ServiceMaxIsSuperDispatcher] = 255, 1, [ServiceMaxIsSuperDispatcher]) AS [ServiceMaxIsSuperDispatcher]
   ,[BusinessUnit]
   ,[MaterialHandlingSalesPersonId]
   ,[SalesArea]
   ,[SuperCenter]
   ,[CustomerPod]
   ,[CompanyLegalName]
   ,IIF([TemporaryEmployee] = 255, 1, [TemporaryEmployee]) AS [TemporaryEmployee]
   ,IIF([UserPermissionsKnowledgeUser] = 255, 1, [UserPermissionsKnowledgeUser]) as [UserPermissionsKnowledgeUser]
   ,IIF([UserPermissionsJigsawProspectingUser] = 255, 1, [UserPermissionsJigsawProspectingUser]) as [UserPermissionsJigsawProspectingUser]
   ,IIF([UserPermissionsWorkDotComUserFeature] = 255, 1, [UserPermissionsWorkDotComUserFeature]) as [UserPermissionsWorkDotComUserFeature]
   ,IIF([UserPreferencesJigsawListUser] = 255, 1, [UserPreferencesJigsawListUser]) as [UserPreferencesJigsawListUser]
   ,IIF([UserPreferencesLightningExperiencePreferred] = 255, 1, [UserPreferencesLightningExperiencePreferred]) as [UserPreferencesLightningExperiencePreferred]
   ,[JigsawImportLimitOverride]
   ,[BadgeText]
   ,IIF([UserPreferencesHideChatterOnboardingSplash] = 255, 1, [UserPreferencesHideChatterOnboardingSplash]) as [UserPreferencesHideChatterOnboardingSplash]
   ,IIF([UserPreferencesHideSecondChatterOnboardingSplash] = 255, 1, [UserPreferencesHideSecondChatterOnboardingSplash]) as [UserPreferencesHideSecondChatterOnboardingSplash]
   ,IIF([UserPreferencesDisableFeedbackEmail] = 255, 1, [UserPreferencesDisableFeedbackEmail]) as [UserPreferencesDisableFeedbackEmail]
   ,IIF([UserPreferencesDisableWorkEmail] = 255, 1, [UserPreferencesDisableWorkEmail]) as [UserPreferencesDisableWorkEmail]
   ,IIF([UserPreferencesHideS1BrowserUI] = 255, 1, [UserPreferencesHideS1BrowserUI]) as [UserPreferencesHideS1BrowserUI]
   ,IIF([UserPreferencesDisableEndorsementEmail] = 255, 1, [UserPreferencesDisableEndorsementEmail]) as [UserPreferencesDisableEndorsementEmail]
   ,IIF([UserPreferencesPathAssistantCollapsed] = 255, 1, [UserPreferencesPathAssistantCollapsed]) as [UserPreferencesPathAssistantCollapsed]
   ,[UnityAgentId]
   ,[UserManagerUnityAgentId]
   ,IIF([UserPreferencesSortFeedByComment] = 255, 1, [UserPreferencesSortFeedByComment]) as [UserPreferencesSortFeedByComment]
   ,IIF([IgnoreValidations] = 255, 1, [IgnoreValidations]) as [IgnoreValidations]
   ,[UnityCustomerTeam]
   ,[UnityCustomerTeamsSelected]
   ,[UnityContactExternalId]
   ,[GeocodeAccuracy]
   ,IIF([UserPreferencesCacheDiagnostics] = 255, 1, [UserPreferencesCacheDiagnostics]) as [UserPreferencesCacheDiagnostics]
   ,IIF([UserPreferencesShowEmailToGuestUsers] = 255, 1, [UserPreferencesShowEmailToGuestUsers]) as [UserPreferencesShowEmailToGuestUsers]
   ,IIF([UserPreferencesShowManagerToGuestUsers] = 255, 1, [UserPreferencesShowManagerToGuestUsers]) as [UserPreferencesShowManagerToGuestUsers]
   ,IIF([UserPreferencesShowWorkPhoneToGuestUsers] = 255, 1, [UserPreferencesShowWorkPhoneToGuestUsers]) as [UserPreferencesShowWorkPhoneToGuestUsers]
   ,IIF([UserPreferencesShowMobilePhoneToGuestUsers] = 255, 1, [UserPreferencesShowMobilePhoneToGuestUsers]) as [UserPreferencesShowMobilePhoneToGuestUsers]
   ,IIF([UserPreferencesShowFaxToGuestUsers] = 255, 1, [UserPreferencesShowFaxToGuestUsers]) as [UserPreferencesShowFaxToGuestUsers]
   ,IIF([UserPreferencesShowStreetAddressToGuestUsers] = 255, 1, [UserPreferencesShowStreetAddressToGuestUsers]) as [UserPreferencesShowStreetAddressToGuestUsers]
   ,IIF([UserPreferencesPreviewLightning] = 255, 1, [UserPreferencesPreviewLightning]) as [UserPreferencesPreviewLightning]
   ,IIF([UserPreferencesHideEndUserOnboardingAssistantModal] = 255, 1, [UserPreferencesHideEndUserOnboardingAssistantModal]) as [UserPreferencesHideEndUserOnboardingAssistantModal]
   ,IIF([UserPreferencesHideLightningMigrationModal] = 255, 1, [UserPreferencesHideLightningMigrationModal]) as [UserPreferencesHideLightningMigrationModal]
   ,IIF([UserPreferencesHideSfxWelcomeMat] = 255, 1, [UserPreferencesHideSfxWelcomeMat]) as [UserPreferencesHideSfxWelcomeMat]
   ,IIF([UserPreferencesHideBiggerPhotoCallout] = 255, 1, [UserPreferencesHideBiggerPhotoCallout]) as [UserPreferencesHideBiggerPhotoCallout]
   ,[MediumPhotoUrl]
   ,[BannerPhotoUrl]
   ,IIF([IsProfilePhotoActive] = 255, 1, [IsProfilePhotoActive]) as [IsProfilePhotoActive]
   ,IIF([ServiceMaxServiceMax_User] = 255, 1, [ServiceMaxServiceMax_User]) as [ServiceMaxServiceMax_User]
   ,IIF([UserPreferencesGlobalNavBarWTShown] = 255, 1, [UserPreferencesGlobalNavBarWTShown]) as [UserPreferencesGlobalNavBarWTShown]
   ,IIF([UserPreferencesGlobalNavGridMenuWTShown] = 255, 1, [UserPreferencesGlobalNavGridMenuWTShown]) as [UserPreferencesGlobalNavGridMenuWTShown]
   ,IIF([UserPreferencesCreateLEXAppsWTShown] = 255, 1, [UserPreferencesCreateLEXAppsWTShown]) as [UserPreferencesCreateLEXAppsWTShown]
   ,IIF([UserPreferencesFavoritesWTShown] = 255, 1, [UserPreferencesFavoritesWTShown]) as [UserPreferencesFavoritesWTShown]
   ,[SmallBannerPhotoUrl]
   ,[MediumBannerPhotoUrl]
   ,[LastUpdate]
   ,[ImportDate]
   ,[ValidFrom]
   ,[ValidTo]
FROM [SF].[User];
GO
GRANT SELECT
    ON OBJECT::[SF].[vwUser] TO [OdsUser]
    AS [dbo];

