CREATE TABLE [Pay].[Vehicle] (
    [Vehicle]                          VARCHAR (50)  NULL,
    [Master Cust Num]                  VARCHAR (50)  NULL,
    [Master Cust Name]                 VARCHAR (50)  NULL,
    [Cust Num]                         VARCHAR (50)  NULL,
    [Cust Name]                        VARCHAR (50)  NULL,
    [Customer Vehicle ID Cost Code]    VARCHAR (50)  NULL,
    [Driver]                           VARCHAR (50)  NULL,
    [VIN]                              VARCHAR (50)  NULL,
    [Year]                             VARCHAR (50)  NULL,
    [Make]                             VARCHAR (50)  NULL,
    [Model]                            VARCHAR (50)  NULL,
    [Series]                           VARCHAR (100) NULL,
    [License State]                    VARCHAR (100) NULL,
    [License Num]                      VARCHAR (50)  NULL,
    [License Exp  Date]                VARCHAR (50)  NULL,
    [Delivery Date]                    VARCHAR (50)  NULL,
    [Fleet Vehicle Status]             VARCHAR (50)  NULL,
    [Fleet Vehicle Status Description] VARCHAR (50)  NULL,
    [Lease Type]                       VARCHAR (50)  NULL,
    [Lease Term]                       VARCHAR (50)  NULL,
    [Months In Service*]               VARCHAR (50)  NULL,
    [Contract Mileage]                 VARCHAR (50)  NULL,
    [Delivered Price]                  VARCHAR (50)  NULL,
    [Dep Pct]                          VARCHAR (50)  NULL,
    [Dep Amt Mo]                       VARCHAR (50)  NULL,
    [Total Lease Charge Mo]            VARCHAR (50)  NULL,
    [Use Tax Amt Mo]                   VARCHAR (50)  NULL,
    [Full Maint Rate Mo]               VARCHAR (50)  NULL,
    [Total Rent Mo]                    VARCHAR (50)  NULL,
    [L&T*]                             VARCHAR (50)  NULL,
    [Service Charge]                   VARCHAR (50)  NULL,
    [Current RBV*]                     VARCHAR (50)  NULL,
    [Calculated Mileage]               VARCHAR (50)  NULL,
    [Calculated Mileage Date]          VARCHAR (50)  NULL,
    [Entered Mileage]                  VARCHAR (50)  NULL,
    [Entered Mileage Date]             VARCHAR (50)  NULL,
    [Garage Street Address 1]          VARCHAR (50)  NULL,
    [Garage City]                      VARCHAR (50)  NULL,
    [Garage State ]                    VARCHAR (50)  NULL,
    [Garage County Name]               VARCHAR (50)  NULL,
    [Garage Postal Code]               VARCHAR (50)  NULL,
    [Garage Country]                   VARCHAR (50)  NULL,
    [Revenue Producing]                VARCHAR (50)  NULL,
    [Vehicle Type]                     VARCHAR (50)  NULL,
    [Ins Category]                     VARCHAR (50)  NULL,
    [Count]                            VARCHAR (50)  NULL,
    [Loc]                              VARCHAR (50)  NULL,
    [Parent]                           VARCHAR (50)  NULL,
    [Reg]                              VARCHAR (50)  NULL
);

