CREATE TABLE [Pay].[WebTime] (
    [Web Pay Employee ID]       VARCHAR (50) NULL,
    [Web Pay Company ID]        VARCHAR (50) NULL,
    [Badge Number]              VARCHAR (50) NULL,
    [Last Name]                 VARCHAR (50) NULL,
    [First Name]                VARCHAR (50) NULL,
    [MI]                        VARCHAR (50) NULL,
    [Title]                     VARCHAR (50) NULL,
    [Personal Email]            VARCHAR (50) NULL,
    [Work Email]                VARCHAR (50) NULL,
    [Mobile Number]             VARCHAR (50) NULL,
    [Pay Description]           VARCHAR (50) NULL,
    [Pay Type]                  VARCHAR (50) NULL,
    [Date]                      VARCHAR (50) NULL,
    [Rounded Time In]           VARCHAR (50) NULL,
    [Rounded Time Out]          VARCHAR (50) NULL,
    [Actual Time In]            VARCHAR (50) NULL,
    [Actual Time Out]           VARCHAR (50) NULL,
    [Hours]                     VARCHAR (50) NULL,
    [Rate]                      VARCHAR (50) NULL,
    [Earnings]                  VARCHAR (50) NULL,
    [Punch Type]                VARCHAR (50) NULL,
    [Labor Level 1 Code]        VARCHAR (50) NULL,
    [Labor Level 1 Description] VARCHAR (50) NULL,
    [Labor Level 2 Code]        VARCHAR (50) NULL,
    [Labor Level 2 Description] VARCHAR (50) NULL,
    [Labor Level 3 Code]        VARCHAR (50) NULL,
    [Labor Level 3 Description] VARCHAR (50) NULL,
    [Labor Level 4 Code]        VARCHAR (50) NULL,
    [Labor Level 4 Description] VARCHAR (50) NULL,
    [Labor Level 5 Code]        VARCHAR (50) NULL,
    [Labor Level 5 Description] VARCHAR (50) NULL,
    [PunchID]                   VARCHAR (50) NULL
);

