CREATE TABLE [Pay].[WebTime] (
    [RowId]                  INT            IDENTITY (1, 1) NOT NULL,
    [CompanyId]              INT            NULL,
    [EmployeeId]             INT            NULL,
    [BadgeNumber]            BIGINT         NULL,
    [LastName]               VARCHAR (50)   NULL,
    [FirstName]              VARCHAR (50)   NULL,
    [MiddleInitial]          CHAR (1)       NULL,
    [Title]                  VARCHAR (50)   NULL,
    [PersonalEmail]          VARCHAR (50)   NULL,
    [WorkEmail]              VARCHAR (50)   NULL,
    [MobileNumber]           VARCHAR (50)   NULL,
    [PayDescription]         VARCHAR (50)   NULL,
    [PayType]                VARCHAR (50)   NULL,
    [Date]                   DATE           NULL,
    [RoundedTimeIn]          VARCHAR (20)   NULL,
    [RoundedTimeOut]         VARCHAR (20)   NULL,
    [ActualTimeIn]           VARCHAR (20)   NULL,
    [ActualTimeOut]          VARCHAR (20)   NULL,
    [Hours]                  DECIMAL (5, 2) NULL,
    [PunchType]              VARCHAR (20)   NULL,
    [LaborLevel1Code]        VARCHAR (20)   NULL,
    [LaborLevel1Description] VARCHAR (50)   NULL,
    [LaborLevel2Code]        VARCHAR (20)   NULL,
    [LaborLevel2Description] VARCHAR (50)   NULL,
    [LaborLevel3Code]        VARCHAR (20)   NULL,
    [LaborLevel3Description] VARCHAR (50)   NULL,
    [LaborLevel4Code]        VARCHAR (20)   NULL,
    [LaborLevel4Description] VARCHAR (50)   NULL,
    [LaborLevel5Code]        VARCHAR (20)   NULL,
    [LaborLevel5Description] VARCHAR (50)   NULL,
    [PunchId]                INT            NULL,
    [FileName]               VARCHAR (80)   CONSTRAINT [DF_WebTime_FileName] DEFAULT ('') NOT NULL,
    CONSTRAINT [PKWebTime] PRIMARY KEY CLUSTERED ([RowId] ASC)
);



